### ISSUE TITLE
[1.16] Industrial Foregoing machines will stop drawing power from Mekanism cables on server (re)start

### ISSUE THREAD

**Issue by Venthos** [InnovativeOnlineIndustries/Industrial-Foregoing#1003]
**Minecraft Version:** 1.16.5
**Forge Version:** forge-1.16.5-36.0.14

**Industrial Foregoing Version:** industrial-foregoing-1.16.5-3.2.9.1
**Titanium Version:** titanium-1.16.4-3.2.5
**Mekanism Version:** Mekanism-1.16.4-10.0.19.446

I am experiencing the same problem as was itemized in this bug report https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/764

Machines that are successfully attached to and drawing power from Mekanism power cables cease to draw power from these cables upon server restart.  Either destroying the attached cable and replacing it or using Mekanism's Configurator to cycle the normal/push/pull back around again will cause the machines to draw power again until next server restart.  Machines from other mods do not seem to be affected, suggesting this behavior is isolated to Industrial Foregoing.

**Comment by Buuz135** [comment]
Are the cables and the machines in the same chunk?

**Comment by Venthos** [comment]
Overall, the cables powering the machines do span multiple chunks.  Of the Industrial Foregoing machines I'm using, one (1) of them do have their machine/cable connection at a chunk border, but the other five (5) connect within their same chunk.  All six (6) machines are affected by this issue.  Screenshots attached.

Here you see the two near Fluid Extractors and one Latex Processing Unit with connections within the same chunk.
![2021-02-05_12 16 33](https://user-images.githubusercontent.com/1847925/107066885-864a8a80-67ac-11eb-8053-6986535f09ca.png)

Here you see the near Fluid Extractor connected across a chunk boundary, but the far Fluid Extractor is connected in the same chunk (as is the Dissolution Chamber).
![2021-02-05_12 16 46](https://user-images.githubusercontent.com/1847925/107066897-8ba7d500-67ac-11eb-9878-7e3196bf153f.png)

**Comment by JeffsRealm** [comment]
I would report this to Mekanism, I am having the same issue with Mekanism Cables connected to Mekanism Machines, Industrual Foregoing and the refined storage. Same issue on start up and log in.

**Comment by Buuz135** [comment]
I don't think it's an IF issue, the cable needs to push power.
