### ISSUE TITLE
[1.16] Block breaker crash client and server

### ISSUE THREAD

**Issue by Realever** [InnovativeOnlineIndustries/Industrial-Foregoing#1004]
My server is crashed after i place the block breaker from your mod and now my server don´t start anymore.I testit it in a singleplayer world  and the same thing happen there too.

Forge version:  36.0.13
Industrial Foregoing version: industrial-foregoing-1.16.5-3.2.9.2-2b762d7.jar
Titanium version: titanium-1.16.5-3.2.6.2.jar
Pastebin: https://pastebin.com/BNJje2kt

**Comment by Buuz135** [comment]
Report it to Effortless Building, they are sending a packet to a fake player.
