### ISSUE TITLE
[1.16] Items are voided inside of a plant sower when the sower is broken.

### ISSUE THREAD

**Issue by shattyyt** [InnovativeOnlineIndustries/Industrial-Foregoing#1005]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**3.2.9.1 fbef27c

**Titanium Version:**3.2.6.1

**Crashlog If Applicable (Upload to pastebin/gist):**
self explanatory.

**Comment by Buuz135** [comment]
Update the mods...
