### ISSUE TITLE
[1.16] black hole unit adding ntb tags if manually adding items

### ISSUE THREAD

**Issue by bdudek** [InnovativeOnlineIndustries/Industrial-Foregoing#1006]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:** 1.16.5-3.2.9.2-2b762d7

**Titanium Version:** 1.16.5-3.2.6.2

**Crashlog If Applicable (Upload to pastebin/gist):**
 with the black hole units when I manually add items to them it adds  an NTB tag to the item and they won't stack with it when trying to add items from a refined storage system
 link to screenshots of an example https://imgur.com/a/1eyrS6I

**Comment by RyanRidere** [comment]
I experience the NBT tag issue when picking up a placed Black Hole Unit with contents inside. All of the contents will now have the NBT 2 tags flag, as seen in bducek's screenshots, and the items will no longer stack with other items.

If I place an empty BHU down and manually add items, it does not alter the NBT tag data. It's only once I pick up the entire BHU with contents inside.

IF Version: industrial-foregoing-1.16.5-3.2.9.1-fbef27c

**Comment by bdudek** [comment]
I had that as well and when it came to manually add the items it happened when I ended up clicking relatively quickly it could have been I had some with the ntb tag in my inv and I thought it came when I manually added them quickly withdrew some again I'm going to have to check again when I get a chance to get on my world

**Comment by Buuz135** [comment]
I can't replicate it, does anyone have the steps to do it with just IF and maybe with Refined Storage too?

**Comment by TemperedFool** [comment]
I don't know if this is exactly how I did it, but I've seen the same thing and think this is how it happened - playing Enigmatica 6 0.3.13:

- Use PNC Omnihopper to pull PNC Gelatin from a PNC Mixer into a Black Hole Unit
- Pick up BHU, put it in a Black Hole Controller.
- Take BHU out of controller, break controller, put the BHU back
- NBT now doesn't match with the Gelatin being produced by the mixer, and the omnihopper will not push it in

If I can supply more info I'd be happy to, including a world download if it would help.

**Comment by Buuz135** [comment]
A mod is adding the tags when placed, idk which mod because in dev doesn't happen
