### ISSUE TITLE
[1.16] Issue Title

### ISSUE THREAD

**Issue by drunkripper** [InnovativeOnlineIndustries/Industrial-Foregoing#1009]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**
MC Version 1.16.5
Direwolf20 1.16.5 Version 1.6.1
Industrial Foregoing Version: 3.2.9.1
Titanium Version: 3.2.5

Plant Sower does not work. Tested in brand new superflat world as well. Installed range upgrades, tried vanilla seeds, and will not plant.

**Comment by Buuz135** [comment]
It does work, there might be something wrong with your setup, please use discord for support.
