### ISSUE TITLE
[1.16] Server crash with block placer

### ISSUE THREAD

**Issue by ChloeDawn** [InnovativeOnlineIndustries/Industrial-Foregoing#1014]
Block placer seems to have hit an NPE on the fake player connection. Happened whilst I was asleep so idk what was happening at the time of the crash.

**Industrial Foregoing Version:**
1.16.5-3.2.9.2-2b762d7

**Titanium Version:**
1.16.5-3.2.6.2

**Crashlog If Applicable (Upload to pastebin/gist):**
https://gist.github.com/ChloeDawn/576b35ddd952dd79c4f2687d471b319d

**Comment by Buuz135** [comment]
Effortless Building issue

**Comment by ChloeDawn** [comment]
What is the issue exactly? The assume the fake player is a real player? How do they need to check?

**Comment by Buuz135** [comment]
They are sending packets to fake players (which they don't have a connection), so they need to filter out fake players
