### ISSUE TITLE
My server cmd will output a lot of message

### ISSUE THREAD

**Issue by kocreeper1** [InnovativeOnlineIndustries/Industrial-Foregoing#1016]
Industrial Foregoing Version: 1.12.2-1.12.8-232

I put this mod in my server , when i use the mob_slaughter_factory , my server cmd will output a lot of message , like this:
''[18:18:27] [Server thread/INFO] [STDERR]: [com.robertx22.onevent.OnMobDeathDrops:mobOnDeathDrop:78]:    at java.lang.Thread.run(Unknown Source)''

**Comment by castilio20** [comment]
next use the last update before you report a error you are using and old version update tp industrialforegoing-1.12.2-1.12.13-237.jar

**Comment by kocreeper1** [comment]
I change to industrialforegoing-1.12.2-1.12.13-237.jar but it still output

**Comment by Buuz135** [comment]
Not a IF issue and unsupported version

**Comment by kocreeper1** [comment]
sorry i don't understand

**Comment by castilio20** [comment]
that is not a Industrial Forgoing issue and 1.12 has no longer support

**Comment by kocreeper1** [comment]
OK thank you
