### ISSUE TITLE
[1.12] Animal Rancher only works in short bursts when milking multiple (about 100) fluid cows at once

### ISSUE THREAD

**Issue by AnotexX** [InnovativeOnlineIndustries/Industrial-Foregoing#1019]
The animal rancher machine only milks my Blazing Pyrotheum fluid cows in short bursts every about 5 minutes. I have the speed I and II upgrades, as well as a +5 Range Addon. It seems to have no specific working condition and it is completely random. Redstone controls, different addons, position, number of cows, etc does not seem to have an effect. I'm not sure if this is intentional in order to keep the animal rancher from being to OP, but it would be nice if it milked any cow in its area, whenever it is milkable.

**Industrial Foregoing Version:**  whatever is on the current build of Project Ozone 3

**TeslaCoreLib Version:** whatever is on the current build of Project Ozone 3

**Crashlog If Applicable (Upload to pastebin/gist):** N/A

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
