### ISSUE TITLE
[1.16] Mystical agriculture ores not added to ore laser recipes

### ISSUE THREAD

**Issue by LuciusV** [InnovativeOnlineIndustries/Industrial-Foregoing#1022]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
1.16.5-3.2.9.2-2b762d7
**Titanium Version:**
1.16.4-3.2.5
**Crashlog If Applicable (Upload to pastebin/gist):**

**Comment by MrStatman80** [comment]
Any chance you adding Soulium ore to the Brown laser lens when in the nether?

As it doesn't exist at the moment with anything from Industrial Foregoing for the lasers.
If not that sorry to bother you
