### ISSUE TITLE
[1.16] Material StoneWork Factory output configuration UI partially broken

### ISSUE THREAD

**Issue by ByFe** [InnovativeOnlineIndustries/Industrial-Foregoing#1023]
**Industrial Foregoing Version:**
1.16.5-3.2.9.2-2b762d7

**Titanium Version:**
1.16.5-3.2.6.2

**Description:**
The output configuration buttons for the last two outputs are "merged" together, so the red output isn't configurable (see screenshot below).

![grafik](https://user-images.githubusercontent.com/5130914/108195588-42467680-7118-11eb-8e3a-fc279722037c.png)

**Comment by Buuz135** [comment]
Fixed
