### ISSUE TITLE
[1.16] Enchantment Applicator deletes tank contents if filled above default capacity

### ISSUE THREAD

**Issue by ChloeDawn** [InnovativeOnlineIndustries/Industrial-Foregoing#1025]
**Industrial Foregoing Version:** 1.16.5-3.2.10-09eb824
**Titanium Version:** 1.16.5-3.2.7

If you attempt to fill an Enchantment Applicator above the default capacity (32000mb) when the config is set higher (e.g. 112000mb), once it hits 32000mb the tank resets to 0.

![Recording of enchantment applicator deleting contents](https://thumbs.gfycat.com/TenderLazyAchillestang-max-14mb.gif)

**Comment by ChloeDawn** [comment]
(It doesn't delete the contents, it just doesn't update correctly.)

**Comment by Buuz135** [comment]
Minecraft issue
