### ISSUE TITLE
[1.16] Weird shading and texturing on chests with shaders

### ISSUE THREAD

**Issue by BentoGambin** [InnovativeOnlineIndustries/Industrial-Foregoing#1034]
![2021-02-24_20 57 32](https://user-images.githubusercontent.com/41645690/109082823-6a6b4200-76e3-11eb-8766-96cc9341dedd.png)
![2021-02-24_17 42 43](https://user-images.githubusercontent.com/41645690/109082830-71925000-76e3-11eb-87a3-018dfda7b63e.png)
As you can see, on the first pic, there are only 4 mods loaded: Titanium, IF, OF and forge mod loader (counts as one).
   
Bug happens with a few shaders: Chocapic13's and Loop (https://www.curseforge.com/minecraft/customization/chocapic13-shaders and https://github.com/espen96/Loop/tree/loop2); I'm already in contact with the later shader's dev.

Tested on a modpack with 107 mods, including IF, bug is there. 
Remove only IF (left even Titanium there) and bug is gone (chest's have no problems).
  
I'd like to know if there is a config that I can change to disable any change that this mod does to entity rendering.

**Industrial Foregoing Version:** industrial-foregoing-1.16.5-3.2.10-09eb824

**Titanium Version:** titanium-1.16.5-3.2.7

**Crashlog If Applicable (Upload to pastebin/gist):**  N.A.

**Optifine** OptiFine_1.16.5_HD_U_G7
**shader**: loop and chocapic13.

**Comment by Buuz135** [comment]
Won't fix, can't fix optifine stuff
