### ISSUE TITLE
[1.16.5] The machines shut down when we all leave the server

### ISSUE THREAD

**Issue by signormorte** [InnovativeOnlineIndustries/Industrial-Foregoing#1035]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:*industrial-foregoing-1.16.5-3.2.10-09eb824*

**Titanium Version:*titanium-1.16.5-3.2.7*

**Crashlog If Applicable (Upload to pastebin/gist):*no crashlog*

We have all noticed the fact that when we leave the server all the industrial foregoing machinery stops working, despite the chickenchunks chunck loaders

**Comment by Buuz135** [comment]
Not an IF issue, might not be properly loaded
