### ISSUE TITLE
[1.16] Server crash after locking inputs on IF Sower/Biorector

### ISSUE THREAD

**Issue by natebc** [InnovativeOnlineIndustries/Industrial-Foregoing#1041]
Enigmatica 6 modpack version 0.4.1

Not sure which machine was involved, maybe you can tell in the crashlog? What i did was lock inputs on my sower and Bioreactor and reconfigure xnet to filter the seeds/produce to the right places. VERY shortly before the crash I removed grapes and added demon fruit (for whatever reason the gatherer wasn't gathering grapes?). So, I'm not sure if it was the injection of a demon fruit, or something else exactly that caused this. I'll poke around a bit more if the server recovers ... lol?

**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.10-09eb824.jar

**Titanium Version:**
titanium-1.16.5-3.2.7.jar

**Crashlog If Applicable (Upload to pastebin/gist):**
https://gist.github.com/natebc/7ef1f7cf7080e29f2c614b32b7d01d35

**Comment by natebc** [comment]
Occurs to me that this does also involve xnet so if you think i should take this to them, let me know. I'm happy to do that as well.

**Comment by natebc** [comment]
Does seem to have persisted through the restart. Lucikly i had a backup about 30 minutes before which should predate me locking the inputs so we'll see.

**Comment by ThatPreston** [comment]
This is a problem with the titanium dependency for the mod. There is already an issue there addressing it and a pending pull request. https://github.com/InnovativeOnlineIndustries/Titanium/issues/84

**Comment by Buuz135** [comment]
PR Merged
