### ISSUE TITLE
[1.16.5] Issue Title

### ISSUE THREAD

**Issue by signormorte** [InnovativeOnlineIndustries/Industrial-Foregoing#1042]
Industrial Foregoing Version:industrial-foregoing-1.16.5-3.2.10-09eb824

Titanium Version:titanium-1.16.5-3.2.7
![2021-02-28_22 58 14](https://user-images.githubusercontent.com/48535373/109435073-c7833280-7a18-11eb-8752-6e080a0c78d7.png)

It no longer produces ether gas, I tried both to make the machinery and to rebuild the structure from scratch and create another wither but nothing to do

**Comment by Buuz135** [comment]
The wither needs to be higher, please use discord for support.
