### ISSUE TITLE
Enchantment Factory Not Accepting Mob Essence from Refined Storage Exporters

### ISSUE THREAD

**Issue by DizzyDJW** [InnovativeOnlineIndustries/Industrial-Foregoing#1045]
Industrial Foregoing Version: 3.2.9.1

Issue: Basically, exactly as the title states. The Enchantment Factory even after breaking both it and Refined Storage's Exporter, refuses to accept mob essence after already functioning fine for literal hours of gameplay. It was at one point accepting the liquid without issue. I have obviously already checked both the connection to the liquid and the amount of liquid I have, (which is hundreds) and I still can't see why it suddenly stopped accepting mob essence from Refined Storage's Exporter.

It will accept from literally anything else.

**Comment by Buuz135** [comment]
Cannot replicate
