### ISSUE TITLE
[1.16] I don't have conduits in my game

### ISSUE THREAD

**Issue by Sir555** [InnovativeOnlineIndustries/Industrial-Foregoing#1046]
**Industrial Foregoing Version: industrial-foregoing-1.16.5-3.2.10.1-decb7ae.jar

**Titanium Version: titanium-1.16.5-3.2.8.jar

So my problem is that I don't have conduits in my game so I can not play the mod. It would be greatly appreciated if somebody could help me.

**Comment by Buuz135** [comment]
Idk, this hasn't had conduits ever, add a mod that does

**Comment by Sir555** [comment]
Thanks I only watched a tutorial and they hat son conduits so I got
confused 😅.

Buuz135 <notifications@github.com> schrieb am Mi., 3. März 2021, 16:40:

**Comment by Sir555** [comment]
And do you many have a suggestion that works for 1.16.4?

Sir gaming <reutersimon1@gmail.com> schrieb am Mi., 3. März 2021, 17:24:
