### ISSUE TITLE
[1.16] Hydroponic Bed output doesnt seem to do anything?

### ISSUE THREAD

**Issue by BenOHedges** [InnovativeOnlineIndustries/Industrial-Foregoing#1047]
Playing with the Hydroponic  Bed and i assume its either supposed to automatically harvest the crop and put it in its inventory ready to be outputted or grow crops quickly and you use Plant Gatherer to harvest it which makes the internal inventory not really needed. Either way im not sure if its supposed to auto harvest or the output gui is not required if not.

Industrial Foregoing Version: industrial-foregoing-1.16.5-3.2.9.1-fbef27c

I checked the change logs for the most recent versions after the version im using because i cant update the server.  I didnt see any issue talking about this and thought i mention it.

Do let me know if im using it wrong

![image_2021-03-04_224610](https://user-images.githubusercontent.com/74880181/110040920-6a9abb80-7d3b-11eb-9ed2-6c84f97a5640.png)

Prior testing was to see if it would grow pumpkins but it only sped up the stem growth hence the dirt block being there

**Comment by Buuz135** [comment]
Read the manual, if you don't have it install patchoul.
