### ISSUE TITLE
[1.16] Missing lang keys for certain machine button tooltips

### ISSUE THREAD

**Issue by aaronhowser1** [InnovativeOnlineIndustries/Industrial-Foregoing#1049]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.10.1-decb7ae
**Titanium Version:**
titanium-1.16.5-3.2.8
![image](https://user-images.githubusercontent.com/15698722/110200332-fe938280-7e22-11eb-832a-984a325d4641.png)
![image](https://user-images.githubusercontent.com/15698722/110200336-02bfa000-7e23-11eb-9aeb-4138e269622a.png)

**Comment by aaronhowser1** [comment]
There's also the second one tho

**Comment by Buuz135** [comment]
It was adressed in a pr
