### ISSUE TITLE
[1.16] Item Dupe Using Infinity Backpack

### ISSUE THREAD

**Issue by NiitroGenius** [InnovativeOnlineIndustries/Industrial-Foregoing#1052]
**Industrial Foregoing Version:*1.16.4-3.2.8.2-6b5c95b*

**Titanium Version:*1.16.5-3.2.8*

If you place an item into the infinity backpack (any slot). Take out the item you placed in there.

If you then middle mouse click it will infinitely give you one that specific item each time you click. The item also retains it's NBT and all data related to it. IE works with a AE2 disk drive full of items. Essentially giving the player easy ways of duping TONS of items at once.

**Comment by Buuz135** [comment]
Update the mod...

**Comment by NiitroGenius** [comment]
This was done using the newest version of IF and Titanium that is available on curseforge?

**Comment by urmet** [comment]
you have latest titanium, but Industrial Foregoing itself is 8 versions behind the latest available on curseforge
