### ISSUE TITLE
mob duplicator wont work

### ISSUE THREAD

**Issue by jackyboy1992** [InnovativeOnlineIndustries/Industrial-Foregoing#1053]
Industrial Foregoing Version: 3.2.10.1
TeslaCoreLib Version: unknown
Crashlog (If Any): no
ok so im playing the new direwolf20 1.16 pack and have made the mob duplicator but for some reason it wont accept power and will not dupe mobs im giving it essence and everything but wont work 

![mob dupe 2](https://user-images.githubusercontent.com/1923334/110698330-6b24cd80-81e5-11eb-82f8-fb50dfd7508b.png)
![mob dupe](https://user-images.githubusercontent.com/1923334/110698346-711aae80-81e5-11eb-838c-ee91ecddec06.png)

**Comment by WBgroup** [comment]
update to 3.2.10.2
