### ISSUE TITLE
Biogenerator makes items dissappear.

### ISSUE THREAD

**Issue by Kolterdyx** [InnovativeOnlineIndustries/Industrial-Foregoing#1054]
Industrial Foregoing Version: 3.2.9.2

I am playing on a modpack (valhelsia 3.1.8a), on a server. I noticed this error by placing a biogenerator next to a (mekanism mod) universal cable, and then breaking it. When I did, the cable still thought the block was there, and was trying to connect to it. I tried updating the cable, even replacing it, and is still thought the biogenerator was there. 

After this, any item that tried to spawn was being removed. Blocks stopped dropping items when broken, and when manually dropping them, they just vanished from the inventory. XP orbs are also instantly deleted.

 As far as I know, restarting the server/game is the only fix for this problem, until the bug is fixed

**Comment by Buuz135** [comment]
Update the mod.
