### ISSUE TITLE
[1.16] Replacing mob orb in duplicator crashed server and crashes server on startup (repeating)

### ISSUE THREAD

**Issue by seals55** [InnovativeOnlineIndustries/Industrial-Foregoing#1055]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

Enigmatica 6 v0.4.3 - I had a cow orb in a mob duplicator going overnight (to get a everlasting beef). I got 15...so I went to put back in my blaze orb. I took out the cow, put in the blaze and the server crashed. The server continuously crashes on startup, I need to revert my backup to get the server back online.

**Industrial Foregoing Version:**
3.2.10.2
**Titanium Version:**
3.2.8
**Crashlog If Applicable (Upload to pastebin/gist):**
https://pastebin.com/JFxxRFgB

**Comment by seals55** [comment]
FYI I reverted my backup, followed the same steps to replace the orb and it worked this time...

**Comment by loboflex** [comment]
Just encountered the same problem when putting a ball with an enderman into the mob duplicator. It worked fine the first time, but after removing the ball and then re-adding it the server crashed and keeps crashing.

https://pastebin.com/453vRzik
