### ISSUE TITLE
[1.16] Backpack crashes server (~3rd evolve)

### ISSUE THREAD

**Issue by oguh43** [InnovativeOnlineIndustries/Industrial-Foregoing#1059]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**
it is on latest
**Industrial Foregoing Version:**
3.2.10.1-decb7ae
**Titanium Version:**
3.2.8
**Crashlog If Applicable (Upload to pastebin/gist):**
https://pastebin.com/FwXk41c1

**Comment by Buuz135** [comment]
Not an IF issue, a power suits issue

**Comment by oguh43** [comment]
> Not an IF issue, a power suits issue

sorry :)
