### ISSUE TITLE
[1.16] No recipe for tiny dry rubber

### ISSUE THREAD

**Issue by Snowcreeper** [InnovativeOnlineIndustries/Industrial-Foregoing#1060]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE** 

forge version --> forge-35.1.37

**Industrial Foregoing Version:** --> industrial-foregoing-1.16.4-3.2.8.2-6b5c95b.jar

**Titanium Version:** --> titanium-1.16.5-3.2.8.jar

**Crashlog If Applicable (Upload to pastebin/gist):** --> No crash

I noticed the recipe for tiny dry rubber was not showing in jei.
Looked into the mods recipe folder and didn't find any recipe file:
![unzipped recipe folder](https://user-images.githubusercontent.com/65914203/111222347-0221c900-85dc-11eb-9492-b4a7f0a460a6.png)

I checked out the other rubber issues and everytime it says fixed.
I'm using the curseforge launcher to pick the "newest" mod versions.
My modlist is pretty bit ~200 mods and like in the other issues I have fastworkbench, but not biomes o' plenty.

While having a look at other recipes i noticed the arboreal extractor from thermal series has no "use" recipe.
Maybe the latex fluid from both mods got messed up by the fastworkbench mod?
Or the Ore unify mod messed it up? (That mod btw doesn't really work since every mod has different forge tags :/ )
ore unify --> oreUnify-1.0.1(1.16.4)(1.16.5).jar

**Comment by Buuz135** [comment]
Use the manual, or update

**Comment by Snowcreeper** [comment]
Update what?

**Comment by Buuz135** [comment]
The mod?

**Comment by Snowcreeper** [comment]
Why does curseforge say it's the newest? I even selected use beta release and nothing new pops up. But on the website it clearly states it has newer versions.
