### ISSUE TITLE
[1.16] Mob Slaughter Factory Pink Slime not working

### ISSUE THREAD

**Issue by CodingJawa** [InnovativeOnlineIndustries/Industrial-Foregoing#1067]
Industrial Foregoing Version: 3.2.10.1
Modpack: Direwolf20 1.16

Pink slime cannot be extracted by Player (by means of bucket), pipe or machine. Push configuration will always ignore pink slime. Both enable and Push do nothing.
Pipes I tried it with: Mekanism and refined pipes
![grafik](https://user-images.githubusercontent.com/66843176/112755623-b9a5da80-8fe1-11eb-81b5-030b8cb20919.png)
![grafik](https://user-images.githubusercontent.com/66843176/112755633-cc201400-8fe1-11eb-9159-c94deb0e8082.png)
![grafik](https://user-images.githubusercontent.com/66843176/112755661-f1148700-8fe1-11eb-8aa0-ada62b0ae1b0.png)

**Comment by Buuz135** [comment]
Thats not the back of the machine that the front. Use the directions shown in the tooltip to help you out. Please use discord for support.
