### ISSUE TITLE
[1.16] Computercraft:Tweaked's generic peripheral API can't interact with every machine.

### ISSUE THREAD

**Issue by Lupus590** [InnovativeOnlineIndustries/Industrial-Foregoing#1073]
**Industrial Foregoing Version:** 1.16.5-3.2.10.2-d316328

**Titanium Version:**  1.16.5-3.2.7

Some Industrial Foregoing machines don't have all of the correct generic peripheral APIs on them. These APIs allow ComputerCraft to move items and fluids around like many pipe mods. I believe that it finds appropriate blocks for generic peripherals by using the forge capability system and so it could be that Industrial Foregoing is not exposing its capabilities correctly.

**Blocks tested that have issues:**
* Mob Crusher
* Mob Duplicator
* Mob Slaughter Factory
* Enchantment Extractor

**Comment by Lupus590** [comment]
Added Mob Slaughter Factory to the list

**Comment by djmattyg007** [comment]
You can add the Enchantment Extractor to this list. It exposes the fluid APIs, but not the inventory APIs.
