### ISSUE TITLE
[1.16] Crash with Rocket Generator 

### ISSUE THREAD

**Issue by avidgamer5918** [InnovativeOnlineIndustries/Industrial-Foregoing#1074]
**Reference:** AllTheMods/ATM-6#1332

**Industrial Foregoing Version:** industrial-foregoing-1.16.5-3.2.11-55cb112

**Titanium Version:** titanium-1.16.5-3.2.8.2

**Crashlog:** https://pastebin.com/BY98BCfk

**Comment by Seceroth** [comment]
Same issue here. Inserted a Firework rocket [Large ball + White + Twinkle + Trail] with Flight duration 1. The server crashed right away. Playing the [Enigmatica 6](https://www.curseforge.com/minecraft/modpacks/enigmatica6) modpack, version 0.4.8.

Adding my crash report in case it helps:
[crash-2021-04-12_07.26.30-server.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/6294175/crash-2021-04-12_07.26.30-server.txt)
