### ISSUE TITLE
[1.16] Ticking entity crash (enchantment applicator)

### ISSUE THREAD

**Issue by DragarX** [InnovativeOnlineIndustries/Industrial-Foregoing#1079]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**
I tried to pull essence from a creative mekanism tank and got a crash loop. I may have accidentally used mob grinding utils liquid xp but the applicator shouldn't accept it right?

**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.11-55cb112.jar
**Titanium Version:**
titanium-1.16.5-3.2.8.jar
**Crashlog If Applicable (Upload to pastebin/gist):**
[crash-2021-04-09_02.26.27-server.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/6283678/crash-2021-04-09_02.26.27-server.txt)

**Comment by Buuz135** [comment]
Update titanium
