### ISSUE TITLE
[1.16] Industrial Foregoing

### ISSUE THREAD

**Issue by joaoespanhol** [InnovativeOnlineIndustries/Industrial-Foregoing#1081]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**1.16.5-3.2.11-55cb112.jar

**Titanium Version:**titanium-1-16-5-3-2-8-2

**Crashlog If Applicable (Upload to pastebin/gist):**https://mclo.gs/AK71Ss3

**Comment by Buuz135** [comment]
You are using Paper, I make mods for Forge, I don't know what Paper is changing and I can't fix it.

**Comment by joaoespanhol** [comment]
i no use paper, paper is no forge.
I am use: Arclight

**Comment by Buuz135** [comment]
Same thing

**Comment by Evolution0** [comment]
I use Industrial Foregoing with Arclight in my own personal 1.16.5 modpack, I haven't got any issues so far but I would not be surprised if Arclight is the issue, it seems to have problems with blocks/items that... change? (Throwing the sword in the lake in Mahou Tsukai, Using Casting Tables/Basins in latest TConstruct, etc)

Usually once you see `Skipping BlockEntity with id` in your logs you just placed/used/found a block that is going to cause issues or not work.

Id bet anything that if you drop into SP and try what is causing a crash nothing will happen, I've done quite a bit of testing with Arclight on these issues.
