### ISSUE TITLE
[1.16] Block Placer causing server to crash

### ISSUE THREAD

**Issue by kaiffeetasse** [InnovativeOnlineIndustries/Industrial-Foregoing#1082]
**Industrial Foregoing Version:** 1.16.5-3.2.10-09eb824

**Titanium Version:** 1.16.5-3.2.7

**Crashlog If Applicable (Upload to pastebin/gist):** https://pastebin.com/gPM2gPAv

The server crashes when the Block Placer is placing a block. After a restart the block is placed.

**Comment by Buuz135** [comment]
Effortless Building issue

**Comment by Requios** [comment]
Effortless Building mod creator here. This issue has been fixed in version 2.23 of Effortless Building.
