### ISSUE TITLE
[1.16] Industrial Foregoing has failed to load correctly, Not enough data available

### ISSUE THREAD

**Issue by pc03hachibee** [InnovativeOnlineIndustries/Industrial-Foregoing#1085]
[crash log.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/6315429/crash.log.txt)
ailure message: Industrial Foregoing (industrialforegoing) has failed to load correctly
		
com.electronwill.nightconfig.core.io.ParsingException: Not enough data available

*mods*
industrial-foregoing-1.16.4-3.2.8.2-6b5c95b
titanium-1.16.5-3.2.7

**Comment by Buuz135** [comment]
Delete IF config files, including the ones in the server folder.

**Comment by pc03hachibee** [comment]
where is that? i play single player?

**Comment by castilio20** [comment]
he means single player world and then go to serverside
