### ISSUE TITLE
[1.16] Wither Builder not spawning wither in FTB Claimed Chunk

### ISSUE THREAD

**Issue by alexsoww** [InnovativeOnlineIndustries/Industrial-Foregoing#1088]
The Wither Builder isn't placing the wither skulls and spawning the wither (the skulls remain stuck in the builder) in a FTB Claimed Chunk, but it works fine in an unclaimed chunk. Also it has a visual bug where the rf bar in the ui is stuck at 4464 rf, but in the panel on the top of the screen (not hwyla, but I can't remember the name) it is full and correct.
Should I make a bug report on FTB Chunks' part?
**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.11-55cb112
**Titanium Version:**
titanium-1.16.5-3.2.8.2

![2021-04-23_10 35 27](https://user-images.githubusercontent.com/83061960/115840530-76922800-a424-11eb-868a-5d61d19ce215.png)
![2021-04-23_10 35 31](https://user-images.githubusercontent.com/83061960/115840549-7abe4580-a424-11eb-9190-0a2736afe284.png)

**Comment by 19175** [comment]
Ally [IF] in your allys list, this will allow other players to use IF machines to 'grief' your claims though. (block placer, block breaker ect)

**Comment by Buuz135** [comment]
That is correct, sorry for the delay.
