### ISSUE TITLE
[1.16] Mob Crusher does Virtually Infinite Damage to any mob/entity except player

### ISSUE THREAD

**Issue by CygnusThe1st** [InnovativeOnlineIndustries/Industrial-Foregoing#1091]
**industrial-foregoing-1.16.5-3.2.11-55cb112**

**titanium-1.16.5-3.2.8.2**

the mob crusher kills everything instantaneously including the Guardian of Gaia after its death it also drops a Dice of Fate that doesn't belong to anyone

**Crashlog If Applicable (Upload to pastebin/gist):can't**

**Comment by Buuz135** [comment]
Thats how it works, not an issue

**Comment by CygnusThe1st** [comment]
@Buuz135 then should i make this a feature request that the Mob Crusher should work like it did in 1.12.2 where it never was able to kill the Guardian of Gaia?

**Comment by TheEpicProgrammer** [comment]
Just add a damage limit to the thing

**Comment by CygnusThe1st** [comment]
@TheEpicProgrammer no i'd like the Mob Crusher to be identified as a player to botania so that the Dice of Fate is Actually usable and not an indestructible useless item OR just add it to the Blacklist of things the Mob Grinder Can't kill
