### ISSUE TITLE
[1.16] Black Hole Unit Destroyed My Soul

### ISSUE THREAD

**Issue by Darkosto** [InnovativeOnlineIndustries/Industrial-Foregoing#1093]
Hello,

The Supreme Black Unit rolls over to -2.14 billion when full and the Void when full option is enabled.

**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.11-55cb112
**Titanium Version:**
titanium-1.16.5-3.2.8.2

**Crashlog If Applicable (Upload to pastebin/gist):**
![image](https://user-images.githubusercontent.com/10309699/116948514-618f7300-ac34-11eb-8ddb-f45b703cdec2.png)

https://clips.twitch.tv/HandsomeLachrymoseLionOhMyDog-PvzYMoXjdkrzbLqq
https://clips.twitch.tv/IntelligentHumbleEggnogStrawBeary-tkCYaZHvYfWQV2BW

**Comment by Darkosto** [comment]
On a more serious note, this issue seems to be related to the Void when full option/button in the GUI. If voiding items is disabled, the Supreme Black Hole Unit will not roll over to -2.14billion. It seems the simplest solution is to remove the Void button and set the black hole unit to not void by default.


For any players who happen to see this issue, when placing a Supreme Black Hole Unit disable the Void when full option in the GUI.

**Comment by scollenburg** [comment]
Pretty sure the error is here. `inserted` is not bounds checked after the assignment.

https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blame/073b88205eb7b41a8dac23dab94312f3bf9f080e/src/main/java/com/buuz135/industrial/capability/BLHBlockItemHandlerItemStack.java#L61
