### ISSUE TITLE
[1.12] Black hole tank gauge doesnt change when you fill it up

### ISSUE THREAD

**Issue by Ay-CC** [InnovativeOnlineIndustries/Industrial-Foregoing#1094]
**Industrial Foregoing Version:**
industrialforegoing-1.12.2-1.12.13-237.jar

**TeslaCoreLib Version:**
tesla-core-lib-1.12.2-1.0.17.jar

![Screenshot 2021-05-04 163745](https://user-images.githubusercontent.com/76176725/117020817-12f6dd00-acf7-11eb-82bf-91490233993e.png)

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
