### ISSUE TITLE
[1.16] Machines Does not working

### ISSUE THREAD

**Issue by Rawgreen** [InnovativeOnlineIndustries/Industrial-Foregoing#1101]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version: 3.2.11

**Titanium Version:3.2.8.2

**Crashlog If Applicable (Upload to pastebin/gist):**

Dissolution Chamber, Mob duplicator and Slimey Mycelial Generator machines eveni did give them power and everything but these machines does not working
![bug_1](https://user-images.githubusercontent.com/59456551/118060223-e861ef80-b39a-11eb-8b34-78f9c9abaa92.png)
![bug_2](https://user-images.githubusercontent.com/59456551/118060227-ebf57680-b39a-11eb-8918-d4bffb9e922a.png)
![bug_3](https://user-images.githubusercontent.com/59456551/118060232-ee57d080-b39a-11eb-8d9e-cfb88c57aeb1.png)
![bug_3_2](https://user-images.githubusercontent.com/59456551/118060236-ef88fd80-b39a-11eb-93ba-9675a61176f3.png)

-As you can see i did everything correctly but these machines doesn't working 

-When i change redstone signal machine seems have energy but its still does not working and when i exit from ui and look again it seems empty again.

Mod Pack: FTB Presents Direwolf20 1.16

**Comment by Buuz135** [comment]
You arent using machines properly.

1) Slimey Generator needs slime to make power
2) Your Dissolution Chamber fluid is wrong
3) The Mob duplicator needs essence to run (The energy is just visual)

Please use discord for support, or just read the manual.
