### ISSUE TITLE
[1.12] [Stoneblocks 2] Plant Sower still not placing seeds on fertilized ground

### ISSUE THREAD

**Issue by dasmou** [InnovativeOnlineIndustries/Industrial-Foregoing#1105]
Hiho, 

you closed the previous ticket and said that industrial foregoing has ended support, but this ticket is not about that modpack but about the Stoneblocks 2 Modpack. So I am reopening it because it was closed accidentely i guess. 

I noticed that the plant sower does not plant any seeds on fertilized_ground provided by the "hatchery" mod which is included in the stoneblocks 2 modpack.

I already found the reason for it. 
In line 139 from the CropSowerTile.java file it checks if the block is dirt, but not if the block maybe is fertilized farmland. 

So can i somehow add it in order to get it to work?

here a screenshot showing the item's name:
![2020-07-23_11 24 10](https://user-images.githubusercontent.com/68687343/88271219-22acb400-ccd7-11ea-8321-d6762cf4b7ca.png)

thanks for helping out!

br,
m0u

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.

**Comment by dasmou** [comment]
still not fixed, is there any eta?

**Comment by WBgroup** [comment]
There is no ETA since version for 1.12 (or basically anything other than 1.16+) is **not** supported. There will be no fixes or updates for older versions.

**Comment by dasmou** [comment]
bump

**Comment by dasmou** [comment]
bump again :P

**Comment by Mox0001** [comment]
You can get the 1.12 files from this link  [https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/tree/1.12](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/tree/1.12)

**Comment by dasmou** [comment]
Hey is there any update in this case? still got the bug.
