### ISSUE TITLE
[1.16] Resourceful Furnace Voids buckets when making Sushi Go Crafting Cheese

### ISSUE THREAD

**Issue by natebc** [InnovativeOnlineIndustries/Industrial-Foregoing#1106]
Industrial Foregoing Version:
industrial-foregoing-1.16.5-3.2.11-55cb112.jar

Titanium Version:
titanium-1.16.5-3.2.8.2.jar
![5479206c-f59d-41d8-92b2-efe0a927cff3](https://user-images.githubusercontent.com/53818/119229162-94ff4800-bae4-11eb-83e2-c9df2e70a760.gif)

**Comment by frakier** [comment]
the furnace mycelial generator is doing the same thing at some point the bucket just disappears.
