### ISSUE TITLE
[1.16] Picking up Ore Meat Fluid voids nbt

### ISSUE THREAD

**Issue by Darkere** [InnovativeOnlineIndustries/Industrial-Foregoing#1113]
Picking up the fluid in a bucket voids the nbt of that fluid.. 

industrial-foregoing-1.16.5-3.2.11-55cb112.jar

**Comment by Buuz135** [comment]
Fixed in https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/commit/a2f6f88182a97d3b8794e9e8ee87cab66e355344
