### ISSUE TITLE
[1.16] Cannot place Fluid Transporter's on Thermal's Fluid Cell

### ISSUE THREAD

**Issue by aaronhowser1** [InnovativeOnlineIndustries/Industrial-Foregoing#1120]
**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.13-4
**Titanium Version:**
titanium-1.16.5-3.2.8.3-9

![image](https://user-images.githubusercontent.com/15698722/121319470-db6ce900-c8d1-11eb-8266-4746959f14dc.png)
Shift-clicking does nothing

**Comment by aaronhowser1** [comment]
If this is on Thermal's side, lmk and I'll move the issue there.

**Comment by Random832** [comment]
Does it work if you put the cell's face configuration in input mode (and still try to pull from it)?

Fluid Cells are known to behave a bit strangely right now with some kinds of pipes due to how the output mode works.

**Comment by aaronhowser1** [comment]
It's super inconsistent. I could place it on all of them, then I broke and replaced it, and now I can't place it on any.

And now I did that *again*, and it can ONLY be placed on this face, even though all are the same
![image](https://user-images.githubusercontent.com/15698722/121502481-d4170f80-c9a5-11eb-86e0-7d265d5a63e1.png)
