### ISSUE TITLE
[1.12] Range Addon Vanishing from Mob Crusher

### ISSUE THREAD

**Issue by Gusleton** [InnovativeOnlineIndustries/Industrial-Foregoing#1126]
**Industrial Foregoing Version: 1.12.2.13-237**

**TeslaCoreLib Version: 1.12.2-1.0.17**

**Crashlog If Applicable (Upload to pastebin/gist):**

In ocean outlast modpack, after some unknown time or condition, my range addons in my mob crusher vanish. I did hook up to the output a drawer to catch that range addon if for some the addon was getting pulled out but that was not the case, the number didn't change.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
