### ISSUE TITLE
[1.16] Animal feeder not working

### ISSUE THREAD

**Issue by SomeDudeOnTheInternet** [InnovativeOnlineIndustries/Industrial-Foregoing#1128]
Industrial Foregoing Version: 1.16.5-3.2.13.1-5
TeslaCoreLib Version: X
Crashlog (If Any): X
Initially worked, now it doesn't work at all unless all range modifiers are removed, limiting the functionality.
All other parts of this mod work correctly, so it seems to be an issue with the block.

pictures:
https://drive.google.com/drive/folders/1p-Gy1MgjwRwlc93eQtg2mag2jdoQF9Zp?usp=sharing
![Cow farm](https://user-images.githubusercontent.com/50602125/123331907-7d611800-d505-11eb-8c74-3e0e5b8d71eb.png)
(the baby cows were there from manual feeding)
![has everything](https://user-images.githubusercontent.com/50602125/123331918-7fc37200-d505-11eb-903e-6455910b5e0b.png)
(has power, wheat, range, and speed upgrade)
![Rest of mod works](https://user-images.githubusercontent.com/50602125/123331924-818d3580-d505-11eb-8fcc-35bd230bc22d.png)

**Comment by Buuz135** [comment]
The feeder stops when there are too many animals in the area, kill some mobs and it will start feeding again.
