### ISSUE TITLE
[1.16] Hydroponic beds in compact machine causing crops to spawn in overworld

### ISSUE THREAD

**Issue by DrivenTundra16** [InnovativeOnlineIndustries/Industrial-Foregoing#1133]
I have a few hydroponic beds in a compact machine, and I noticed that shortly after placing them the entity count was going up by thousands in a few seconds. I found where it was coming from and there were crops spawning in the exact same coordinates of the ones in the compact machine. (the beds were at -1000, 40, 0, and the crops were appearing in the exact same coordinates in the overworld). I can't really solve this other than just breaking the beds.

https://user-images.githubusercontent.com/86855655/124328019-d6106080-db56-11eb-8b02-51726246ef2f.mp4

**Comment by Buuz135** [comment]
Can you check if it happens with minecraft seeds or just with Mystical Agriculture?
