### ISSUE TITLE
Missing block

### ISSUE THREAD

**Issue by zoldmaki** [InnovativeOnlineIndustries/Industrial-Foregoing#1138]
Industrial Foregoing Version: industrial-foregoing-1.16.5-3.2.14.1-7
TeslaCoreLib Version: not present
When I updated the mod a milk something got removed and my friend can't join because 
this removed block was in the game when the world was generated. The block or fluid has not been placed. Any idea?
[debug.log](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/6807002/debug.log)

**Comment by Buuz135** [comment]
Use discord for  support

**Comment by zoldmaki** [comment]
> Use discord for support

ok
