### ISSUE TITLE
[1.12] Range upgrades don't work past +6

### ISSUE THREAD

**Issue by Majschina** [InnovativeOnlineIndustries/Industrial-Foregoing#1139]
**Industrial Foregoing Version:1.10**

**TeslaCoreLib Version:1.0.17**

Basically all the upgrades past +6 only increase the radius by 6, instead of for example 12 for +12. I am playing FTB Sky Odyssey 1.3.0. I have only seen this on the mob crusher and mob duplicator, as I haven't tested other machines.

**Comment by Buuz135** [comment]
Some machines have a max range, check the machine tooltip.

**Comment by Majschina** [comment]
I'm sorry, my bad, never managed to notice that.
