### ISSUE TITLE
[1.16] Issue Title

### ISSUE THREAD

**Issue by j4rw15** [InnovativeOnlineIndustries/Industrial-Foregoing#1140]
Wither builder does not work in the last 3 versions of this mod, Industrial Foregoing.

**Comment by KungRaseri** [comment]
Experiencing the same thing here.  Using the Final Frontier 2 modpack (pack version 7.9).

Everything seems like it should work.

![image](https://user-images.githubusercontent.com/1054240/126422111-f6f5759b-6a04-48f0-8363-8ccc8a323780.png)

Provided the machine with skulls and sand from the refined storage mod. 

![image](https://user-images.githubusercontent.com/1054240/126422217-f6726b43-f855-4ca7-b257-7dd028f6a1b5.png)

I am able to spawn withers via building the structure manually.
