### ISSUE TITLE
[1.16] The machines do not work in the presence of the chunk loader but not the player

### ISSUE THREAD

**Issue by signormorte** [InnovativeOnlineIndustries/Industrial-Foregoing#1141]
Industrial Foregoing: 1.16.5-3.2.14.1-7
Titanium: 1.16.5-3.2.8.4-10
Forge: 1.16.5 36.1.32
ChickenChunks: 1.16.5-2.8.0.86-universal

I play on a server with my friends, and every time we all leave the server the machines stop working, we put a chunk loader to prevent them from stopping but it didn't help.

**Comment by Buuz135** [comment]
Which machines?

**Comment by signormorte** [comment]
I have seen him with the plant gaether, the sower and the animal feeder, but I think he does it with everyone

**Comment by Buuz135** [comment]
Is it possible that things in world don't change? it might not be a machine problem but a chunkloader problem

**Comment by signormorte** [comment]
In fact I tried with another mod and they started working again even when I left the server, it's probably a problem with the chickenchunks
