### ISSUE TITLE
[1.16] Cost of Combining Enchants eventually rolls over to nothing

### ISSUE THREAD

**Issue by MuteTiefling** [InnovativeOnlineIndustries/Industrial-Foregoing#1143]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.14.2-8
**Titanium Version:**
titanium-1.16.5-3.2.8.4-10
**Crashlog If Applicable (Upload to pastebin/gist):**
No crash

Steps to reproduce:
1) Place Supreme Black Hole Tank full of Essence on top of an Enchantment Applicator
2) Fill it with Essence
3) Add Fortune III or whatever to a tool
4) Creative copy the tool into both input slots to get Fortune IV
5) Repeat, refilling essence as necessary
6) Eventually the tools will start to take nearly a full tank of essence to combine
7) Keep combining
8) Soon the tool will reach a threshold where the cost calculation rolls back over to 0 and more combinations can be done for quite some time before the cost starts to become appreciable again. 

I was able to level a tool up to Fortune C this way in short order in Creative. Yes, this would take a long time to attain in survival, where the only methods for copying an enchant tends to be expensive, but it could be achieved by levelling multiple enchants in tandem starting from low levels. 

Still, it should fail to combine further once it reaches a point where the cost has outgrown the max essence buffer.

**Comment by MuteTiefling** [comment]
Since you were having trouble reproducing this, here's a video from start to finish: https://streamable.com/glrwbw

Only thing I don't show in the video is that the applicator is set to pull from the top: 

![image](https://user-images.githubusercontent.com/9543430/127251712-1949e67b-7e54-4967-be31-612a7a2cb905.png)

No clue if this has any impact.

**Comment by James103** [comment]
> Since you were having trouble reproducing this, here's a video from start to finish: https://streamable.com/glrwbw

Can you please try reproducing this again while recording? If you can successfully reproduce this, upload the video as an attachment or post it on YouTube so that it will stay indefinitely. The original video seems to have been automatically deleted.
