### ISSUE TITLE
[1.16] Enchantment Applicator (and maybe more) immediate game crash interaction with /tank/null docks

### ISSUE THREAD

**Issue by jebjordan** [InnovativeOnlineIndustries/Industrial-Foregoing#1145]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version: industrial-foregoing-1.16.5-3.2.14.1-7**

**Titanium Version: titanium-1.16.5-3.2.8.4-10**

**Crashlog If Applicable (Upload to pastebin/gist): https://gist.github.com/jebjordan/bd1b2f891d57c72f102f75bcdd313bb9**

I am using GDLauncher, but that doesn't really affect anything.
Mods installed:
Industrial Foregoing, Titanium, /tank/null, patchouli.

Steps to reproduce:
1. Place down an applicator
2. Put a black hole tank above it, fill with essence.
3. Fill the applicator and turn on pulling from top.
4. Enchant an item, thus using the black hole tank.
5. Remove the tank, and place down a Dock on top of the Applicator.
6. Game has now crashed.

Nearly 99% sure this is an issue with industrial foregoing.

**Comment by Buuz135** [comment]
Pastebin is private

**Comment by jebjordan** [comment]
weird I made it public.

Must've been flagged or something.. uhhh, here, a gist.

Seems pastebin dislikes that paste of mine for some reason.
https://gist.github.com/jebjordan/bd1b2f891d57c72f102f75bcdd313bb9

**Comment by jebjordan** [comment]
I'd like to also point out that this crashes both singleplayer and serverside.

Right now I'm unable to join my server because I found out this bug on accident.
The second the chunk it's in loads the server crashes.

**Comment by jebjordan** [comment]
@Buuz135 Just wanted to let you know I added a gist instead of a pastebin.

**Comment by jebjordan** [comment]
@Buuz135 The update did *not* fix the issue.
it still instantly crashes after updating. Steps are the exact same.
Crash log: https://gist.github.com/jebjordan/4fc373d6cef69b1a8b9b8b26c7a6c455

:(

Hopefully this can be fixed quickly

**Comment by jebjordan** [comment]
@Buuz135 please if you could re-open this issue

**Comment by Reinitialized** [comment]
Can we get the latest bugfix commit officially published? It has indeed fixed the issue, but I doubt the ATM6 team would be willing to accept a custom built jar over the official one.
