### ISSUE TITLE
[1.16] Issue Title

### ISSUE THREAD

**Issue by L0rdLogan** [InnovativeOnlineIndustries/Industrial-Foregoing#1146]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

industrial-foregoing-1.16.5-3.2.13.1-5

titanium-1.16.5-3.2.8.4-10

xNet and Mob slaughter factory not pulling both Pink Slime and Liquid Meat at the same time, disabiling Liquid Meat allows Pink slime to pull

**Comment by Buuz135** [comment]
Not an IF issue
