### ISSUE TITLE
[1.16] IllegalArgumentException with Slaughter Factory

### ISSUE THREAD

**Issue by oitsjustjose** [InnovativeOnlineIndustries/Industrial-Foregoing#1159]
**Industrial Foregoing Version:** 3.2.14.3-9

**Titanium Version:**: 3.2.8.4-10

**Crashlog If Applicable (Upload to pastebin/gist):**[Crashlog](https://gist.github.com/oitsjustjose/01b72229950bf7213c9189a4103991c6)
## Symptom

Players can't log into Forge server within range to load  the Slaughter Factory, thus causing the crash.

## Potential Culprit

https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/a528cbbb39eaff6b81978bd54255941bb9317336/src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/SlaughterFactoryTile.java#L98-L105

**Comment by Buuz135** [comment]
Something has corrupted/removed that block without removing the tile properly, I don't know what `minecraft:void_air` but thats not minecraft air
