### ISSUE TITLE
[1.16] Missing gear recipes 

### ISSUE THREAD

**Issue by fred21O4** [InnovativeOnlineIndustries/Industrial-Foregoing#1162]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:** industrial-foregoing-1.16.5-3.2.14.4-11.jar

**Titanium Version:** titanium-1.16.5-3.2.8.5-19.jar

**Crashlog If Applicable (Upload to pastebin/gist):** N/A

Recipes for Iron Gold and Diamond gears are missing

**Comment by Buuz135** [comment]
Missing manual too
