### ISSUE TITLE
[1.16] Range Addon doesn't work on Plant Gatherer 

### ISSUE THREAD

**Issue by Duorhs** [InnovativeOnlineIndustries/Industrial-Foregoing#1163]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**

industrial-foregoing-1.16.5-3.2.14.4-11.jar

**Titanium Version:**

titanium-1.16.5-3.2.8.5-19.jar

**Crashlog If Applicable (Upload to pastebin/gist):**

**Issue:**
The Plant Gatherer only work when the tree is in front of (next to) the machine with 1-block range , even the range indicator
 shows more than that . However if other trees are connected to the first tree then they will be gathered together.

**Comment by Buuz135** [comment]
Works fine, can't replicate
