### ISSUE TITLE
[1.16] Laser Drill disconnects client when too many within chunk

### ISSUE THREAD

**Issue by turulix** [InnovativeOnlineIndustries/Industrial-Foregoing#1164]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**
I build a giant Ore Laser using a total of ~123 lasers drills, all upgraded with all 3 mods. When the chunk gets unloaded & loaded again on a server the client get disconnected with the exception below. This is the design I used [Design](https://i.turulix.de/3ztuGe.png) with 5 tesseracts around the Ore Laser itself to power the inner ones.

**Industrial Foregoing Version:**
3.2.14.4-11

**Titanium Version:**
3.2.8.4-10

**Crashlog If Applicable (Upload to pastebin/gist):**
[Image of Exception](https://i.turulix.de/nvyd4A.png)

**Comment by Buuz135** [comment]
I need a log, that doesn't help at all

**Comment by turulix** [comment]
Sorry, here you go https://i.turulix.de/XHCPyV.rar I can't upload it to pastebin / hastebin as the log is way to big

**Comment by Buuz135** [comment]
All of your powah cables are overloading the chunk nbt. Not an IF issue.
