### ISSUE TITLE
[1.16] Error with JEI Plugin

### ISSUE THREAD

**Issue by Sunekaer** [InnovativeOnlineIndustries/Industrial-Foregoing#1171]
**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.14.5-13.jar

**Titanium Version:**
titanium-1.16.5-3.2.8.4-10.jar

Other mods:
Just Enough Items (JEI)
jei-1.16.5-7.7.1.121.jar

Patchouli
Patchouli-1.16.4-53.1.jar

**Crashlog If Applicable (Upload to Pastebin/gist):**
https://paste.sunekaer.com/rasitizoce.sql

**Comment by trogarus** [comment]
Guessing that this is the same issue as I have, but not sure, so will post here. Seems like an empty fluid stack issue in JEI when trying to look at the dissolution chamber recipe tab.

[crash-2021-08-29_08.18.45-client.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/7072466/crash-2021-08-29_08.18.45-client.txt)

[latest.log](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/7072468/latest.log)

**Comment by trogarus** [comment]
Updated to jei-1.16.5-7.7.1.121

Seems to have fixed the crash issue, but now there are now recipes showing for the dissolution chamber at all.

**Comment by tytan652** [comment]
Integrated dynamics had the same [issue](https://github.com/CyclopsMC/IntegratedDynamics/issues/1082) recipe of some machine will not be shown.
Needs to be fixed on Industrial Foregoing side.

https://github.com/mezz/JustEnoughItems/issues/2468#issuecomment-910248086

**Comment by Buuz135** [comment]
Fixed in https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/commit/925fa7be306a3229957b556cf80df1d0faa8546a

**Comment by trogarus** [comment]
And after latest Industrial Foregoing update, recipes seem to be back in JEI and work.
