### ISSUE TITLE
[1.16] No recipe shown with latest version of JEI

### ISSUE THREAD

**Issue by tytan652** [InnovativeOnlineIndustries/Industrial-Foregoing#1173]
Since the new version of JEI is out, there are no recipes showing for the dissolution chamber at all.

Integrated dynamics had the same [issue](https://github.com/CyclopsMC/IntegratedDynamics/issues/1082), recipe of some machine was not be shown.

Needs to be fixed on Industrial Foregoing side.
https://github.com/mezz/JustEnoughItems/issues/2468#issuecomment-910248086

Issue related to Industrial Foregoing on JEI repo: https://github.com/mezz/JustEnoughItems/issues/2471

**Industrial Foregoing Version:**
3.2.14.5-13

**Titanium Version:**
3.2.8.4-10

**JEI Version:**
7.7.1.121

**Crashlog If Applicable (Upload to pastebin/gist):**

**Comment by Buuz135** [comment]
Duplicate #1171
