### ISSUE TITLE
[1.16] Sorting machine's inventory while in Industrial-Foregoing's machines deletes all of the internal buffer items and range-addon. 

### ISSUE THREAD

**Issue by jackwang0602** [InnovativeOnlineIndustries/Industrial-Foregoing#1175]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

Problem:
Sorting machine's inventory while in Industrial-Foregoing's machines deletes all of the internal buffer items and range-addon. 

How I discovered this problem:
I'm playing FTB Presents Direwolf20 1.16 pack 1.11.0 version. My habit is randomly sort my inventory, and one time I was accidentally sorting the inventory in the machine which is the internal item buffer, I sort it with middle click and all the items in the buffer and the range-addon just got deleted.

How this problem happens:
1. Open machine's GUI like Mob Crusher which has an internal item buffer and has range-addon slot
2. Hovering mouse on the internal item buffer
3. Middle click which activate the inventory sorting mod
4. All the internal item gone and also the range-addon gone, they just disappear

**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.14.5-13

**Titanium Version:**
titanium-1.16.5-3.2.8.4-10

**Crashlog If Applicable (Upload to pastebin/gist):**
No CrashReport. The game itself didn't crash.

Not English native speaker so maybe it's not easy to read it sorry btw, also thanks for create this mod and keep updating!

Good luck!

**Comment by Buuz135** [comment]
Its the sorting mod issue.
