### ISSUE TITLE
[1.16] Infinity Drill seems to be a bit wonky....

### ISSUE THREAD

**Issue by CKY-** [InnovativeOnlineIndustries/Industrial-Foregoing#1176]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**
**Forge Version:**
Forge - 36.2.0

**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.14.6-14

**Titanium Version:**
titanium-1.16.5-3.2.8.5-20
**Crashlog If Applicable (Upload to pastebin/gist):**
with charging enabled the Infinity Drill is having a hard time harvesting even the simplest of blocks 
[https://streamable.com/rb2fvx](https://streamable.com/rb2fvx)
it's odd that sometimes it will and sometimes it will not break blocks

**Comment by Buuz135** [comment]
Nothing much can be done, thats how minecraft works. Disable the charging to disable the item updates
