### ISSUE TITLE
[1.16] Dissolution chamber recipes aren't showing up in JEI

### ISSUE THREAD

**Issue by Gurakai** [InnovativeOnlineIndustries/Industrial-Foregoing#1177]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version: 1.16.5-3.2.14.5-13 **

**Titanium Version: 1.16.5-3.2.8.4-10 **

**Crashlog If Applicable (Upload to pastebin/gist): N/A**

![2021-09-04_08 47 13](https://user-images.githubusercontent.com/10900107/132096781-c30664ca-05f8-4f90-8bea-0d19bc4b100a.png)

**Comment by WBgroup** [comment]
Downgrade JEI to .118 at least

**Comment by Buuz135** [comment]
Or update IF

**Comment by Gurakai** [comment]
Downgrading JEI to .118 has it fixed, very much appreciated.

I also didn't realize that a more updated version was available at first since it didn't have an update on the curseforge client.
