### ISSUE TITLE
[1.16] Fermented ancient debris ore meat does not produce anything when used in fluid sieving machine. 

### ISSUE THREAD

**Issue by CLASIX** [InnovativeOnlineIndustries/Industrial-Foregoing#1182]
Title says it all. JEI says its supposed to turn into netherite dust from mekanism. I dont know if that is a custom recipe by the author of enigmatica 6 or not. It does turn into raw ore meat and fermented ore meat fine. 

Industrial version 1.16.5-3.2.14.6 (updated on my own, pack author has not published pack update)

Titanium version 1.16.5-3.2.8.5-20 (updated on my own, pack author has not published pack update)

Thanks for all your hard work. Industrial Foregoing is an amazing mod! 

EDIT: after a little research, I came to the conclusion that this is actually problem for the pack author. Sorry for the spam! Ill keep it open though, just in case I am mistaken.

**Comment by VorpalLemur** [comment]
I came here today looking for an answer to exactly this as I've run into it as well.   Thanks for keeping it around and making it easy to find, even should it turn out to be a pack author issue as OP suggests.

**Comment by Buuz135** [comment]
Fixed on enigmatica 6 side
