### ISSUE TITLE
[1.16] Enchantment Applicator enchant level 

### ISSUE THREAD

**Issue by ohbi** [InnovativeOnlineIndustries/Industrial-Foregoing#1187]
When applying an enchant from a book and the book is over level III it applies a level III version of the enchant.  I've tried applying a second III enchant to see if it would level up but it also applied a level III enchant.   

Applying these enchants with an anvil will apply the books normally.

This happened in my Enigmatica 6 (0.5.11, world crashes if i try start it to check the IF version) world maybe 3 weeks ago  but that world is a little glitchy so thought it was that but its also happening in my Ragnamod VI world now too.

IF Version: 3.2.14.6 (Ragnamod VI 6.0.22)
Titanium: 3.2.8.4

**Comment by Buuz135** [comment]
That is a config that E6 enabled
