### ISSUE TITLE
Animal Rancher not working with range upgrades

### ISSUE THREAD

**Issue by albyalex96** [InnovativeOnlineIndustries/Industrial-Foregoing#1193]
Industrial Foregoing Version: 1.16.5-3.2.14.6-14.
TeslaCoreLib Version: NONE
Patchouli : 1.16.4-53.2
Titanium : 1.16.5-3.2.8.5-20
Crashlog (If Any): None
As mentioned, the animal rancher does not work when upgrades are installed ( i've used +3 range upgrade ). it does use power but it does not provide any resources. when used without upgrades, it milks cows and shear sheeps.

**Comment by Buuz135** [comment]
Cant replicate
