### ISSUE TITLE
[1.16] Dragon's death isn't properly triggered by the Mob Crusher

### ISSUE THREAD

**Issue by MuteTiefling** [InnovativeOnlineIndustries/Industrial-Foregoing#1196]
Simply put, if the dragon is killed by the mob crusher, the end portal doesn't form and a new dragon respawns shortly after. 

**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.14.6-14.jar

**Titanium Version:**
titanium-1.16.5-3.2.8.5-20.jar

**Crashlog If Applicable (Upload to pastebin/gist):*
[latest.log](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/7447800/latest.log)

Enjoy my terrible marksmanship :D
https://streamable.com/kr7xwi

Initial report. Replicated with only IF and JEI
https://github.com/NillerMedDild/Enigmatica6/issues/3307

**Comment by Quezler** [comment]
tbh a mob blacklist on that block would be neat, e.g. for the gaia guardian too, there doesn't seem to be a way atm 🤔
