### ISSUE TITLE
[1.16] Black Hole Unit ignores filter

### ISSUE THREAD

**Issue by juh9870** [InnovativeOnlineIndustries/Industrial-Foregoing#1202]
**Industrial Foregoing Version:** 3.2.14.6

**Titanium Version:** 3.2.8.6

Standalone Black Hole Unit ignores filter, no matter if items inserted via machinery or by hand

**Comment by NielsPilgaard** [comment]
Seems like this bug is still a thing, if the Black Hole Unit is inside a Black Hole Controller: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/5193
