### ISSUE TITLE
[1.16] Missing adult filter for slaughter factory

### ISSUE THREAD

**Issue by joeltine** [InnovativeOnlineIndustries/Industrial-Foregoing#1203]
**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.14.6-14.jar

**Titanium Version:**
n/a

**Crashlog If Applicable (Upload to pastebin/gist):**
n/a

In the 1.16 version of the mod, the mob slaughter factory kills babies, but there is no longer an adult filter to prevent it. It seems the adult filter was removed somewhere along the line as it used to be in the mod. W/o the adult filter, it complicates the process of breeding animals and ultimately getting only the adult offspring slaughtered.

**Comment by InsaneJ** [comment]
This is not a bug I think.

The Animal Baby Separator machine can now separate baby animals OR adult animals. In the GUI of the machine there is a button you can click  to switch between modes.
