### ISSUE TITLE
[1.16] Incompatibility with Chem Lib

### ISSUE THREAD

**Issue by tetuis** [InnovativeOnlineIndustries/Industrial-Foregoing#1204]
**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.14.7-16

**Titanium Version:**
titanium-1.16.5-3.2.8.7-22

When Chem Lib is installed, JEI recipes for Industrial Foregoing Machines are not added.

**Comment by MechOrigin** [comment]
I'm also having an issue with this
