### ISSUE TITLE
[1.16] Curio crash the game when breaking grass

### ISSUE THREAD

**Issue by Mrthomas20121** [InnovativeOnlineIndustries/Industrial-Foregoing#1211]
I honestly have no idea what is causing the crash.
I created a world, broke grass that was next to me and the game crashed. 
If it help this was in a Generic Ecosphere biome.

**Industrial Foregoing Version:**
3.2.14.7-16
**Titanium Version:**
3.2.8.7-22
**Crashlog If Applicable (Upload to pastebin/gist):**
https://gist.github.com/Mrthomas20121/dea3930c876e8da667cc2dd02da21c86

**Comment by Buuz135** [comment]
Try downgrading curios ro 4.0.5.3

**Comment by Mrthomas20121** [comment]
Downgrading curios to 4.0.5.3 seems to work.
