### ISSUE TITLE
[1.16] Plant Gatherer stops working 1 operation after a tier 1 range card is added

### ISSUE THREAD

**Issue by NepNep21** [InnovativeOnlineIndustries/Industrial-Foregoing#1212]
After adding a range card to a plant gatherer, it will stop after breaking 1 crop and never work again, only tested with mystical agriculture plants so far, the modpack is FTB oceanblock and teams settings should be allowing fake player interaction
![2021-12-02_13 57 50](https://user-images.githubusercontent.com/43792621/144468868-ffc06a76-f83e-4add-a50f-c5872707457d.png)
![2021-12-02_13 57 53](https://user-images.githubusercontent.com/43792621/144469275-8dc76ea1-6b05-4f3e-ace6-974d1bc40048.png)

**Industrial Foregoing Version:** 3.2.14.7-16

**Titanium Version:** 3.2.8.7-22

**Comment by HarbingerNo9** [comment]
I am also having the same issue. Also on Oceanblock modpack.

**Comment by JoJoJoran** [comment]
I'm having the exact same issue. Removing and reinserting the range upgrade makes it do one more operation after which it stops again.

**Comment by raflowers** [comment]
I have one Plant Gatherer working as intended with a Range Addon +1 but my second gatherer just a few blocks away set up the exact same way is experiencing this issue. I'm on the latest version of OceanBlock, I believe it's the latest version of Industrial Foregoing.
![2022-01-02_14 36 42](https://user-images.githubusercontent.com/48536856/147888858-60273127-58a2-4568-b0f9-c94fa07b6e52.png)
g
