### ISSUE TITLE
[1.16] Wither Builder ignores slot restrictions in pull mode

### ISSUE THREAD

**Issue by jeremiahwinsley** [InnovativeOnlineIndustries/Industrial-Foregoing#1216]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
`industrial-foregoing-1.16.5-3.2.14.7-16.jar`
**Titanium Version:**
`titanium-1.16.5-3.2.8.7-22.jar`

Tested on a fresh instance of Forge 36.2.20 with IF and dependencies.

When a slot is set to pull from an inventory, it ignores slot restrictions.

![2021-12-11_19 35 46](https://user-images.githubusercontent.com/7946299/145696156-3c4324fc-67e1-4dcf-99e5-201ae585052f.png)

**Comment by moody69420** [comment]
its actually any industrial foregoing machine at the moment
