### ISSUE TITLE
[1.16] Game crash on launch

### ISSUE THREAD

**Issue by iLLHunter** [InnovativeOnlineIndustries/Industrial-Foregoing#1218]
**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.14.7-16
**Titanium Version:**
titanium-1.16.5-3.2.8.7-22
**Crashlog If Applicable (Upload to pastebin/gist):**
https://pastebin.com/VRtpqnih

Has occurred a few times. Sometimes game launches, sometimes it does not. On crash, screen shows text from 'Failure Message'
I still plan on using the mod, so long as I can continue to get game launched. I just want to share crash report to help improve the mod, which I love.

**Comment by iLLHunter** [comment]
I should take notes. Just do nothing and wait for almost 3 years, slap a tag on and close the ticket. I wish I could treat support cases like this at work, would be a ton easier. Stellar job.

**Comment by Buuz135** [comment]
Pay me like your job does

**Comment by iLLHunter** [comment]
I totally would, but unfortunately, they don't have jobs that pay well for sitting around ignoring issues until enough time has passed it can be considered old then closing it unresolved, leaving game crashing bug present in their code.
