### ISSUE TITLE
[1.16] Mob Capturing Tool does not work on llamas

### ISSUE THREAD

**Issue by LuciusV** [InnovativeOnlineIndustries/Industrial-Foregoing#1221]
**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.14.7-16
**Titanium Version:**
titanium-1.16.5-3.2.8.7-22

Mob Capturing Tool does not work on llamas, both wild and wandering trader's

**Comment by Reyzerbit** [comment]
I second this bug, I have also encountered it in Industrial Foregoing version industrial-foregoing-1.16.5-3.2.14.6-14 with Titanium version titanium-1.16.5-3.2.8.4-10
