### ISSUE TITLE
[1.16] Monsters give more Liquid Meat than animals do

### ISSUE THREAD

**Issue by aaronhowser1** [InnovativeOnlineIndustries/Industrial-Foregoing#1224]
**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.14.6-14

**Titanium Version:**
titanium-1.16.5-3.2.8.4-10

FTBTeam/FTB-Modpack-Issues/issues/351

One of my players noticed that animals make more Pink Slime and less Liquid Meat, while monsters make more Liquid Meat and more Pink Slime.
![image](https://user-images.githubusercontent.com/15698722/147863928-baf6bf53-99e4-4b6f-9cc4-5bc48c5ee307.png)
Isn't that totally backwards? Shouldn't you get more food from the food mobs?

**Comment by Buuz135** [comment]
Thats how it works, its says it in the manual.

**Comment by aaronhowser1** [comment]
Why is that? Passive mobs are farmed for food. They're food mobs. Why do food mobs not make food?

**Comment by Buuz135** [comment]
Noone said that meat is how much you eat of an animal. Meat is meat even if you like to eat it or not.

**Comment by aaronhowser1** [comment]
I don't understand what you're trying to say.

It's weird to me that the optimal way to make food isn't to breed farm animals (cows, pigs, etc, mobs whose entire point is to farm for food), but to make a monster grinder, when monsters have nothing to do with food.

**Comment by WBgroup** [comment]
You make a passive mob farm for pink slime, that's how it was and that's how it is.
