### ISSUE TITLE
[1.18.2]Crash when placing a block in front of fluid extractor

### ISSUE THREAD

**Issue by DeeDoubleYous** [InnovativeOnlineIndustries/Industrial-Foregoing#1261]
Industrial Foregoing Version: 1.18.2-3.3.1.0
Crashlog (If Any):  https://pastebin.com/9Dyg7Tt7

This happens after placing a block in front of the fluid extractor, doesn't matter if a log or not. The game just crashes out and then can't be reloaded.

**Comment by Buuz135** [comment]
Update titanium
