### ISSUE TITLE
[1.18.2] Rendering Issue

### ISSUE THREAD

**Issue by aAndrew3030** [InnovativeOnlineIndustries/Industrial-Foregoing#1262]
Experiencing a weird rendering issue, were random blocks and chunks are not showing block textures. Uninstalling IF and Titanium fixes the issue, and reinstalling it causes it the issue to appear again. Moving around in the world makes the area that it shows shift. Also some blocks are rotated.
![2022-06-05_17 04 29](https://user-images.githubusercontent.com/84727133/172071602-a88899e1-69c5-42d9-bbf0-b6c36fa8b77c.png)

Titanium is 3.5.5-37
IF is 3.3.1.0-2
Forge 40.1.44 (also tried several previous versions of forge just to see if that made a difference)
Uninstalled all performance mods and rendering mods (with the exception of Flywheel, but I turned off rendering in the config)

**Comment by Buuz135** [comment]
Are there any IF machines in that area?

**Comment by aAndrew3030** [comment]
Yes, the Infinity Charger, but it is also happening in areas other then that. I also am trying to upload a log file, but github is being goofy

**Comment by aAndrew3030** [comment]
[latest.zip](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/8840831/latest.zip)
I guess the file was to large, so I had to compress it. Endless Journeymap spam making it large

**Comment by aAndrew3030** [comment]
To try to recreate the issue, I installed a new profile and added mods mentioned in the above log file. I placed Infinity chargers with infinity drill in them. Saved and restarted minecraft. The world hangs will trying to load. It wont create a crash report, but this is the log
[debug.log](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/8840894/debug.log)

**Comment by aAndrew3030** [comment]
Mod installed are curios, IF, titanium, patchouli, and JE
[latest.log](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/8840905/latest.log)
I

**Comment by Buuz135** [comment]
In all the logs I see Advent Of ascension causing issius

**Comment by aAndrew3030** [comment]
It must be the AOA integration you have implemented that is showing in the log, cause AOA wasn't installed when I recreated the issue. Also a couple are for Tinker's integration threw AOA, and that caused a bug in 1.18.2 with AOA being incompatible with Tinker's

**Comment by aAndrew3030** [comment]
Regardless, I just tested the version from the discord 3.3.1.1, and it fixed the issue and the world will load now
