### ISSUE TITLE
[1.18.2] Chunk Loading of mob duplicator not working

### ISSUE THREAD

**Issue by ixam22** [InnovativeOnlineIndustries/Industrial-Foregoing#1264]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
industrial-foregoing-1.18.2-3.3.1.1-3.jar
**Titanium Version:**
titanium-1.18.2-3.5.6-38.jar
**Crashlog If Applicable (Upload to pastebin/gist):**

Mob duplicator isn´t active with a chunk loader.
I tryed Mekansim Anchor and https://www.curseforge.com/minecraft/mc-mods/chunk-loaders

**Comment by ixam22** [comment]
chunk loading isnt working on black hole tank too

**Comment by Buuz135** [comment]
I dont think its an IF issue
