### ISSUE TITLE
[1.18.2] Material Stonework Factory - item pipes from multiple mods don't work

### ISSUE THREAD

**Issue by atlgeek007** [InnovativeOnlineIndustries/Industrial-Foregoing#1270]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version: 1.18.2-3.3.1.1-3**

**Titanium Version: 1.18.2-3.5.6-38**

**Crashlog If Applicable (Upload to pastebin/gist): N/A**

When trying to use either Item Pipes from Pipez or Mekanism Logistical Transporters, I am unable to extract any output from a Material Stonework Factory into a Black Hole Unit.

**Comment by Buuz135** [comment]
Were the black hole units full?

**Comment by atlgeek007** [comment]
There was only the one item in the black hole unit to tell me what it was (glass, sand, cobble) - also the tooltip doesn't show what's in the unit or tank in your inventory anymore, not sure if that's intended or not.
