### ISSUE TITLE
[1.18.2] Issue - AllTheMods7 Can't Plant Crops

### ISSUE THREAD

**Issue by BozzyBigBalls** [InnovativeOnlineIndustries/Industrial-Foregoing#1271]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**

**Titanium Version:**

**Crashlog If Applicable (Upload to pastebin/gist):**

Saplings work fine but generic vanilla crops don't work with the sower. Probably just me being an idiot but yeah, help?

To elaborate, i enter seeds and waited 5 mins and nothing happened in terms of planting. It has power and can plant saplings fine but not crops that require you to hoe the ground

**Comment by Buuz135** [comment]
Is the area tilled?
