### ISSUE TITLE
[1.18.2] Issue Title

### ISSUE THREAD

**Issue by patchchristensen** [InnovativeOnlineIndustries/Industrial-Foregoing#1274]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
![Screenshot 2022-06-19 194820](https://user-images.githubusercontent.com/8680491/174511511-ceec8c5a-2a28-4bf6-a096-485ba71564fd.png)
![Screenshot 2022-06-19 194840](https://user-images.githubusercontent.com/8680491/174511513-961b51cc-97b2-466a-85b9-7c86126bf4cc.png)

**Titanium Version:**

**Crashlog If Applicable (Upload to pastebin/gist):**
[crash-2022-06-19_17.05.54-fml.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/8936940/crash-2022-06-19_17.05.54-fml.txt)

Getting this crash on start up, no other mods installed. "Class loading errors"

**Comment by Buuz135** [comment]
Update titanium

**Comment by patchchristensen** [comment]
Oh thanks that worked. You might add on the curse forge page that it is a required mod, didn't see it listed there. 

Thank you so much!
