### ISSUE TITLE
[1.16] Laser Drill incompatibility with Emendatus Enigmatica

### ISSUE THREAD

**Issue by DrainLegacy** [InnovativeOnlineIndustries/Industrial-Foregoing#1278]
**Industrial Foregoing Version:**industrial-foregoing-1.16.5-3.2.14.7-16

**Titanium Version:**titanium-1.16.5-3.2.8.7-22

I'm playing on FTB Ultimate: Anniversary Edition

With the Emendatus Enigmatica mod installed, the laser drill is only able to produce Ancient Debris, Glowstone and Niter Ore. I've tried using the different lenses at the different depths but it only produce these 3 ores.

**Comment by NeariX67** [comment]
Finally found it. It is unrelated to Industrial Foregoing and Emendatus Enigmatica.

The FTB Team implemented some KubeJS scripts that alter some recipes for good reason.

## Fix:
* Go to `kubejs\server_scripts` inside your server folder
* Edit `unify.js` using nano or visual studio code for example
* Comment out or remove line 594: `event.remove({output: /emendatusenigmatica:.+_ore/})`

**Comment by DrainLegacy** [comment]
Holy! I've completely forgot about this thread. Thanks for your help!

**Comment by DrainLegacy** [comment]
Holy! I've completely forgot about this thread. Thanks for your help!
