### ISSUE TITLE
[1.18.2] Infinity Backpack's item auto-pickup doesn't work

### ISSUE THREAD

**Issue by SnideKek** [InnovativeOnlineIndustries/Industrial-Foregoing#1279]
**Industrial Foregoing Version: industrial-foregoing-1.18.2-3.3.1.4-8**

**Titanium Version: titanium-1.18.2-3.5.6-38**

Infinity Backpack doesn't pick up items as expected, even when fueled
The problem is - Backpack has already have stone stored inside and mined stone gets to player's inventory instead of backpack's inventory

![2022-06-30_23 03 32](https://user-images.githubusercontent.com/66492980/176769549-5d70431b-302f-4f3f-8726-45233b67ef43.png)
Translation: Auto-pickup is set to "Items only" mode
P.S. All slots have "Void excess" and "Restock" modes turned off

**Comment by Paraxdq** [comment]
Can confirm the issue, tested every setting and the item just lands inside the inventory.

**Comment by lucasucr** [comment]
I have also been having this issue, have tried everything but the item still goes to the inventory instead of the backpack.
