### ISSUE TITLE
[1.18.2] Sewage textures are wrong in AE2

### ISSUE THREAD

**Issue by ButterPeanuts** [InnovativeOnlineIndustries/Industrial-Foregoing#1284]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
industrial-foregoing-1.18.2-3.3.1.4-8

**Titanium Version:**
titanium-1.18.2-3.5.6-38

**Crashlog If Applicable (Upload to pastebin/gist):**
None

Sewage textures are wrong in AE2.
In Applied Energistics2 11.0.0, Some AE2 UIs(ME Terminal, Export bus, Cell Workbench...) display Sewage with a strange texture that looks like a mixture of the appearance of various items.
JEI shows the texture without any problem.

I am not sure if this is an Industrial foregoing bug or not, but I will report it here for now.
(This text was translated at DeepL)

**Comment by Buuz135** [comment]
I dont think its an IF issue if it only happens with sewage, all the IF fluids are registered the same way
