### ISSUE TITLE
[1.18.2] Enchantment Applicator cannot go higher than vanilla max limit.

### ISSUE THREAD

**Issue by KodYazanDruid** [InnovativeOnlineIndustries/Industrial-Foregoing#1288]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**  industrial-foregoing-1.18.2-3.3.1.4-8

**Titanium Version:**  titanium-1.18.2-3.5.6-38

**Crashlog If Applicable (Upload to pastebin/gist):** No crash

**Modpack:** ATM7 0.4.23

I had Fortune VII enchanted book (max level increased via Apotheosis). I tried to combine with my pickaxe with E.Applicator. It applied Fortune III. I can combine at anvil without any problem.

**Comment by Buuz135** [comment]
There is a config to enable that
