### ISSUE TITLE
[1.18.2] Create/Jei incompat

### ISSUE THREAD

**Issue by Rimusp** [InnovativeOnlineIndustries/Industrial-Foregoing#1293]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:** 3.3.1.4-8

**Titanium Version:**3.5.6-38

**Crashlog If Applicable (Upload to pastebin/gist):** No a Crash but error https://pastebin.com/Lr0eYTjW (cant upload whole log there its to big)

If i add industrial foregoing to my modpack i cant see any of creates non standard recipes (also using newest version of create and newest release jei, alpha version of jei made no difference)

**Comment by Buuz135** [comment]
Probably fixed in https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/pull/1294
