### ISSUE TITLE
[1.18.2] Conveyor and Transporter Filters Not Behaving Correctly

### ISSUE THREAD

**Issue by NyvexOfShadows** [InnovativeOnlineIndustries/Industrial-Foregoing#1298]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:** industrial-foregoing-1.18.2-3.3.1.4-8.jar

**Titanium Version:** titanium-1.18.2-3.5.6-38.jar

**Crashlog If Applicable (Upload to pastebin/gist):** N/A

In the latest version of IF, I cannot add an item to filters for conveyor upgrades and item transporters. A blacklist or a whitelist can be selected, but no item can be added for filtering purposes. Right- and left-click do not work as they are expected to work. If there's a specific way to add the item to the filter, it is not documented in the Patchouli manual.

**Comment by Lexicade** [comment]
@NyvexOfShadows I managed to get it working once earlier and spent a while trying to replicate what I did. The good news is that there is a workaround.

The filter doesn't accept a dragged item at all. Instead place the desired item on the hotbar as your held item. Open the GUI and click the filter and it should show up as you'd expect. 

Little bit funky, but at least this is usable :)

**Comment by Kage-Yami** [comment]
> @NyvexOfShadows I managed to get it working once earlier and spent a while trying to replicate what I did. The good news is that there is a workaround.
> 
> The filter doesn't accept a dragged item at all. Instead place the desired item on the hotbar as your held item. Open the GUI and click the filter and it should show up as you'd expect.
> 
> Little bit funky, but at least this is usable :)

Unfortunately, this workaround doesn't work for fluid transporters, as you can't hold fluid in your hand. Adding buckets of fluid into the filter doesn't work (e.g. set a receiving transporter to allowlist-mode, and add a bucket of water to the filter; water from the sending tank will not be moved to the destination tank)
