### ISSUE TITLE
[1.18.2] Project Expansion's Infinite Steak destroys JEI dissolution chamber recipes

### ISSUE THREAD

**Issue by AmmoniumX** [InnovativeOnlineIndustries/Industrial-Foregoing#1300]
When playing with both Industrial Foregoing and Project Expansion, JEI does not display dissolution chamber recipes.
The issue appears to be specifically with the "infinite steak" item, i.e. if you fork Project Expansion and remove the infinite steak item, the issue does not persist. 

Due to the nature of bugs involving multiple mods, I am not sure if this is entirely IF's fault, but my (somewhat educated) guess is the the infinite steak may cause problems with the culinary mycelial reactor's calculations, breaking JEI recipes along the way. If this is not a bug on IF's side, then I apologize.

Steps to reproduce:
1. Install Industrial Foregoing, JEI, and Project Expansion on the same Minecraft Instance.
2. Load and join a world
3. (Sometimes necessary, sometimes not) type /reload
4. View a recipe for any item inside a dissolution chamber, e.g. simple machine frame.

Expected outcome: JEI would show the recipe for said item.
Actual outcome: JEI does not show any recipe.

**Forge Version:** 40.1.73

**JEI Version:** jei-1.18.2-9.7.1.255.jar

**Project Expansion Version:** ProjectExpansion-1.18.2-1.0.13.jar

**Industrial Foregoing Version:** industrial-foregoing-1.18.2-3.3.1.4-8.jar

**Titanium Version:** titanium-1.18.2-3.5.6-38.jar

**Crashlog If Applicable (Upload to pastebin/gist):**

**Comment by AmmoniumX** [comment]
Thanks for the fast fix, Is it coming to 1.18.2 as well or only 1.19?

**Comment by Xplodin** [comment]
Hopefully this comes to 1.18 as it broke my pack :((
