### ISSUE TITLE
Middle Mouse clicking in inventory screen of Mob Crusher results in items deleted including upgrade modules

### ISSUE THREAD

**Issue by 2ndRecon** [InnovativeOnlineIndustries/Industrial-Foregoing#1301]
Industrial Foregoing
1.18.2-3.3.1.5-9

Titanium
1.18.2-3.5.6-38

**Problem Statement:**
When in the inventory screen of the Mob Crusher; middle-mouse clicking in the loot inventory area results in all items being deleted including any installed range modules. Essence container doesn't appear to be impacted as any accrued Essence remains in the inventory.

**Steps to Duplicate**
Deploy an IF 'Mob Crusher' and provide sufficient power.
Install any combination of upgrade modules.
Spawn mobs and allow them to be killed/harvested.
Verify loot drops have been generated in the inventory of the Mob Crusher.
Move your mouse cursor into the 3x6 orange inventory area
Click Middle-Mouse || 'Middle Button' in keybinds menu.
Watch your loot and upgrades vanish into the nether.

**Comment by drivetheory** [comment]
Possibly related to the Inventory Sorter mod, which by default uses the Middle (mouse) Button for sorting inventory, which is why those of us who experience this bug are clicking the middle mouse button in the inventory.

**Comment by Buuz135** [comment]
Not IF issue

**Comment by 2ndRecon** [comment]
Update: For what it's worth, my son and I are now playing FTB Skies, and this behavior is also present on this pack.

I am opening a new issue on that pack, but just for anyone who may find this post in FTB Skies 1.0.3 and 1.0.4, opening the Flower pouch (botania) WITH flowers inside it, and middle-mouse-clicking inside the flower pouch will void ALL flowers in the inventory of the pouch.
