### ISSUE TITLE
[1.18.2] statis chamber

### ISSUE THREAD

**Issue by Warbringer12** [InnovativeOnlineIndustries/Industrial-Foregoing#1304]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:*industrial-foregoing-1.18.2-3.3.1.5-9*

**Titanium Version:*titanium-1.18.2-3.5.6-38*

statis chamber doesn't show working area/ nor does it accept range upgrades

**Comment by X-Niter** [comment]
Just to add to this here sense @Warbringer12 touched on the subject. 

There is actually a few different machines that don't render there working area. 
Sadly I don't have a current list of all of them and this was noticed on a 1.18.2 Stoneblock 3 server.
