### ISSUE TITLE
[1.19] Infinity tools resetting upon actions in smithing table

### ISSUE THREAD

**Issue by PikachuGabe** [InnovativeOnlineIndustries/Industrial-Foregoing#1311]
**Industrial Foregoing Version:**
industrial-foregoing-1.19.2-3.3.2.0-2

**Titanium Version:**
titanium-1.19.2-3.7.0-23

https://user-images.githubusercontent.com/84477180/205458574-c3a9c4e5-0c45-4406-bda1-7d74db0ba974.mp4

dont mind how janky my video is,i had to trim down the size and i kinda overdid it with handbrake.
i reforge it to be an apotheosis item with slots so i have the easiest way to use a smithing table on it,applying a gem. when i apply the gem,the hammer fully resets back to as if it was just crafted.

**Comment by PikachuGabe** [comment]
here i got a better video

https://user-images.githubusercontent.com/84477180/205465019-5671b067-17d6-4708-97cc-82501cf56738.mp4

**Comment by PikachuGabe** [comment]
silly me accidently closing

**Comment by Buuz135** [comment]
I'm not really sure if thats IF fault?

**Comment by PikachuGabe** [comment]
Yeah,i sent it in both IF and apoth github just incase,apoth is https://github.com/Shadows-of-Fire/Apotheosis/issues/733

**Comment by jmac460** [comment]
I sent the issue to Apotheosis but they claim it's IF's issue, but this is definitely annoying

**Comment by eyesoffaith** [comment]
I've also recently run into this issue while playing ATM8. I'd be interested to see if there is some kind of fix for this.

Thank you all again for your hard work. Always enjoyed IF

**Comment by Brother-Blue** [comment]
Is there any update to this issue? Encountered it on an ATM9 server

**Comment by PikachuGabe** [comment]
Unfortunately there is not and most likely never will be unless the infinity tools get redesigned. The two mods simply blame it on eachother.
