### ISSUE TITLE
[1.19] Fluid drill not working

### ISSUE THREAD

**Issue by ryan-l-hayden** [InnovativeOnlineIndustries/Industrial-Foregoing#1313]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:** industrial-foregoing-1.19.2-3.3.2.1-3.jar

**Titanium Version:** N/A

**Crashlog If Applicable (Upload to pastebin/gist):** N/A

This appears to be a continuation of https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1305 . 
Fluid drill was set in nether wastes at level 15, with orange lens. It fills but does not collect any lava. This was tested in creative and survival. Since lava has the same whitelist/blacklist that Ancient Debris has, and the above issue only seems to have been applied to the ore laser base tile class, I'm thinking maybe fluid laser base need the same fix. But that is just a guess.
ref - https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/commit/95ed24ea8818814dbcb6afb1c233df4bc1a1643e#diff-6ac05e9f91ea6daf962cfc7d41549668b7870888e784a2118b1d016e75fa18ef

**Comment by Buuz135** [comment]
Fixed in #1319
