### ISSUE TITLE
[1.18.2] Dissolution Chamber Stops When World/Server is Stopped

### ISSUE THREAD

**Issue by Avakining** [InnovativeOnlineIndustries/Industrial-Foregoing#1317]
The Dissolution Chamber stops working when quitting/reopening the world. An item needs to be removed and replaced in its slot to resume functioning.

Screen recording showcasing the problem: https://youtu.be/N0X5qGFJtlE

**Industrial Foregoing Version:** 3.3.1.5

**Titanium Version:** 3.5.8

**Crashlog If Applicable (Upload to pastebin/gist):**

**Comment by Buuz135** [comment]
Fixed bdcbcf463567c74a3ac9550032f7ac6590affe83
