### ISSUE TITLE
[1.19] Mob Imprisonment Tool does not retain Gossip tag upon releasing Zombie Villagers

### ISSUE THREAD

**Issue by Jkosio23** [InnovativeOnlineIndustries/Industrial-Foregoing#1318]
**Industrial Foregoing Version:** 3.3.2.1

**Titanium Version:** 3.7.0

Using Integrated dynamics I found out that when transporting zombie villagers with the Mob Imprisonment Tool (MIT), the entity data about gossips makes it into the MIT, but once the Zombie Villager is released it does not have the Gossips NBT tag whatsoever. Pictures attached in order are Uncured Villager, Zombified Villager, MIT with Zombie Villager, and then Released Zombie Villager.

![image](https://user-images.githubusercontent.com/35435541/209449701-52503f9b-4856-431d-ac4c-d0accf10181e.png)
 
![image](https://user-images.githubusercontent.com/35435541/209449718-d606cece-4020-48a9-b542-61948adc287f.png)

![image](https://user-images.githubusercontent.com/35435541/209449736-359ea215-6862-4cd0-9c51-e2e45432f31a.png)

![image](https://user-images.githubusercontent.com/35435541/209449750-13035840-04f0-4032-a392-277e6e2dd168.png)

**Comment by Jkosio23** [comment]
Gossips lies between FallFlying and PortalCooldown

**Comment by Buuz135** [comment]
This might be some minecraft special thing, I don't remove anything from it.
