### ISSUE TITLE
[1.19] Error with AE2 Wireless Crafting Terminal

### ISSUE THREAD

**Issue by TomasGnG** [InnovativeOnlineIndustries/Industrial-Foregoing#1322]
**Industrial Foregoing Version:** 1.19.2-3.3.2.1-3

**Titanium Version:** 1.19.2-3.7.0-23

**Crashlog If Applicable (Upload to pastebin/gist):** https://mclo.gs/bwQGYRW

**Additional Informations:**
Playing on ATM8 1.0.8 server.
1. Crafted the Block Placer
2. Closed the inventory
3. Wireless Crafting Terminal broke and couldn't be opened anymore

**Comment by Buuz135** [comment]
There is nothing mentioned in the log about IF
