### ISSUE TITLE
[1.18.2] titanium dependency commented out in the mods.toml

### ISSUE THREAD

**Issue by fayer3** [InnovativeOnlineIndustries/Industrial-Foregoing#1323]
**Industrial Foregoing Version:** industrial-foregoing-1.18.2-3.3.1.5-9

**Titanium Version:** none

**Crashlog If Applicable (Upload to pastebin/gist):** https://gist.github.com/fayer3/9662187bf31e28cd540689df20d6ae38

the titanium dependence in the mods.toml is commented out, therefor forge doesn't warn the user if it's missing and just crashes
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/1.18/src/main/resources/META-INF/mods.toml#L29-L34

**Comment by Deathboy671** [comment]
Your missing a mod https://www.curseforge.com/minecraft/mc-mods/titanium

**Comment by fayer3** [comment]
yes I know, that's the whole point of this issue, if it were mentioned int the toml, forge would have let me know
