### ISSUE TITLE
[1.16] Fluids flowing from the top replaces fluid source blocks

### ISSUE THREAD

**Issue by juh9870** [InnovativeOnlineIndustries/Industrial-Foregoing#1324]
**Industrial Foregoing Version:** industrial-foregoing-1.16.5-3.2.14.7-16.jar

**Titanium Version:** titanium-1.16.5-3.2.8.7-22.jar

**Crashlog If Applicable (Upload to pastebin/gist):** -

When fluid source of IF fluid (tested with Latex and Ether Gas) is placed above another source fo the same fluid, the bottom source will get deleted and replaced with flowing fluid with broken localization name
![image](https://user-images.githubusercontent.com/15922601/213885385-0d4c3277-ec84-480b-891e-e0557af1b5cc.png)

**Comment by Kenshij** [comment]
This bug blocks the use of pumps, because they playe source blocks multiple times in the same postion and you can't create a propper infinite source with the create hose pulley, because it sucks this strange fluid out, which is not recognized from all recipes with latex in the desolution chamber.
