### ISSUE TITLE
[1.19] item dupe in ATM8 just from crafting

### ISSUE THREAD

**Issue by Pultex** [InnovativeOnlineIndustries/Industrial-Foregoing#1327]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version: industrial-foregoing-1.19.2-3.3.2.1-3**

**Titanium Version:titanium-1.19.2-3.7.1-24**

**Crashlog If Applicable (Upload to pastebin/gist): no crash yet**

it I craft any thing from the mod half of the items are returned to me

I get the advanced frame, any of the frames really, after crafting in a vanilla crafting table

I a refined storage grid the items will be there after pulling out the item from the grid
but will not really be items and will freeze the grid

Returning the items to the refine system with the X button on the grid will it time
cause a error of "ItemStack value must not be empty" as the items returned are not real
but dupes

This ONLY happens with any Industrial foregoing item craft all other craft are fine so
it must be an error in this mod

The dupe is not a problem but the destruction of the ENTIRE refine storage system is

also external storage from refine can not be connected to any Industrial Foregoing machines
it will cause the same error of empty stacks

Edit:
So looking at refined storage old closed issues that did not get fixed
the error seem to be a thread issue in minecraft that is a java issue that the mod can not fix
maybe forge can find a workaround though an api or something
odd as this happened in older versions of minecraft the in 1.12 -1.18 did not happen 
now we need to use java 17-19 the problem is back

java really is a list of problems just waiting to return

**Comment by Pultex** [comment]
I am wrong this is the same problem that Refine storage has with
Silent Gear
I you have no silent gear on your hot bar or your inventory there is no bug
this may not happen at all on server base worlds
that was the reason only a few had the refine storage problem effects only SP worlds

**Comment by Buuz135** [comment]
Not an IF issue
