### ISSUE TITLE
[1.19] Sewer keeps 

### ISSUE THREAD

**Issue by SourPatchSundae** [InnovativeOnlineIndustries/Industrial-Foregoing#1329]
industrial-foregoing-1.19.2-3.3.2.1-3.jar
titanium-1.19.2-3.7.0-23.jar

**Comment by castilio20** [comment]
buuz how could you not fix this issue it so simple....

**Comment by Buuz135** [comment]
It just keeps

**Comment by SourPatchSundae** [comment]
fat finger
