### ISSUE TITLE
[1.18.2] Black hole inventory on multiplayer not showing

### ISSUE THREAD

**Issue by TheAnsuz** [InnovativeOnlineIndustries/Industrial-Foregoing#1333]
### Information

**Industrial Foregoing Version: industrial-foregoing-1.18.2-3.3.1.5-9**

**Titanium Version: titanium-1.18.2-3.5.7-39**

**There is no crashlog nor any logs on the minecraft's console**

### Description
Black hole units do not open their respective inventory on multiplayer, they still work fine but no interface whatsoever.
 _The host (if any) seems to be capable of opening said interfaces_

**Comment by Buuz135** [comment]
Try updating titanium
