### ISSUE TITLE
[1.19] Plant Sower upgrade vanishing

### ISSUE THREAD

**Issue by sekwah41** [InnovativeOnlineIndustries/Industrial-Foregoing#1346]
**Industrial Foregoing Version:** 3.3.2.3

**Titanium Version:** 3.7.2

Upgrades vanish when middle mouse button is pressed

https://user-images.githubusercontent.com/3209834/230925990-03940d49-83a9-45fc-b644-205325830cc2.mp4

**Comment by sekwah41** [comment]
For context, this is in the FTB Skies modpack. I have not tested this on its own.

**Comment by Buuz135** [comment]
That is the mod that sorts fault, as its not a traditional inventory.

**Comment by sekwah41** [comment]
Ahh perfect, wasn't sure as I was also told by a friend that it does it with some machines but not others.
