### ISSUE TITLE
[1.19] Placing Item Transporter Crashes Client

### ISSUE THREAD

**Issue by 0xhayleydev** [InnovativeOnlineIndustries/Industrial-Foregoing#1351]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
3.3.2.3

**Titanium Version:**
3.7.3

**Crashlog If Applicable (Upload to pastebin/gist):**
https://pastebin.com/AQUQ1Wuq

Steps to reproduce:
1. Place conveyor belt headed into a chest
2. Place an Item Transporter onto the chest
3. Game crash

Notes:
- Playing ATM8
- Using MultiMC
- Playing on a multiplayer server

Video for reference:
https://youtu.be/2qFR-2BJF9I

**Comment by polyarkk** [comment]
will still crash in MC/IF/TI version: 1.20.1 3.5.19 3.8.32
