### ISSUE TITLE
[1.19] Enchantment Applicator not displaying essence level correctly

### ISSUE THREAD

**Issue by stayingarmed** [InnovativeOnlineIndustries/Industrial-Foregoing#1354]
**Industrial Foregoing Version:** industrial-foregoing-1.19.2-3.3.2.3-5.jar

**Titanium Version:** titanium-1.19.2-3.7.3-27.jar

**Crashlog If Applicable (Upload to pastebin/gist):**

When using the enchantment applicator with a tank full of essence beside it pulling in the essence, it gets to the halfway point of filling the applicator and then it starts blinking (showing empty) until I turn off "pull" and then it displays the actual amount in the applicator until I turn pull on again..I have to keep turning pull on/off to see the actual amount in the applicator and if I leave the gui for the applicator and go back in, it shows empty until I toggle one of the input directions.

**Comment by Buuz135** [comment]
This should be fixed already
