### ISSUE TITLE
[1.16] Game crashes in loading, with IF being labeled the culprit. 

### ISSUE THREAD

**Issue by zdb2k** [InnovativeOnlineIndustries/Industrial-Foregoing#1355]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
industrial-foregoing-1.16.5-3.2.14.7-16.jar
**Titanium Version:**
titanium-1.16.5-3.2.8.7-22.jar
**Crashlog If Applicable (Upload to pastebin/gist):**
[crash-2023-07-01_15.13.16-fml.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/11927306/crash-2023-07-01_15.13.16-fml.txt)

I also tried going from the most current version to earlier versions and that did not solve the issue.

**Comment by Buuz135** [comment]
Delete the IF config files
