### ISSUE TITLE
[1.19] Fermentation Station giving incorrect output.

### ISSUE THREAD

**Issue by Kevin-Marsh** [InnovativeOnlineIndustries/Industrial-Foregoing#1358]
Industrial Foregoing Version: 1.19.2-3.3.2.3-5

Titanium Version:1.19.2-3.7.3-27

The Fermentation Station appears to be outputting 15x the fermented ore meat instead of 5x when you select the 5x mode and supply it with ether gas. This was brought to my attention from another player and I also confirmed it on my game. Right now it is 10 raw in and 150 ingots out which is very nice but maybe not what was intended.

**Comment by technomancer21** [comment]
As the player who made the discovery and reported it to Kevin-Marsh, I feel I should point out that I was using tier two speed, efficiency, and processing upgrades in the full chain of machines, washing factory > fermentation station > fluid sieving machine > resourceful furnace.
I personally would like to know if this was an intended function of the upgrades, or if indeed a bug.

**Comment by Buuz135** [comment]
If they are using processing upgrades (that they make that the machines does more actions at once) make sure the machine isn't consuming 3x times too of the input fluid.

**Comment by Kevin-Marsh** [comment]
![2023-07-24_20 53 02](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/assets/9076964/fc43c985-decd-4f69-9534-72e534fae788)
![2023-07-24_20 53 06](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/assets/9076964/ac13d956-1a2e-4a16-9906-547a775b3347)

I triple checked for you. It is definitely 1 bucket in 15 buckets out. And it didn't happen without the addons.
