### ISSUE TITLE
[1.19] Breaking a black hole unit makes it no longer accept same item type

### ISSUE THREAD

**Issue by puchm** [InnovativeOnlineIndustries/Industrial-Foregoing#1359]
**Industrial Foregoing Version:**
industrial-foregoing-1.19.2-3.3.2.3-5

**Titanium Version:**
industrial-foregoing-1.19.2-3.3.2.3-5

**Issue**
When breaking a black hole unit, it gives the item an empty tag. This causes it to no longer accept items of the same type, since it is trying to put in items without the tag, but only accepts items with the tag.
I can confirm the tag only appears after breaking and replacing it. I have tested this with the Supreme Black Hole Unit.

See screenshot of the NBT data:
![image](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/assets/21011840/31693fe6-de0d-459c-9ac1-c1069daa9db8)

I can also confirm that removing the tag manually through commands makes it accept items again.

i.e.: `/data remove block -140 -58 79 blStack.tag`

**Comment by catt0** [comment]
Can confirm the bug in MC 1.20.1, Industrial Foregoing version 3.5.9, Titanium version 3.8.23, forge 47.1.3 (ATM9 0.2.18b on a dedicated server). Tag appears when putting down the unit with items in it. Using the command fixes the contents.

**Comment by Buuz135** [comment]
A random mod is messing the Empty stack and adding nbt to it
