### ISSUE TITLE
[1.19] Infinity Drill not mining when charging

### ISSUE THREAD

**Issue by codesmith47** [InnovativeOnlineIndustries/Industrial-Foregoing#1360]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
1.19.2-3.3.2.3-5
**Titanium Version:**
1.19.2.3.7.3-27
**Crashlog If Applicable (Upload to pastebin/gist):**
N/A 

When trying to use the drill while being charged by the "Player Transmitter" from Powah the drill won't mine until charging is disabled.

**Comment by Buuz135** [comment]
Use the infinity charger

**Comment by codesmith47** [comment]
Yes, that charges faster, but my initial problem is that the drill is being charged wirelessly while mining, it cannot mine any blocks while that is happening. I use the "Player Transmitter" from Powah to charge all my items while I am out and about.

A fix to make the drill work while getting charge would be great!
