### ISSUE TITLE
[1.20] Mod loading error has occurred with no other mods

### ISSUE THREAD

**Issue by parmstr2** [InnovativeOnlineIndustries/Industrial-Foregoing#1362]
**Industrial Foregoing Version:** 1.20.1-3.5.4

**Titanium Version:** 1.20.1-3.8.1-9

**Crashlog If Applicable (Upload to pastebin/gist):** https://pastebin.com/arhMNFCj

As stated in the title I get a "mod loading error has occurred" with no other mods installed besides Patchouli.

**Comment by Buuz135** [comment]
Update titanium
