### ISSUE TITLE
 [1.20] Issue Block Placer not placing

### ISSUE THREAD

**Issue by JediAvenger** [InnovativeOnlineIndustries/Industrial-Foregoing#1363]
industrial-foregoing-1.20.1-3.5.7

Block placer not placing blocks.  Shows no working area.

**Comment by Buuz135** [comment]
Make sure its not in a protected area

**Comment by JediAvenger** [comment]
Thanks.  I needed to allow fake players.

**Comment by sreny1** [comment]
for the record, the fake player ID is:
ec5b5875-ebb5-4b47-833b-0de37ac9e6d7

As found here:
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/fc4c286af75d164d213c86ac1c9df8cfa4e49977/src/main/java/com/buuz135/industrial/utils/IFFakePlayer.java#L41
