### ISSUE TITLE
[1.16] Can't Use range addon 

### ISSUE THREAD

**Issue by terrarian10** [InnovativeOnlineIndustries/Industrial-Foregoing#1364]
**Industrial Foregoing Version:*industrial-foregoing-1.16.5-3.2.14.7-16.jar*

**Titanium Version:** titanium-1.16.5-3.2.8.4-10.jar

Attempts to place the range addon into things like the plant fertilizer, placer, harvester, and sewer have failed in the following manner

https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/assets/67126671/c1db17d7-2e47-4af2-8113-0f2b22ec1460

The addons also are unobtainable (IDK if this is purposeful or not) and mod name tooltip says Minecraft instead of Industrial Foregoing

Edit: This works with some range cards (like tier 2) but not others (ex. tier 4)

**Comment by Buuz135** [comment]
Update the mod and don't use the give commands to get them
