### ISSUE TITLE
[1.20] Dissolution chamber not accepting inputs when inputs locked

### ISSUE THREAD

**Issue by dvdmcwilliams** [InnovativeOnlineIndustries/Industrial-Foregoing#1366]
Whenever I try to lock the recipe to automate a frame, for example, the machine wont accept any input. 
Tried to set pull from any side of the machine with no luck at all, the only way I can use it is by crafting a frame at a time.
All of this by playing on Allthemods9.

**Industrial Foregoing Version:**
industrial-foregoing-1.20.1-3.5.9

**Titanium Version:**
titanium-1.20.1-3.8.21

**Crashlog If Applicable (Upload to pastebin/gist):**

**Comment by Kadah** [comment]
A number of machines appear to have this behavior, like the plant sower, which also seems to have its placement grid rotated 90 degrees.

**Comment by BloodInAs** [comment]
Hello, will you fix this with an update, or should we add the code ourselves?

**Comment by Buuz135** [comment]
Update titanium? It was marked as completed

**Comment by BloodInAs** [comment]
I don't quite understand. You closed my ticket with a problem, with a duplicate reason and referred here. What is the solution to the problem?

**Comment by Buuz135** [comment]
The issue was fixed 8h ago. Update titanium

**Comment by Kadah** [comment]
Workaround for the previous version:

Insert items one at a time. Vanilla hoppers can do it, as can setting LaserIO's item transfer being limited to one per action.

**Comment by Kadah** [comment]
Still seeing the same bugged behavior on `titanium-1.20.1-3.8.23` in DW20-1.20 1.3.1 pack.

To repo, I change the LaserIO node to insert from 1 item per 20 ticks (the workaround) to the default of 8. If the number trying to be inserted is greater than the the free slots for that item, nothing is inserted.
