### ISSUE TITLE
[1.20]game crashing on boot

### ISSUE THREAD

**Issue by mango11587** [InnovativeOnlineIndustries/Industrial-Foregoing#1369]
game crashes when i boot saying this"The game crashed whilst initializing game
Error: net.minecraftforge.fml.ModLoadingException: Industrial Foregoing (industrialforegoing) encountered an error during the common_setup event phase" i have all the mods needed tired different version still nothing and updated forge java everything works with out the mods too

**Comment by Buuz135** [comment]
Please provide a crash report

**Comment by mango11587** [comment]
works now don't know why thanks anyway
