### ISSUE TITLE
[1.20] The Conveyor Extraction Upgrade item pulls items out of players.

### ISSUE THREAD

**Issue by ProjectTorturer** [InnovativeOnlineIndustries/Industrial-Foregoing#1377]
Bug item:
-  Meta: `industrialforegoing:conveyor_extraction_upgrade`
------
- The Conveyor Extraction Upgrade item pulls items out of players.
------
**Industrial Foregoing Version:**
- 1.20.1 - 3.5.9
------
**Titanium Version:**
- 1.20.1 - 3.8.21
------
**WorldGuard Version**
- worldguard-bukkit-7.0.9-dist.jar

**Comment by Buuz135** [comment]
This is intended
