### ISSUE TITLE
[1.19] Adult filter missing for mob slaughter factory

### ISSUE THREAD

**Issue by Naddox** [InnovativeOnlineIndustries/Industrial-Foregoing#1378]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

Looks like others have reported this issue but for version 1.16, which means this has been missing for several versions.

**Industrial Foregoing Version:** 3.3.2.3-5

**Titanium Version:** 3.7.3-27

**Crashlog If Applicable (Upload to pastebin/gist):**

**Comment by Buuz135** [comment]
Intended
