### ISSUE TITLE
[1.20] Dissolution chamber not accepting inputs

### ISSUE THREAD

**Issue by BloodInAs** [InnovativeOnlineIndustries/Industrial-Foregoing#1379]
**Industrial Foregoing Version:**
3.5.9
**Titanium Version:**
3.8.22

The dissolution chamber, when locked, does not accept any objects. I tried both through the inventory and through pipes from various mods, such as mekanism, ender-io, xnet. AE2 supplies via the export bus.

'industrialforegoing:dissolution_chamber'

**Comment by Buuz135** [comment]
Duplicate #1366
