### ISSUE TITLE
[FEATURE] Add a mob processor similar to the cloche

### ISSUE THREAD

**Issue by Buuz135** [InnovativeOnlineIndustries/Industrial-Foregoing#138]
Industrial Foregoing Version: 
TeslaCoreLib Version: 
Crashlog (If Any):

**Comment by charlesbevans** [comment]
There are lots of duplicated machines in MC. Since pack-makers can turn it off, I'm good with having an alternative. Woot is quite the undertaking and provided with any alternative, many will just make a mob farm.
