### ISSUE TITLE
[1.18.2] industrial forgoing machine blocks dont open the UI, gives huge error in serverside console

### ISSUE THREAD

**Issue by CoolGo1425** [InnovativeOnlineIndustries/Industrial-Foregoing#1380]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
industrial-foregoing-1.18.2-3.3.1.6-10

**Titanium Version:**
titanium-1.18.2-3.5.10-44

**Crashlog If Applicable (Upload to pastebin/gist):**
https://paste.sparked.host/uvahamejik   -   (latest.log since no crash, error is near the bottom)

**Comment by Buuz135** [comment]
Update titanium
