### ISSUE TITLE
[1.20] Impossible to automate Dissolution Chamber recipes through AE2 Pattern Provider

### ISSUE THREAD

**Issue by burdoto** [InnovativeOnlineIndustries/Industrial-Foregoing#1381]
**Industrial Foregoing Version:** 3.5.9
**Titanium Version:** 3.8.22

title says it all. also trying to use pipes for automating seems impossible bcs even if i lock the recipe, for some reason the pipes cannot insert the right items

**Comment by Buuz135** [comment]
Update titanium

**Comment by burdoto** [comment]
sometimes rebuilding the dissolution chamber helps, but also not always
