### ISSUE TITLE
[1.20] FileNotFoundException

### ISSUE THREAD

**Issue by Sultia** [InnovativeOnlineIndustries/Industrial-Foregoing#1390]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:** 3.5.9

**Titanium Version:** 3.8.23

**Crashlog If Applicable (Upload to pastebin/gist):** 
[latest.log](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/13452958/latest.log)

**Comment by Buuz135** [comment]
I don't see any crash related to Industrial Foregoing in that log
