### ISSUE TITLE
[1.19] Item Transporters have a hard time pulling from Functional Storage Drawers

### ISSUE THREAD

**Issue by MuteTiefling** [InnovativeOnlineIndustries/Industrial-Foregoing#1393]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
industrial-foregoing-1.19.2-3.3.2.3-5

**Titanium Version:**
titanium-1.19.2-3.7.4-28

Original report: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/800

Can reproduce this if I follow those exact steps.

**Comment by Buuz135** [comment]
Smh stop using that mod, Storage Drawers is better

**Comment by MuteTiefling** [comment]
.... Stop using your drawers. 😜

**Comment by Buuz135** [comment]
Moved to FS
