### ISSUE TITLE
[1.20.1]  Skipping loading recipe as it's serializer returned null

### ISSUE THREAD

**Issue by jamieb999** [InnovativeOnlineIndustries/Industrial-Foregoing#1401]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**   industrial-foregoing-1.20.1-3.5.14

**Titanium Version:** titanium-1.20.1-3.8.25

**Crashlog If Applicable (Upload to pastebin/gist):**

https://pastebin.com/RuBycDH1

See the pastebin above for the full logs. 

You keep getting an error like this there are several receipes that
are not loading 

[12Jan.2024 23:12:42.379] [main/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Skipping loading recipe industrialforegoing:laser_drill_ore/ores/fluorite as it's serializer returned null

see the pastebin above. There are multiple recipes not loading it is 
not just that one. 

The server here is a forge 1.20.1 server 
running  forge-1.20.1-47.2.4-installer.jar

So why am I getting these info and why are the recipe's not loading? 

I went on your discord server and I was on the  industrial-foregoing channel  
to get answers about this as well prior to opening this bug ticket to see if it 
could be easily fixed but I got no answer on you discord server. 
I believe this is a bug with the mod anyways and a ticket probably should be 
opened here. 

Can you please fix this issue. 

Jamie (she / her)

**Comment by jamieb999** [comment]
Full logs on startup are at https://pastebin.com/6AzqxX0H

**Comment by Buuz135** [comment]
Working as intended

**Comment by jamieb999** [comment]
No it isn't working as intended.. it should load the recipes or if it doesn't see the correct mod pack 
there then it should skip trying to load the item all together this is most definately not working as intended. This needs
to be fixed.

**Comment by Buuz135** [comment]
This it what it does. Are you a modder to know how it works?

**Comment by jamieb999** [comment]
I am a trained professional in the IT field and I know that this is sloppy. If it doesn't detect the mod needed to load that item
then it should not even try to load the issue. This needs to be fixed.  This is not working properly and needs to be fixed.  This issue is not fixed. reopen this ticket now.

**Comment by Buuz135** [comment]
Nah, it's a forge thing, you literally have no idea how this works.

**Comment by Buuz135** [comment]
I literally have public repos and millions of downloads, what do you have? Nothing. 

Go cry somewhere else.

**Comment by TelepathicGrunt** [comment]
> Don't tell me that I don;t have any idea how it works because I do. Wow you are insulting. Are you the dev? because you have no clue how to properly code a mod. Fix this issue this matter is not resolved.

@jamieb999 Hello, I am too a dev. Please do not insult other devs. Your profession has no meaning here. This is coding for a Minecraft mod which has a lot of quirks and things to consider. If you do not mod, which it seems you are admitting to not be doing so, that means you do not understand this log entry at all despite claiming that you do. A lie.

The log entry is working as intended by Forge. Seriously. Right here in Forge's patch.
https://github.com/MinecraftForge/MinecraftForge/blob/88d2dc6c8f91fd3a6b38fa06bd92cde2db1c94db/patches/minecraft/net/minecraft/world/item/crafting/RecipeManager.java.patch#L35

The whole point is the custom recipe condition added by Forge (for Buuz135's and everyone else's use case of supporting inter-mod recipes) will return null if no condition matches (like the other mod not being on) which then Forge will explicitly log this recipe skipping with that log message you see.

This was a conscious decision by Forge to log this at info level to the logs in 1.20.1.

**Comment by unilock** [comment]
If I'm understanding Forge's code correctly, that `Logger#info` call should never be reached if the recipe's conditions aren't met, which makes me think that there is indeed an issue here.
