### ISSUE TITLE
[1.12] infinity drill drilling more than 13x13x13 area

### ISSUE THREAD

**Issue by panthera** [InnovativeOnlineIndustries/Industrial-Foregoing#1402]
![2024-01-21_20 49 39](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/assets/56058733/c0d28af1-33f7-4a0b-96dd-fe72c6df586f)
the drill occasionally does more than the largest area possible, all that dirt and stone in the birch forest is from my drill....... i tried to put myself in the nearest spot to where i used the drill before that happened(green arrow) this is the _**8th**_ time it happened to me

**Comment by Buuz135** [comment]
👋 Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
