### ISSUE TITLE
The Recycler is missing PLEASE

### ISSUE THREAD

**Issue by Speznat** [InnovativeOnlineIndustries/Industrial-Foregoing#1406]
Where you can throw every item in there and getting scraps from and need to unbox that for random items. That was one of the best features of industrialcraft for example. PLEASE please do that.

**Comment by Buuz135** [comment]
Wrong mod

**Comment by Speznat** [comment]
> Wrong mod

??? a recycler for industrial foraging this is the repository for industrial foraging or not? what?
