### ISSUE TITLE
Recycler for Industrial Foregoing please

### ISSUE THREAD

**Issue by Speznat** [InnovativeOnlineIndustries/Industrial-Foregoing#1408]
Where you can throw every item in there and getting scraps from and need to unbox that for random items. That was one of the best features of some other packs that are long abbondoned. PLEASE plerase guys do that for you mod would be awesome.

**Comment by Buuz135** [comment]
This is INDUSTRIAL FOREGOING no INDUSTRIALCRAFT

**Comment by Speznat** [comment]
> This is INDUSTRIAL FOREGOING no INDUSTRIALCRAFT

yeah and thats why im suggesting an recycler what do you dont understand about a SUGGESTION!!!! because all other modpacks who have something like a recycler are 20 years old and dont work anymore!!!!!
