### ISSUE TITLE
[1.20] Issue Title About Potion Brewer can"t work normally

### ISSUE THREAD

**Issue by Xhuge1** [InnovativeOnlineIndustries/Industrial-Foregoing#1413]
**Industrial Foregoing Version:*3.5.14*

**Titanium Version:*3.8.25*

The Potion Brewer can"t work normally.
If I put glass bottle in it, all I get is a water bottle. Then it stops working.

**Comment by Buuz135** [comment]
Do you put the ingredients at the top? and blaze powder too?

**Comment by Xhuge1** [comment]
> Do you put the ingredients at the top? and blaze powder too?
ofcourse. I put nether wart and blaze powder at the correct position. But I still get water bottle.

**Comment by Xhuge1** [comment]
> Do you put the ingredients at the top? and blaze powder too?

https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/assets/162018150/9be7ffff-c0eb-4d9b-8ec5-e681b62bd054

There is a video about the situation.
