### ISSUE TITLE
[1.20.1] Add blacklist function for mob_imprisonment_tool 

### ISSUE THREAD

**Issue by BazZziliuS** [InnovativeOnlineIndustries/Industrial-Foregoing#1415]
Please add a blacklist function for mob_imprisonment_tool 
This feature is needed so that bosses or other mobs cannot be used to capture and in the auto-spawner

**Comment by Buuz135** [comment]
It already exists, you can add entity types to the tag "industrialforegoing:mob_imprisonment_tool_blacklist"
