### ISSUE TITLE
[1.20] mob donkey with chest dupes items when in mob capture tool

### ISSUE THREAD

**Issue by GlauberBlox** [InnovativeOnlineIndustries/Industrial-Foregoing#1421]
there is a machine that dupes mobs and it also dupes donkeys with chest lol, just found out in a video of a big youtuber
https://youtu.be/FsclvSVqtZo?si=aWOn1jnhcmk8YKOQ

**Comment by GlauberBlox** [comment]
btw, at the video, start by here: 4:44

**Comment by Buuz135** [comment]
This person has enabled "Exact Copy" in the config which is disabled by default for that exact reason. Without that config enabled it doesn't duplicate anything.
