### ISSUE TITLE
[1.20.1] Washing factory not accepting item input

### ISSUE THREAD

**Issue by millennIumAMbiguity** [InnovativeOnlineIndustries/Industrial-Foregoing#1422]
**Industrial Foregoing Version:** 3.5.16
**Titanium Version:** 3.8.27

I have tested it with only Industrial Foregoing and JEI.

The Washing factory does not accept items tried with the UI and a hopper.

![image](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/assets/37588844/0ef0743d-8a40-4e63-8b3a-0ab682443563)
![image](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/assets/37588844/6e48e891-688d-42ae-9419-770055327bd8)

**Comment by Buuz135** [comment]
Does the iron have a dust?

**Comment by millennIumAMbiguity** [comment]
> Does the iron have a dust?

![image](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/assets/37588844/b9d27cfa-2296-4ee2-aace-2e634ce6f5f2)

**Comment by Buuz135** [comment]
You need to have a dust version of the ore for it work
