### ISSUE TITLE
[1.20] Material Stonework Factory causes a lot of lag with time

### ISSUE THREAD

**Issue by john13210** [InnovativeOnlineIndustries/Industrial-Foregoing#1436]
Friend told me that this could be like a ran time bug
the longer the stonework is placed the more lag it can cause
the stonework doesnt need to do anything
it just needs to have some items made inside it
i have 1 on the server causing 17737 ms/t

**Industrial Foregoing Version:**
1.20.1-3.5.16.jar
**Titanium Version:**
1.20.1-3.8.27.jar

if you need more info just ask
will watch this report for some time

**Comment by Buuz135** [comment]
I would need a spark report as "17737ms/t" is kinda useless

**Comment by john13210** [comment]
will do when i find another one like that
