### ISSUE TITLE
[1.20] Addon Range Tier isn't applicable if gived with command

### ISSUE THREAD

**Issue by Colluttorio** [InnovativeOnlineIndustries/Industrial-Foregoing#1446]
The issue that i have found appear if you have a world with cheat enabled and try to launch this command:

/give PlayerName industrialforegoing:range_addonX (where X is any number admissible)

the range_addon that you got, isn't applicable to plant sower and gather (maybe also the other machines but i haven't tried)
Just crafted addon work

**Industrial Foregoing Version:**
industrial-foregoing-1.20.1-3.5.17.jar

**Titanium Version:**

**Crashlog If Applicable (Upload to pastebin/gist):**
No crash

Forge version: 47.3.1
Minecraft version: 120.1

**Comment by Buuz135** [comment]
Addons have NBT, get it from JEI, craft it or add the proper NBT to it.
