### ISSUE TITLE
[1.20] Mob Slaughter Factory meat production lost zeroes?

### ISSUE THREAD

**Issue by uhloin** [InnovativeOnlineIndustries/Industrial-Foregoing#1448]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

Chicken in Mob Slaughter Factory generates 80 mB Pink Slime, but only 4 mB Liquid Meat. Should be 400 mB, because Washing Factory requires 100 mB LM per ore piece, or currently 25 chickens per ore piece. 

**Industrial Foregoing Version:**
industrial-foregoing-1.20.1-3.5.19.jar 
**Titanium Version:**
titanium-1.20.1-3.8.32.jar 

**Crashlog If Applicable (Upload to pastebin/gist):**

**Comment by Buuz135** [comment]
Passive mobs generate more pink slime and less meat and non passive ones generate more meat and less slime. The numbers are correct

**Comment by uhloin** [comment]
Then that washing factory is useless without huge creeper/zombie/skeleton farm. Am I right?

**Comment by Buuz135** [comment]
Industrial Foregoing gives you plenty of tools to make mobfarms of any size

**Comment by uhloin** [comment]
OK, thank you for the hint. I will experiment... may be create essence with passive mobs, then create zombies from essence and convert them to meat.

**Comment by wrincewind** [comment]
I'd recommend looking into Mechanical Dirt - it uses small amounts of power (and liquid meat?) to produce mobs quite quickly, and this can be boosted with the various upgrades.

**Comment by uhloin** [comment]
Mechanical Dirt does not work at all
