### ISSUE TITLE
[1.20] GregTech energy incompatibility

### ISSUE THREAD

**Issue by xHyroM** [InnovativeOnlineIndustries/Industrial-Foregoing#1449]
**Industrial Foregoing Version:**
1.20.1-3.5.19

**Titanium Version:**
1.20.1-3.8.32

**Description**
You can't power industrial foregoing machines with GTM energy. GTM energy works perfectly with Thermal Foundation or Ad Astra machines so I think it's issue on IF side.

**Workarounds**
Use Thermal Foundation's Redstone Cell as power connector

**Relations?**
https://github.com/GregTechCEu/GregTech-Modern/issues/1404

**Comment by Buuz135** [comment]
It's not a IF issue, it uses Forge Energy that is the standard, Thermal uses Redstone Flux and converts it to FE
