### ISSUE TITLE
[1.20] Mechanical Dirt doesn't work or useless

### ISSUE THREAD

**Issue by uhloin** [InnovativeOnlineIndustries/Industrial-Foregoing#1450]
**Industrial Foregoing Version:**
1.20.1-3.5.19

**Titanium Version:**
1.20.1-3.8.32

The configuration is 12x12 square with Slaughter Factory on the edge with emerald range addon. At night there are some mobs spawning with usual rate and killed by factory. If turn factory off and turn on this Mechanical Dirt block, then during whole night 1-2 mobs spawn on the block. May be the problem is number of hostile mobs underground, like with normal spawning.
But if I need to create a huge buildings like this -
https://www.youtube.com/watch?app=desktop&v=30JWnYnduH0
- then Mechanical Dirt block has zero sense, such a farm works well without any mods.

Mechanical Dirt block should not work like natural field spawning, but like a spawner with creation of mob on every cycle of progress bar. I found such old issue in this project, but it's closed, but the problem is still present or is re-created in 1.20.1.

**Comment by Buuz135** [comment]
Read the manual, it needs power, meat and be dark. Stop using github for support.

**Comment by uhloin** [comment]
Power and meat gauges are full, green gauge is moving and I waited whole night without any light sources. Also I tested different distance from player to dirt position.
