### ISSUE TITLE
[1.12] Dependency not listed on Curseforge

### ISSUE THREAD

**Issue by Moltresrider** [InnovativeOnlineIndustries/Industrial-Foregoing#1456]
Apparently it requires tesla core lib, but it does not list that as a dependency.

**Comment by Buuz135** [comment]
Check the dependencies in the files

![NVIDIA_Share_pjlMwv4oz2](https://github.com/user-attachments/assets/9aa7540d-ebe9-4fff-bf5b-52c567480cca)
