### ISSUE TITLE
[1.12] Issue Title Placement of the Laser drill in a particular direction is impossible

### ISSUE THREAD

**Issue by PillowMan123456789** [InnovativeOnlineIndustries/Industrial-Foregoing#1465]
This mod needs a wrench that can rotate in whatever direction you need. placing the laser drills is the most infuriating thing ive ever experienced in my entire life id rather hang myself by my foreskin than try and place this block. So heres the issue. YOU CAN NOT PLACE DOWN THE LASER DRILL SO THAT IT FACES THE DIRCTION YOU WANT. SUCH AS FORWARDS.
wan to replicate this? try and place a block in every which direction and i garuntee you will not be able to get it to rotate in 2 of the four directions. This is not the first time ive had this issue and trying to collect ether gas is the most painful thing in existence to do considering this issue. If i didnt need this mod for the atm star id outright delete it. PLEASE HELP

**Comment by Buuz135** [comment]
👋 Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.

**Comment by Spongman** [comment]
this still happens in 1.21. laser drill orientation is broken.
