### ISSUE TITLE
[1.21] crash with neoforge 1.21.1

### ISSUE THREAD

**Issue by VaporeonScripts** [InnovativeOnlineIndustries/Industrial-Foregoing#1470]
**Industrial Foregoing Version:**
latest
**Titanium Version:**
latest
**Crashlog If Applicable (Upload to pastebin/gist):**
https://mclo.gs/eWg0B5Q

**Comment by Buuz135** [comment]
Latest is not a version number, and you aren't even running latest, update your mods.

**Comment by VaporeonScripts** [comment]
I am running latest tho? Wym

**Comment by Buuz135** [comment]
You are running titanium-1.21-4.0.13 the latest in curseforge is titanium-1.21-4.0.21.jar which was released 6 days ago

**Comment by VaporeonScripts** [comment]
Didnt see that,ig I can update it
