### ISSUE TITLE
[1.21] Wither Builder Inconsistencies

### ISSUE THREAD

**Issue by leamir** [InnovativeOnlineIndustries/Industrial-Foregoing#1474]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
1.21-3.6.13 (Client & server)

**Titanium Version:**
4.0.21

**Modpack**
ATM 10 Version 0.56

**Crashlog If Applicable (Upload to pastebin/gist):**
I've been having problems for a while with Industrial Foregoing, will provide logs for a server crash on a older version (explanation why below)  [crash-2024-09-23_10.23.40-server.txt](https://gist.github.com/leamir/48d4552fba35e0a830be96c214e1ecd3)
No other logs were produced at all (both client & server)

This issue is possibly related to #1309 

For context, I run a dedicated server on my local network

My problem is that when a wither is being built, all soul sands are placed, but the skulls are not, and they stay in the builder

The crash log above is because, when I was first testing this bug (on the outdated version), the soul sands were placing, and when the skull was placed (woudn't always place - same problem as currently), it crashed the server. Updating the modpack server-side fixed the map crash, and the wither was spawned once I joined again.

I have not have a server crash involving the wither builder since updating

Edit: i've tried on both claimed and unclaimed areas (FTB Chunks), my team settings allow all fake players

**Comment by MuteTiefling** [comment]
I'm encountering this as well. 
IF 1.21-3.6.13
Titanium 4.0.21

![2024-09-29_00 37 32](https://github.com/user-attachments/assets/1e208476-520f-4f5a-8acd-fa46f6d1fd0c)
![2024-09-29_00 37 38](https://github.com/user-attachments/assets/f7161b6d-7bfb-486e-90c0-5b2c8d743d1b)

**Comment by spocane** [comment]
ATM10 v1.9
Just experienced this as well. Works fine in the overworld, but not other dimensions.

When i tried in the end i was able to see that it was placing the skulls in the corresponding coords in the overworld.
