### ISSUE TITLE
[1.21] Resourceful Furnace won't push unless it can't pull

### ISSUE THREAD

**Issue by MuteTiefling** [InnovativeOnlineIndustries/Industrial-Foregoing#1475]
The furnace only appears to be able to do one action at a time. It either pulls an item, or pushes the result. Never both. This results in the machine needing to fill completely before it'll push an item. In the screenshot below, for example, it was keeping itself full of meat to cook, but wouldn't push the results till all output slots were 100% full. then it pushed enough to smelt again.

Overall this reduces the speed of the furnace considerably since it's stopping and starting instead of smelting continuously. 

**Industrial Foregoing Version:**
![image](https://github.com/user-attachments/assets/31f6300b-5a12-4208-911a-beb999d7a7cd)

**Titanium Version:**
![image](https://github.com/user-attachments/assets/b6ed121a-9980-4bfe-a915-c27c17f5d778)

**Crashlog If Applicable (Upload to pastebin/gist):**

![image](https://github.com/user-attachments/assets/26cba1cf-e8dc-49d4-b294-5741d05a155c)

**Comment by Kanzaji** [comment]
Additional context: It appears that the furnace won't push if the slot it tries to push to can't handle more items - even if there are different slots available. Example: Chest on top -> First slot fills up, furnace won't push any more items.
