### ISSUE TITLE
[1.21] Plant Sower isnt working with netherwart

### ISSUE THREAD

**Issue by Saereth** [InnovativeOnlineIndustries/Industrial-Foregoing#1477]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
industrialforegoing-1.21-3.6.13.jar

**Titanium Version:**
titanium-1.21-4.0.21.jar

**Crashlog If Applicable (Upload to pastebin/gist):**
Not crashing

setting up a netwart farm doesnt seem to be working, here is a screenshot of my setup, creative energy on the bottom, range upgrade, nether wart in the ui
<img width="1580" alt="image" src="https://github.com/user-attachments/assets/c98cf04d-6525-4ff5-9744-ca0a401afe3a">
<img width="476" alt="image" src="https://github.com/user-attachments/assets/da8b7ff2-a870-422e-96f5-4b79e4cc26d5">

The area is not claimed or anything that would prevent interactions

**Comment by Mike-057** [comment]
Try Hydroponic Grow Bed :)
