### ISSUE TITLE
[1.21] Potion brewer causes game to exit upon adding ingredients after netherwart

### ISSUE THREAD

**Issue by AntonLM** [InnovativeOnlineIndustries/Industrial-Foregoing#1479]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
3.6.13
**Titanium Version:**
Don't know what that is, sorry.
**Crashlog If Applicable (Upload to pastebin/gist):**
https://pastebin.com/iQQvcDzu

**Comment by wcream3** [comment]
When the potion brewer attempts to brew only 1 potion, it crashes. Brewing 2 or 3 potions at a time has not produced the crash, but brewing one potion results in a crash every time. A temporary solution for players is to ensure the amount of empty bottles they have in the potion brewer is always divisible by 3. 

Cheers
