### ISSUE TITLE
[1.21] Can't put Addons in machines

### ISSUE THREAD

**Issue by Firefly0402** [InnovativeOnlineIndustries/Industrial-Foregoing#1493]
**Industrial Foregoing Version: 3.6.15**

**Titanium Version: Sorry I'm noob and don't know that :(**

**Crashlog If Applicable (Upload to pastebin/gist):**

I tried with mob crusher and mob slaughter factory and can't put any range/speed addons into the addon-slots. Tried it with different Tiers too. In case that info helps I'm playing minecraft version 1.21.1 with the modpack craftoria 1.5.0

**Comment by Buuz135** [comment]
Did you cheat the items in? You need to craft them or get them from the creative menu

**Comment by Firefly0402** [comment]
Yes I did. Didn't think that would matter. Thank you very much :)
