### ISSUE TITLE
[1.21] Issue Title

### ISSUE THREAD

**Issue by Nobodycare233** [InnovativeOnlineIndustries/Industrial-Foregoing#1503]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:*1.21-3.6.15*

**Titanium Version:*4.0.21*

**Crashlog If Applicable (Upload to pastebin/gist):**
seeder does not plant(only plant berry,but potatoes and carrots and wheat not plant)

**Comment by Nobodycare233** [comment]
![2024-10-21_18 18 33](https://github.com/user-attachments/assets/40826b5d-9fd2-4bae-bc4d-b3150ec29fcd)
![2024-10-21_18 18 36](https://github.com/user-attachments/assets/ff35a628-4847-4774-83e1-4c50935951e2)
![2024-10-21_18 18 39](https://github.com/user-attachments/assets/4b235d83-c15e-4132-abd2-cb90beba33bd)
this does not plant,only plant berry,fix it quickly!!!

**Comment by Buuz135** [comment]
It works for me, using dirt and Hydroponic beds
