### ISSUE TITLE
[1.16] Villagers Trade Enchanger There is no craftable in 1.16.5

### ISSUE THREAD

**Issue by CleberBR11111111** [InnovativeOnlineIndustries/Industrial-Foregoing#1506]
I'm playing with some mods on 1.16.5 and I can't make the automatic trade machine with villagers because it doesn't appear to me, I wanted to make an automatic EMC factory using it.

I'm using the latest mod update for 1.16.5

**Comment by Buuz135** [comment]
It doesnt exist in 1.16.5
