### ISSUE TITLE
[1.21] Pink slime balls show up as ingots

### ISSUE THREAD

**Issue by jstansel** [InnovativeOnlineIndustries/Industrial-Foregoing#1520]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:** 3.6.21

**Titanium Version:** 4.0.30

**Crashlog If Applicable (Upload to pastebin/gist):** N/A

With the new release, pink slime balls now have the c:ingots and c:ingots/pink_slime tags.

**Comment by TheBedrockMaster** [comment]
I said add them to pink slime _ingots_ 😅
