### ISSUE TITLE
[1.21] Potion Brewer

### ISSUE THREAD

**Issue by Kiriao** [InnovativeOnlineIndustries/Industrial-Foregoing#1527]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
[industrialforegoing-1.21-3.6.21.jar](https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing/files/5951082)

**Titanium Version:**
[titanium-1.21-4.0.30.jar](https://www.curseforge.com/minecraft/mc-mods/titanium/files/5897690)

**Crashlog If Applicable (Upload to pastebin/gist):**
i was trying to automate potion brewer by using AE2 in ATM10 but i found out that after the potion is done brewing it not importing back to the system nor the modular router able to pull from the it.

Here is the machine
![Screenshot 2024-12-26 200903](https://github.com/user-attachments/assets/b39c7bb9-908b-4cce-9af0-65fa54206865)
![Screenshot 2024-12-26 200953](https://github.com/user-attachments/assets/522ca221-dd07-4e19-9443-7b250da3bf93)

**Comment by Buuz135** [comment]
You need to put what you want to extract in the green slot as a filter

**Comment by Kiriao** [comment]
I did that can but still cannot

**Comment by Buuz135** [comment]
Yes
