### ISSUE TITLE
[1.21] Potion Brewer not exporting

### ISSUE THREAD

**Issue by PolluxZ32** [InnovativeOnlineIndustries/Industrial-Foregoing#1528]
The potion brewer in industrial foregoing isn't outputting items even when it is set to push from a side where there was either an ME import bus, pipez pipe, mekanism filter pipe etc, no matter what I try it does not push the potions out.

**Comment by Buuz135** [comment]
Put the potion you want to export in the green slot of the machine, to allow it to extract.
