### ISSUE TITLE
Setting the Sides of Black Hole Units / Controller Does Not Prevent Input / Extraction from Hoppers

### ISSUE THREAD

**Issue by superfluke** [InnovativeOnlineIndustries/Industrial-Foregoing#309]
Setting the input/output sides of the black hole units and black hole controller to disabled does not prevent the hopper from inputting/extracting items from the disabled side.

Industrial Foregoing Version: industrialforegoing-1.12.2-1.8.10-143
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.12
Crashlog (If Any): n/a

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
