### ISSUE TITLE
Cant plant/farm with"Natura mod"

### ISSUE THREAD

**Issue by seathasky** [InnovativeOnlineIndustries/Industrial-Foregoing#380]
**Industrial Foregoing Version:**  Latest 1.12.2
**Natura Mod Versions:** natura-1.12.2-4.3.2.49
**TeslaCoreLib Version:**  Tesla-1.12.2-1.0.63
**Crashlog (If Any):** N/A

Wanting to farm Natura plants, have "Blood Sapling (Natura)" planted, but the IF Sower and Plant Gatherer do not interact with it.  The Bloodwood tree does grow upside down, not sure if that has any effect! Thanks in advance. Here are some images to help you. https://imgur.com/a/rChrtnR

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
