### ISSUE TITLE
resourceful furnace stops producing essence

### ISSUE THREAD

**Issue by c0mical** [InnovativeOnlineIndustries/Industrial-Foregoing#408]
Industrial Foregoing Version: 1.10.4-187 (FTB Continuum 1.4.1)
TeslaCoreLib Version: 1.0.15
Crashlog (If Any):  N/A

Hi

I'm not sure how to recreate it it, but I've at a certain point the resourceful furnace stops producing essence. it still smelts as expected just no essence

unfortunately it is on a minecraft server network so I have no access to any console logs

breaking and replacing it does not seem to get it working as expected again

**Comment by c0mical** [comment]
after a bit more testing, it has just stopped producing essence when used for smelting iron, any other material still produces essence

**Comment by Buuz135** [comment]
Does this happen in Singleplayer or multiplayer ?

**Comment by c0mical** [comment]
it was multiplayer, I havent been able to test it again after a server restart though

**Comment by c0mical** [comment]
Hi,

the original material (pulverised iron) is working again now, however the material that I had swapped it onto (pulverised gold) has stopped working now

**Comment by 28lachie** [comment]
I have the same issue on 1.12.2 but i'm told changing out the ore to a different thing usually fixes it for awhile. I don't know if this is coded into it because I haven't got time to check but would be good to know

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
