### ISSUE TITLE
Wither Builder "Active on Redstone Signal" doesn't build on redstone pulse

### ISSUE THREAD

**Issue by infogulch** [InnovativeOnlineIndustries/Industrial-Foregoing#418]
I built an automated wither killing system and set it up to send a redstone pulse to the Wither Builder (with "Active on Redstone Signal" enabled, of course) to build a new wither when the previous wither died, based on picking up the previous wither's drops. This usually didn't work, but it did work every once in a while.

After two hours of trying to figure out why it only worked some of the time I finally noticed that the 500RF Work Energy Buffer itself only fills up while a redstone signal is supplied. The redstone signal doesn't activate the machine, the redstone signal allows the buffer to fill up.

This means that if someone wants to build a wither on demand they must send a redstone signal for *precicely* as many ticks as it takes to fill up the energy buffer. And if you use speed or energy upgrades it may not even be possible if the energy consumption (affected by upgrades) does not evenly divide into a number of ticks controllable by redstone.

Instead, I think the buffer should always fill up, regardless of any redstone signal or setting, and if the "Active on Redstone Signal" option is enabled the machine waits to build the wither until a redstone signal is supplied.

Industrial Foregoing Version: 1.10.3
TeslaCoreLib Version: 1.0.15

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
