### ISSUE TITLE
[1.12.2] [Request] More Ingredients in Recipes to Ore Dictionary

### ISSUE THREAD

**Issue by Skaphegor** [InnovativeOnlineIndustries/Industrial-Foregoing#433]
I would like to request if you can oredict stone in all recipes that contains it. I have UB installed and many different kinds of stone but they cannot be used for IF. And it would also be useful if itemRubber  would be oredicted in the recipes so you can use rubber vom IC2 or Tech Reborn also.

**Comment by NickelHub** [comment]
See https://github.com/Buuz135/Industrial-Foregoing/pull/434

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
