### ISSUE TITLE
Black Hole Unit doesn't accept all items from the ME Storage Bus

### ISSUE THREAD

**Issue by dav20011** [InnovativeOnlineIndustries/Industrial-Foregoing#468]
Industrial Foregoing Version: 1.11.9-222
TeslaCoreLib Version: 1.0.15.13

If I try to insert items via ME IO Port (fully upgraded) -> ME Storage Bus -> Black Hole Unit only 1/16 of the items are being transferred to the BHU. The rest is stored in other available storage options because AE wasn't able to insert it into the BHU. This should not be related to AE because the Quantum Storage Unit and other blocks work fine.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
