### ISSUE TITLE
Enchantment factory never produces Projectile Protection

### ISSUE THREAD

**Issue by LuciusV** [InnovativeOnlineIndustries/Industrial-Foregoing#489]
Industrial Foregoing Version: 1.12.2-1.12.4-228
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): 

During they play I noticed that enchantment factory never produces Projectile Protection. After I saw it I made test world and enchanted 81 pieces of armor in enchantment factory. Resulting protection enchantments are:
Protection  37
Blast Protection 6
Fire Protection 18
Projectile Protection = 0 (!!)

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
