### ISSUE TITLE
[Request] Config option for Infinity Drill Effects

### ISSUE THREAD

**Issue by Rsslone** [InnovativeOnlineIndustries/Industrial-Foregoing#495]
Industrial Foregoing Version:  industrialforegoing-1.12.2-1.12.4-228
TeslaCoreLib Version:  tesla-core-lib-1.12.2-1.0.15
Crashlog (If Any):  n/a

I wrote in a closed thread, I thought I'd make a thread of its own for completeness and in case my suggestion went unseen.

I'd like to suggest if the drill won't ever have a disable option, to at least have some sort of config to disable the effects added. In my opinion it's both confusing and how the effect is not shaded, it breaks immersion.

Thanks for all your hard work!

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
