### ISSUE TITLE
Infinity Drill vanishing

### ISSUE THREAD

**Issue by bradley21** [InnovativeOnlineIndustries/Industrial-Foregoing#500]
Modpack: E2E Skyblock
Industrial Foregoing Version: 1.12.4
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): 

Have tried to create four Infinity drills.  Two vanished after trying to fill with Biofuel, vanished from machine after reaching capacity.  Two vanished on reaching max energy capacity (Filled with tons of energy...and they were suddenly gone...)

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
