### ISSUE TITLE
[Request] Range Addon: Show working AOE in machine before crafting

### ISSUE THREAD

**Issue by rebio** [InnovativeOnlineIndustries/Industrial-Foregoing#505]
Right now I have to craft the range addon and put it into the machine to >see< the working AOE.

Can we please have a button inside machines that shows the working AOE of the different tiers before I craft a range addon? the use would be that I can select the right range addon right away and don't have to craft the wrong one which's area is too small/large before I get the right one.

Side quest: A range addon with custom range for all directions would be nice :D

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
