### ISSUE TITLE
Industrial-Foregoing: Wither Builder placing Regular Skulls instead of the provided Wither Skull.

### ISSUE THREAD

**Issue by Noogies123** [InnovativeOnlineIndustries/Industrial-Foregoing#523]
I already reported this bug once, but it was closed without any comment whatsoever.

Please elaborate as to why my reported issue is being ignored?

I'm taking time reporting something that I could just ignore.  Please treat your user base with a little dignity.  If this is a known bug, then say so.  If it's a config issue, then say that.   Don't just close it with no comment.

Noogies.

**Comment by Buuz135** [comment]
You opened 4 issues with 0 description and without filling the required information, what do you expect? Add that the comment you made in one of them to this one.

**Comment by Noogies123** [comment]
I included the Version information.   There was no crash, so I had nothing to provide for that,   and I tried to be as descriptive of the problem as I could.    I didn't open 4 issues.  I opened just 1 issue.   What are the other three?

Noogies123.

**Comment by Buuz135** [comment]
This four ones? With no description in any of them. https://imgur.com/a/VCCCS3d

**Comment by Noogies123** [comment]
I'm not sure how that happened.   It was not intentional.   I may have clicked someplace and accidentally posted.   Haven't you ever accidentally posted something more than once?

Can we start again?    I would like to report a potential bug in the Wither Builder.   Please see my closed descriptive post from 40 minutes ago.   Please ignore the blank ones, i am 60 yrs old, and occasionally click more often than I intend to.

Noogies123

**Comment by Noogies123** [comment]
You mentioned that all 4 of the posts were blank.   #519, #520, #521 and #522,  Yet #522 was the one that I entered all the required version info, and my description.   I think that if you saw it as a blank post, that maybe you were seeing cached info from your browser rather than my post.   When I hit the submit button on it for the first time, it had all the text that you see minus the screenshot at the bottom (I added that later)     

Can you maybe re-open #522, and close this one #523 ?

Regards
Noogies123

**Comment by Noogies123** [comment]
I have updated #522.  Please close #533 (this thread) and re-open #522.   Thanks.

Noogies123

**Comment by AntonioToni** [comment]
Issue still present.
industrialforegoing-1.12.2-1.12.12-236
tesla-core-lib-1.12.2-1.0.15

**Comment by Prasodym** [comment]
Hello, With me the problem was also recorded in git that this does not run normally.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
