### ISSUE TITLE
[Bug/Feature request] Black Hole Tank does not accept empty buckets

### ISSUE THREAD

**Issue by calloatti** [InnovativeOnlineIndustries/Industrial-Foregoing#524]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.7-231
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15
Crashlog (If Any): 

The black hole tank does not accept empty buckets piped in or clicked in. 

Unable to pipe empty buckets to a black hole tank with lava so I can get a bucket with lava as output.

Full buckets can be clicked in and an empty bucket is returned, as expected.

This would be a nice thing to have so we can use a Refined Storage crafter pointed to the tank with an empty-bucket to full bucket recipe since RS does not fill buckets automatically anymore.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
