### ISSUE TITLE
[Feature Request] Craft tweaker support for spores recreator

### ISSUE THREAD

**Issue by FeedCat02** [InnovativeOnlineIndustries/Industrial-Foregoing#533]
Would be nice to be able to add mushrooms like nuclear craft glowing mushrooms or pam's white mushrooms to the recipe list

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
