### ISSUE TITLE
Plant Sower Bug - plants saplings on wrong blocks

### ISSUE THREAD

**Issue by Whimsy85** [InnovativeOnlineIndustries/Industrial-Foregoing#534]
Industrial Foregoing Version: 1.12.2-1.12.8-232
TeslaCoreLib Version: 1.12.2-1.0.15
Forge: 14.23.5.2820
Crashlog (If Any): non

Plant Sower plants saplings on wrong blocks.

https://pasteboard.co/I6g2vtt.png

**Comment by selli69** [comment]
Have the same issue

Industrial Foregoing Version: 1.12.2-1.12.8
TeslaCoreLib Version: 1.12.2-1.0.15

Plant sower plant on saplings and stone, additionally one level deeper.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
