### ISSUE TITLE
Bioreactor Recipes

### ISSUE THREAD

**Issue by HurtsAsHell** [InnovativeOnlineIndustries/Industrial-Foregoing#550]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.11-235
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15

The input recipe is empty and i don't know what item* is it, i think it's a bug.

![Screen](https://user-images.githubusercontent.com/37914234/55687404-f0a20200-596c-11e9-95ad-bc6aea010c71.PNG)

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
