### ISSUE TITLE
Additional Configs?

### ISSUE THREAD

**Issue by ghost** [InnovativeOnlineIndustries/Industrial-Foregoing#552]
Industrial Foregoing Version: 1.12.5-229
TeslaCoreLib Version: 1.0.1.5
Crashlog (If Any): N/A

Hello all,
So i was looking into the configs for the machines in this mod, and didn't find any. It would be great to have a config for the speed of the machines.
Thanks!

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
