### ISSUE TITLE
[Suggestion] Make MobImprisonmentTool blacklist

### ISSUE THREAD

**Issue by evernife** [InnovativeOnlineIndustries/Industrial-Foregoing#559]
I need a blacklist for this tool, as some mobs that are not meant to being moved are being moved T.T

https://github.com/Buuz135/Industrial-Foregoing/blob/361924f04fd4704182168a8bfab09b8da34f74e6/src/main/java/com/buuz135/industrial/item/MobImprisonmentToolItem.java#L76

https://github.com/Buuz135/Industrial-Foregoing/blob/361924f04fd4704182168a8bfab09b8da34f74e6/src/main/java/com/buuz135/industrial/item/MobImprisonmentToolItem.java#L89-L91

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.

**Comment by evernife** [comment]
Sure.

Anyone needing a fix for this can take a look at this source.

https://github.com/CrucibleMC/Grimoire-Mixins-1.12.2/blob/master/Mixin-IndustrialForegoing/src/main/java/io/github/crucible/grimoire/mixins/industrialforegoing/MixinMobImprisonmentToolItem.java
