### ISSUE TITLE
[SUGGESTION] Full Auto-Anvil

### ISSUE THREAD

**Issue by TomShkurti** [InnovativeOnlineIndustries/Industrial-Foregoing#561]
Industrial Foregoing Version: Any
TeslaCoreLib Version: Any
Crashlog (If Any): N/A

A while back as a small 1.7.10 test mod I made a 'full' auto-anvil machine with the ability to rename items and repair them as well as applying and combining enchantments. I was planning to upgrade and release this as an add-on for IF in 1.12, but was wondering if instead people would be interested in this just becoming a part of regular IF in place of the Enchantment Applicator?

A full breakdown of the machine's behavior is as follows:

- Emulation of all conventional anvil functions including combining enchantments on books and weapons, repairing items, and renaming.
- In place of player levels, consumed Essence as defined by a table in the configuration file going up to Level 30. Will likely change this to a flat multiplier for Essence per level, as well as a similar multiplier for consuming power.
- Had an additional slot which would only accept vanilla anvils, and required one to be present for the machine to work. Every operation had a chance to increase the damage on the anvil and eventually destroy it. This chance was adjustable by a config value.
- There were also config values determining whether to:
     - apply the 'prior work' effect to items worked in the device.
     - add incompatible enchantments when combining enchantments
     - add enchantments not normally applicable to the item
     - rename for free

**Comment by edotenseilove** [comment]
That would be great because there are not many full auto anvil mods

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
