### ISSUE TITLE
Cannot Switch Modes of Infinity Drill with Shaders on

### ISSUE THREAD

**Issue by sabromex** [InnovativeOnlineIndustries/Industrial-Foregoing#563]
Industrial Foregoing Version: Whatever's in the most recent FTB Ultimate Reloaded
TeslaCoreLib Version: ^
Crashlog (If Any): N/A

Optifine, without shaders, the drill works great. But,
Can't switch area size while using shaders.
Also don't have the option to change the hotkey for area size.
Also the drill looks giant with shaders when held in hand, using any shader pack.
By comparison, Gravisuite chest plate, the hotkey works for the hover mode to change modes.
Other mods work when changing modes with shaders on.
Thinking this is a bug or not yet implemented. Hope you can spare a little time to make a fix!
Anyway, thank you for the mod, it's very fun!

**Comment by billbertking1** [comment]
Dropping by to add that it still happens in 1.12.2-1.9 - same pack as well.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
