### ISSUE TITLE
[Suggestion] Make Plant Gatherer accept Fortune

### ISSUE THREAD

**Issue by ReillyBrogan** [InnovativeOnlineIndustries/Industrial-Foregoing#564]
Industrial Foregoing Version: 1.12.11-235

In vanilla the fortune enchantment applies to crop drops. Can you add support for the Fortune Addon to the Plant Gatherer such that we can use this mechanic for our farms?

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.

**Comment by ReillyBrogan** [comment]
@Buuz135 This feature request is still valid against 1.16 as that version doesn't have it either. Can we reopen this?
