### ISSUE TITLE
Water Condensator does not accept fluid pushing upgrade

### ISSUE THREAD

**Issue by M3wM3w** [InnovativeOnlineIndustries/Industrial-Foregoing#565]
Water Condensator does not accept the fluid pushing upgrade, but it displays slots for upgrades.

Industrial Foregoing Version: 
industrialforegoing-1.12.2-1.12.11-235.jar

TeslaCoreLib Version: 
tesla-core-lib-1.12.2-1.0.15.jar

**Comment by ShadowNinja237** [comment]
I have the same problem

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
