### ISSUE TITLE
[Suggestion] Make Fluid Crafter work without fluids too

### ISSUE THREAD

**Issue by oliveanimone907** [InnovativeOnlineIndustries/Industrial-Foregoing#566]
Industrial Foregoing Version: 1.12.11-235
TeslaCoreLib Version: 1.0.15

I really love the feature of the fluid crafter that you can/have to lock the items for it to actually craft. I however can't find anything similar for crafting without fluids and was surprised that I could not find a crafter or similar machine in Industrial Foregoing. Would it be possible to enable crafting of recipes without fluids in the fluid crafter or possibly create a different machine that simply craftes regular recipes? Possilby toggle this via configs?

All other crafting machines I can find in other mods tend to get clogged if they require more than one item as one would at some point in time fill the entire inventory preventing the other item from being inserted.

Generally just wanted to give you a heads up as I really love this mod and would never want to play a technical modpack without it as it greatly improves automation :+1:!

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
