### ISSUE TITLE
Performance Issue Industrialforegoing/TeslaLib

### ISSUE THREAD

**Issue by Shybella** [InnovativeOnlineIndustries/Industrial-Foregoing#569]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.11-235
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15
Crashlog (If Any): none

Reports 

https://timings.aikar.co/?id=cb97773f23634a06b561c99a46df8adf
https://sparkprofiler.github.io/?s221McLvlY

VisualVM NPS: https://drive.google.com/open?id=1eus0nOFrcY791rgFZ8e3FDp3SkC54mNy

This also occurs pretty bad on the Petrified Generators. Could be related to Thermal Dynamics conduits and tesla/industrial foregoing integration? I am also having hits from TD, there has also been reports of tick issues on cofh github in relation to industrialforegoing machines. I am working on narrowing this down.

https://github.com/CoFH/Feedback/issues/961

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
