### ISSUE TITLE
Block Placer placing mob heads one block lower.

### ISSUE THREAD

**Issue by nyuuns2** [InnovativeOnlineIndustries/Industrial-Foregoing#574]
Industrial Foregoing Version: 1.12.2 - 1.12.12.236
TeslaCoreLib Version: 1.12.2 - 1.0.15
Crashlog (If Any): 
![Screenshot](https://user-images.githubusercontent.com/30362256/59076279-44649500-88a3-11e9-8822-382a95a08ca7.jpg)
In the left one I have placed a mob head first then a block, on the others just a head.
It's a minor issue but still an issue. They are also placed facing north.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
