### ISSUE TITLE
Laser Drill beam causes black diagonal random block outline

### ISSUE THREAD

**Issue by Donutfreak** [InnovativeOnlineIndustries/Industrial-Foregoing#575]
Turning on the laser drill causes a diagonal black block outline on some random blocks. Outline isn't everywhere, it seems to only be visible when player is facing north or west and only shows on the south and east parts of the block. Being far away from the drill makes the issue go away.

A video of the wireframe while the laser is on: https://streamable.com/7htlj

FTB Ultimate Reloaded 1.7.1, Minecraft 1.12.2, Tinkers' Construct added
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.12-236
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15
Crashlog (If Any): N/A
![2019-06-24_18 24 40](https://user-images.githubusercontent.com/3360326/60062371-ce876880-96ad-11e9-96f7-076b3bdcacfe.png)
![2019-06-24_18 24 49](https://user-images.githubusercontent.com/3360326/60062372-ce876880-96ad-11e9-9def-f54cfbb6a47d.png)

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
