### ISSUE TITLE
The Black Hole Tank should be grouped with the other Black Hole blocks in the book instead of having the Dye Mixer in the way

### ISSUE THREAD

**Issue by aaronhowser1** [InnovativeOnlineIndustries/Industrial-Foregoing#590]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.13-237
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15
![image](https://user-images.githubusercontent.com/15698722/61823569-a82a2980-ae21-11e9-978d-393962f54b53.png)

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/103265768-faa33a00-4973-11eb-99ec-33e681a5c712.png)
👀
