### ISSUE TITLE
Exacy copy doesn't work correctly

### ISSUE THREAD

**Issue by vmsh0** [InnovativeOnlineIndustries/Industrial-Foregoing#591]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.11-235.jar
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15.jar
Crashlog (If Any): 

Hello,

Exacy copy is enabled both in the config and in the Duplicator. When I duplicate mobs (e.g. Zombie Villagers) some tags are duplicated (e.g. armor), others are not (e.g. profession, CanPickUpLoot, etc...).

I don't really know how to provide further info, but I'd be glad to do so if instructed.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
