### ISSUE TITLE
Black Hole unit/controller duping interaction

### ISSUE THREAD

**Issue by Yamza** [InnovativeOnlineIndustries/Industrial-Foregoing#593]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.13-237
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15
Crashlog (If Any): 

https://gyazo.com/44b5d7bcababc3b5689fb1505c3e4165

Have the tank or unit next to an import device, AA liquid laser, itemduct from Thermal  or a mek item or liquid pipe, then use a cyclic sack of holding or moving wand on it, and it will pick up the original, and drop a dupe that is empty.
Can also be an AE bus or rs bus.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
