### ISSUE TITLE
Plant Sower, Plant Gatherer doesn't function when chunk loaded

### ISSUE THREAD

**Issue by Locomotivers** [InnovativeOnlineIndustries/Industrial-Foregoing#594]
I usually keep chunk load my area in my server. I noticed when I log out and come back a few hours later, the bottom portion of tree trunk collected and rest of tree left still leftover world. 

I also used Railcraft worldspike and E.U2 chunk loading ward.

Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.12-236
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15
Crashlog (If Any): -

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
