### ISSUE TITLE
Fluid pump, no output when replaceFluidWithCobble=false

### ISSUE THREAD

**Issue by Twisted6** [InnovativeOnlineIndustries/Industrial-Foregoing#596]
Industrial Foregoing Version: 1.12.2-1.12.13-237
TeslaCoreLib Version: 1.12.2-1.0.15

The fluid pump doesn't generate any fluid but still deletes fluid sources and consumes power when replaceFluidWithCobble=false.

**Comment by Zhang-Wei-666** [comment]
+1

**Comment by Spongman** [comment]
sometimes it doesn't output fluid even when replaceFluidWithCobble is true.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
