### ISSUE TITLE
Plant interactor not picking up all crops

### ISSUE THREAD

**Issue by KKSERAI** [InnovativeOnlineIndustries/Industrial-Foregoing#601]
Industrial Foregoing Version: 1.12
TeslaCoreLib Version: 1.12

I'm growing strawberries from Pam's Harvescraft and whenever they are ready, the plant interactor only takes one of the two or three strawberries. How can I fix?

**Comment by binh3012** [comment]
I also have this problem with Cotton from Natura.

**Comment by Jack-McKalling** [comment]
I also have this problem with Mystical Agriculture 1.7.3 crops in Sky Factory 4.1.0.
It works to put some kind of hopper down to collect items, but the Plant Interactor _does_ collect some of these drops, just not all of them. So there are two item outputs in that setup but it should be just one. Either do pick up all or don't pick up any.

**Comment by MBfromOK** [comment]
I had this issue with the Rats mod on another modpack play through, they were programmed to break the crop and retrieve the normal drop (1:1) anything extra dropped on the ground...

Perhaps the Interactor could be coded to retrieve the crop name / ID before harvesting and then look for floating / dropped entities and vacuum, pickup / hoover them?

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
