### ISSUE TITLE
Animal Feeder not working

### ISSUE THREAD

**Issue by ActiveByte** [InnovativeOnlineIndustries/Industrial-Foregoing#602]
Industrial Foregoing Version: 1.12.2
TeslaCoreLib Version: 1.0.15
Crashlog (If Any): N/A

Animal feeder is not doing anything

**Comment by KKSERAI** [comment]
Is it powered?

**Comment by ActiveByte** [comment]
I checked and it was something with liteloaders just romoved it completely and its fixed now, lost one hour on finding the broken mod

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
