### ISSUE TITLE
[1.12] Plant gatherer gathers leaves much outsider than its working radius

### ISSUE THREAD

**Issue by Prunoideae** [InnovativeOnlineIndustries/Industrial-Foregoing#604]
**Industrial Foregoing Version: **
1.12.13
**TeslaCoreLib Version: **
1.0.15

**Crashlog If Applicable (Upload to pastebin/gist): **
It's a bug in functionality, as I'm living in Biomes O Plenty's coniferous forest, there are plenty of fir wood and I'm using a plant gatherer to make a small tree farm for myself.
But the machine only gathers leaves and after almost half an hour, I found my surrounding turned into this:
![image](https://user-images.githubusercontent.com/24620047/64476735-739de180-d1c5-11e9-8f2c-b574456eec08.png)
Is there any solution? Or I will have to use TE's tree planter instead...

**Comment by Prunoideae** [comment]
Then all the leaves was cut off, and it finally harvested all the logs, which make the wood became even more ugly...
![image](https://user-images.githubusercontent.com/24620047/64476853-a8f6ff00-d1c6-11e9-8766-0a7328a2bb02.png)
What happened?

**Comment by Water-Moon** [comment]
Right now, it seems that the only solution is to isolate this machine and its working area from the surroundings...

**Comment by ProsperCraft** [comment]
We have the same issue on my official TownCraft server-
industrialforegoing-1.12.2-1.12.13-237

This was in a roofed forrest with dark oak.

![2020-01-09_11 37 30](https://user-images.githubusercontent.com/4427684/72095361-8fc9a080-32d5-11ea-926b-8f17e7a0d52a.png)
![2020-01-09_11 37 39](https://user-images.githubusercontent.com/4427684/72095362-90623700-32d5-11ea-8d98-56803f6132ce.png)
![2020-01-09_11 37 48](https://user-images.githubusercontent.com/4427684/72095363-90623700-32d5-11ea-8ea3-b72474a0bb69.png)
![2020-01-09_11 38 10](https://user-images.githubusercontent.com/4427684/72095364-90623700-32d5-11ea-8a75-d5699373eedc.png)

**Comment by KollinsPlays** [comment]
I've had this too. Seem like the algorithm that looks for connected leaves needs to be a little less fuzzy in it's logic and maybe have a max range beyond it's harvest range it will check. Enough to pick up the leaves from say a large oak or a 2x2 jungle tree, but not try and clear a whole forest.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.

**Comment by Water-Moon** [comment]
OH NO :(
