### ISSUE TITLE
[Feature Request] Extra Alchemy Support For Potion Brewer

### ISSUE THREAD

**Issue by kjj194** [InnovativeOnlineIndustries/Industrial-Foregoing#605]
The mod Extra Alchemy adds recipes for new potions some of which require bottles of water to be infused with glowstone or gold instead of netherwart initially.

A good solution to this problem would be to rather than locking the slots to specific items just allow them to be locked to whatever current item is in there similar to an rftools crafter.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
