### ISSUE TITLE
Tesla core Upgrade issue

### ISSUE THREAD

**Issue by Solus-Prime** [InnovativeOnlineIndustries/Industrial-Foregoing#606]
**Industrial Foregoing Version: 1.12.8**

**TeslaCoreLib Version: 1.0.15**

Plant sower, Plant gatherer, Plant fertilizer and sludge refiner don't accept Tesla core lib tier 2 speed upgrades but will accept tier 1 upgrades

**Comment by Buuz135** [comment]
You need to use both at the same time
