### ISSUE TITLE
[1.12] Imprisonment tool does not work on villagers

### ISSUE THREAD

**Issue by GiovanH** [InnovativeOnlineIndustries/Industrial-Foregoing#608]
Right-clicking a villager with an imprisonment tool brings up the trading GUI, which prevents the imprisonment tool from working. 

It works on baby villagers and nitwits. 

**Industrial Foregoing Version:** 1.12.13

**TeslaCoreLib Version:** 1.12.2-1.0.15

**Comment by GiovanH** [comment]
For reference, the capturing wand from Not Enough Wands has a similar entity capturing behavior, but it works properly. It uses left-click to capture, though.

**Comment by Lanse505** [comment]
There should be a capture device launcher for use with villagers and entities that have too big hitboxes. Look if that still exists and if it does use that.

**Comment by syruppp** [comment]
Shift+Right-click.

**Comment by GiovanH** [comment]
Shift+Right click is correct, but this doesn't seem to be documented behavior.

**Comment by GiovanH** [comment]
This issue could be resolved with documentation, or a message that reminds you if you left-click a villager while holding a capture tool.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
