### ISSUE TITLE
[1.12] Game Crash from loading Industrial Foregoing mod (Using Twitch Mod Pack)

### ISSUE THREAD

**Issue by VyseNoxus** [InnovativeOnlineIndustries/Industrial-Foregoing#610]
**Industrial Foregoing Version: 1.12.2-1.12.12-336

**TeslaCoreLib Version: 1.12.2-1.0.15

**Crashlog If Applicable (Upload to pastebin/gist): [U2Je1nJw.txt] https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/3645091/U2Je1nJw.txt)

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
