### ISSUE TITLE
[1.12] Inverted laser lens in a laser base crashes

### ISSUE THREAD

**Issue by libraryaddict** [InnovativeOnlineIndustries/Industrial-Foregoing#612]
**Industrial Foregoing Version: ** 1.12.13-237

**TeslaCoreLib Version: ** 1.0.15

**Crashlog If Applicable (Upload to pastebin/gist): ** (Shortened)
 https://pastebin.com/qW4G5eWE

Basically from what I gather, he placed a normal laser lens in. Then 5 inverted lens.

**Comment by MrTitainin** [comment]
I managed to also crash laser base with inverted lens. It should be easy to solve by adding a check that changes all negative weights to 0.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
