### ISSUE TITLE
[1.12] Mob Crusher gives essence without killing

### ISSUE THREAD

**Issue by Hiagg** [InnovativeOnlineIndustries/Industrial-Foregoing#613]
**Industrial Foregoing Version: **

1.12.2 - 1.9

**TeslaCoreLib Version: **

1.12.2 - 1.0.15

**Issue**
So apparently the mob crusher killing mobs isnt actually a requirement for essence. Just mobs dying within its area of coverage. So with a max range upgrade and a mob crusher from mob_grinding_utils to kill with looting 10, i dont even need to power the machine to collect essence at a rate faster than a powered crusher can collect it

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
