### ISSUE TITLE
[1.12] Wither builder spawn glitch

### ISSUE THREAD

**Issue by Shadowhackercz** [InnovativeOnlineIndustries/Industrial-Foregoing#614]
**Industrial Foregoing Version: 1.12.2 - 1.12.8-232**

**TeslaCoreLib Version: 1.12.2 - 1.0.15**

**Crashlog If Applicable (Upload to pastebin/gist): **

Hi, I'm not sure if anyone here posted this, but I today found a bug (glitch) on stream accidentaly.

If you use wither builder in a claimed chunk and you don't allow to build fake players blocks and you build the wither for yourself except ONE wither head, I think that the wither builder tries to build the head, but it gets cancelled, however, it will still spawn the wither, so..

I had like 100 withers suddenly flying around by accident.

If it's already reported or fixed, then sorry.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
