### ISSUE TITLE
[1.12] Compatibility with Animania

### ISSUE THREAD

**Issue by Yousei9** [InnovativeOnlineIndustries/Industrial-Foregoing#616]
industrialforegoing-1.12.2-1.12.13-237
animania-1.12.2-1.7.2

Issue on animania: https://github.com/capnkirok/animaniamod/issues/321

Animal Feeder:
Pigs, Cows and Horses are bottomless black holes. The feeder is constantly pumping them full, hearts are flying but there hasn't been a single baby born.
Chickens refuse seeds from the feeder and complain about hunger
Sheep at least breed but still require way more food than they should.

Animal Grower:
Doesn't seem to work at all. All baby animals are hungry and if enabled starve to death long before growing to adulthood.

**Comment by rachelf42** [comment]
just ran into the same issue, using tekxit 3 v0.972

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
