### ISSUE TITLE
[1.12] Enchantment Applicator/Extractor - Interaction with Mystical Ag Armors

### ISSUE THREAD

**Issue by Danekjovax** [InnovativeOnlineIndustries/Industrial-Foregoing#618]
**Industrial Foregoing Version: **
industrialforegoing-1.12.2-1.12.13-237

**TeslaCoreLib Version: **
tesla-core-lib-1.12.2-1.0.15

Hello!  I'm playing with your mod within the modpack Dungeons Dragons & Space Shuttles v6.3, and noticed that none of the Mystical Agriculture armors can be used with your Enchantment Extractor or Applicator.  Could they be added?  Thanks in advance!

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
