### ISSUE TITLE
[1.12] Speed Upgrade II Issue

### ISSUE THREAD

**Issue by maonya** [InnovativeOnlineIndustries/Industrial-Foregoing#620]
**Industrial Foregoing Version: **
industrialforegoing-1.12.2-1.12.8-232
**TeslaCoreLib Version: **
tesla-core-lib-1.12.2-1.0.15

Speed Upgrade 2 from the Tesla Core Lib mod cannot be put into the Latex Processing Unit. I'm pretty sure this is a bug because the LPU allows me to put the first tier of the speed upgrade into its upgrade slots.

**Comment by manahound** [comment]
Encountering the same with the Latex Processing Unit, Block Placer, and Plant Interactor (all accept speed upgrade I but not II) on:
* tesla-core-lib 1.0.15
* industrialforegoing 1.12.13

**Comment by Buuz135** [comment]
You need tier 1 to add tier 2

**Comment by Matt2408** [comment]
@Buuz135 Shouldn't the Fluid Extractor accept tier 2 upgrades aswell? (if you have tier 1 already equiped)?
