### ISSUE TITLE
[1.12] Missing lang keys

### ISSUE THREAD

**Issue by aaronhowser1** [InnovativeOnlineIndustries/Industrial-Foregoing#622]
**Industrial Foregoing Version: **
industrialforegoing-1.12.2-1.12.13-237
**TeslaCoreLib Version: **
tesla-core-lib-1.12.2-1.0.15

`text.book.accepted_items`
`text.book.produced_items`

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
