### ISSUE TITLE
Feature Request: Prevent removal of filled bottles until all ingredients are brewed.

### ISSUE THREAD

**Issue by minakitty** [InnovativeOnlineIndustries/Industrial-Foregoing#623]
Technically a dup of #438 , but as the proposed 'fix' isn't a fix, and it was closed without feedback from the OP, have to open a new issue.

I have the same issue with connecting my brewer with Refined Storage, and as was mentioned there, simply whitelisting the desired potion is not desireable.  Otherwise, one will have to make an individual Crafter (to send brewing ingredients to the machine), Writer (to apply power), 2 Exporters (one to add water and one to add bottles), an Importer (whitelisted to the exact potion you want), -and- the potion brewer.

What would the possibility be of setting up so the three bottles are locked in the 'output' buffer until the fifth crafting stage is completed.  Doing that would allow all recipes to craft as intended with only a small delay for recipies with fewer steps?  Otherwise I have to manually collect bottles everytime as I can't safely use the output

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
