### ISSUE TITLE
[FEATURE] Resourceful Furnace feature request: Auto split item

### ISSUE THREAD

**Issue by binh3012** [InnovativeOnlineIndustries/Industrial-Foregoing#625]
**Describe the solution you'd like**
You could add a button/options to allow on/off auto split item in Resourceful Furnace. Thanks.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
