### ISSUE TITLE
[1.12] Generator extra RF

### ISSUE THREAD

**Issue by springheeljack** [InnovativeOnlineIndustries/Industrial-Foregoing#627]
Industrial Foregoing Version:
industrialforegoing-1.12.2-1.12.13-237
TeslaCoreLib Version:
tesla-core-lib-1.12.2-1.0.15

Attaching any energy acceptors (machines, capacitor bank) to multiple sides of any generator causes extra RF to be generated. For example, burning a block of coal in a Petrified Fuel Generator with an EnderIO capacitor bank on the left and right sides of the generator will result in 800rf/t going into one bank and 400rf/t going into the other. The same thing happens when using more capacitor banks, with a third bank receiving 266rf/t, fourth receiving 200rf/t etc.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
