### ISSUE TITLE
[1.14] Shift Clicking interacts weirdly in inventories like the block placer

### ISSUE THREAD

**Issue by Darkere** [InnovativeOnlineIndustries/Industrial-Foregoing#631]
**Industrial Foregoing Version: **
industrial-foregoing-1.14.4-2.1.0-69a4a14
**Titanium Version: **
titanium-1.14.4-2.2.9
switches between hotbar and inventory instead of the machine.

**Comment by Darkere** [comment]
Made it worse :(. You can no longer shift-click out of containers. 

While shift-clicking into containers does work now, it only works until half the inventory is filled for some bizarre reason.

**Comment by Buuz135** [comment]
Can't replicate in 1.15

**Comment by Darkere** [comment]
Then you are not looking hard enough :)

https://gfycat.com/FearlessFirmCaribou

**Comment by Buuz135** [comment]
Is this the 1.15.2 version?

**Comment by Darkere** [comment]
yes the one you just released
