### ISSUE TITLE
[1.14] Incompatibility with Mystical Agriculture (?)

### ISSUE THREAD

**Issue by Fogrits** [InnovativeOnlineIndustries/Industrial-Foregoing#633]
**IF Version: 2.1.0-69a4a14**

**Titanium Version: 2.2.9**

**Forge Version: 28.1.96**

[Crash Log](https://pastebin.com/j2w3cmrY)

**Comment by Buuz135** [comment]
Why did I get this report?

**Comment by Fogrits** [comment]
Happened after installing IF

**Comment by Buuz135** [comment]
It doesn't mention IF at all in that crash report.
