### ISSUE TITLE
1.7 feature

### ISSUE THREAD

**Issue by 34486** [InnovativeOnlineIndustries/Industrial-Foregoing#637]
Hello, I would like to request a feature that was in the old 1.7 minefac reloaded to be implemeneted iinto industrial foregoing. 

When lightning strikes a pink slime, they duplicate (as well as catch fire and burn) but iit immedetaly duplicates them. 

Is this something that could be added? I beleive it was a hidden feature, so I guess could it stay hidden?

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
