### ISSUE TITLE
1.14.4 Version Crashes Upon Startup

### ISSUE THREAD

**Issue by DJBaphomet** [InnovativeOnlineIndustries/Industrial-Foregoing#638]
Industrial Foregoing Version: 1.14.4
TeslaCoreLib Version: No 1.14.4 version?
Crashlog (If Any): [crash-2019-12-08_16.47.08-client.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/3937327/crash-2019-12-08_16.47.08-client.txt)

**Comment by Buuz135** [comment]
It needs titanium as a dependency
