### ISSUE TITLE
Putting a dead mob in a mob duplicator crashes the server

### ISSUE THREAD

**Issue by computer2467** [InnovativeOnlineIndustries/Industrial-Foregoing#639]
Industrial Foregoing Version: 1.12.13
TeslaCoreLib Version: 1.0.15
Crashlog (If Any): [crash-2019-12-08_21.45.06-server.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/3937678/crash-2019-12-08_21.45.06-server.txt)
If you use a mob imprisonment tool on a dead mob, it will store a mob with 0HP. If you put the MIT into a mob duplicator, it will crash the server then and whenever the server restarts with it active from that point.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
