### ISSUE TITLE
Request: Include sane keywords in tooltips

### ISSUE THREAD

**Issue by trevorjd** [InnovativeOnlineIndustries/Industrial-Foregoing#642]
I appreciate the desire to not breach copyrights or whatever, but who thinks to search for "gatherer" when trying to find a farmer, farming station or harvester?

It would be helpful if relevant keywords could be included in item descriptions such that relevant machine can be found when a player searches!

**Comment by PssbleTrngle** [comment]
I agree.
I love the extraordinary way every machine has been renamed, it makes playing with the mod so much more fun, but there should be some way to find them without having to guess every synonym in the dictionary. 
Providing a tooltip in the lore would be very helpful

**Comment by Buuz135** [comment]
There is a manual for the mod now, check it out if you need to know what machines does.
