### ISSUE TITLE
NPE and CTD when clicking Facings I/O button in BioFuel Generator

### ISSUE THREAD

**Issue by trevorjd** [InnovativeOnlineIndustries/Industrial-Foregoing#644]
Singleplayer, made a BioFuel Generator, placed it, opened the GUI, clicked the "facings" button at the bottom left (where you specify pull/push etc.) and instant CTD.  Problem doesn't occur with the Sower, Fluid Extractor or Latex Processor, but 2/2 with the BioGen.

Industrial Foregoing Version:  1.14.4-2.1.0-69a4a14
TeslaCoreLib Version: n/a
Titanium Version: 1.14.4-2.2.9
Forge Version: 1.14.4-28.1.104
Crashlog (If Any): https://gist.github.com/trevorjd/54ccfa31318d17054f513a8e591c8622

**Comment by Buuz135** [comment]
Duplicate #628
