### ISSUE TITLE
Crash with infinity drill

### ISSUE THREAD

**Issue by Darkere** [InnovativeOnlineIndustries/Industrial-Foregoing#646]
Industrial Foregoing Version: industrial-foregoing-1.14.4-2.1.0-69a4a14.jar
titanium-1.14.4-2.2.9.jar  
Crashlog (If Any): https://hatebin.com/lgowholvri

**Comment by EterniaLogic** [comment]
Same, I cannot login again. I had my drill on 5x5x1.
Also, I had infinite RF/t when my drill had 15milRF and 6k Biofuel in the drill. 

The drill seemed to use 10kRF/drill in tier one, which seemed excessive.

https://pastebin.com/Q61M6VSe

**Comment by Vaelzan** [comment]
Fixed both the crash and the render height of the bounding box. Hopefully the developer accepts the patch, I just happened to be debugging the issue for somebody on Valhelsia's Discord. https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/pull/647
