### ISSUE TITLE
fluid pump won't pump 1-high pool

### ISSUE THREAD

**Issue by Spongman** [InnovativeOnlineIndustries/Industrial-Foregoing#648]
v1.12.3

````
/fill ~-31 ~-1 ~-31 ~31 ~-2 ~31 minecraft:stone
/fill ~-30 ~-1 ~-30 ~30 ~-1 ~30 minecraft:lava
````

try to pump it. doesn't work.

edit: it seems the range addon size matters. +7 or more doesn't work.

**Comment by Spongman** [comment]
are there no more bug fixes for 1.12 ?

**Comment by Spongman** [comment]
ok, this is a bit more subtle. it seems that it's stopping for some reason that i can't determine. and in my world it looks like it stopped before pumping the surface layer of lava block.

here's a question, when does `isWorkFinished` ever get set to false?

**Comment by saturner** [comment]
Seeing this too on FTB Academy

**Comment by KollinsPlays** [comment]
I'm curious @Spongman what you did before you took the addon out? I know if a pump has no range addon but has power, like #649 and frankly, most of the problems I've had with the Fluid Pump, it will suck up the block right below it, put cobble there and then stay in the "i'm done working" state even if you put a range addon in.

> here's a question, when does `isWorkFinished` ever get set to false?

This seems to be the hangup that unless you put a range addon in first, possibly filter if there are multiple fluids in range, and then power it up, it just pumps the block below it and shuts off. The fix would be to have it check for work to do when addons change or maybe even when redstone control is changed. I can imagine this 1 change would cut down a lot of bug reports and questions about the pump. I kinda wish I knew enough java to just fix it and push a change up...

**Comment by Spongman** [comment]
i think unfortunately the 1.12 version is unsupported at this point, which is a shame since that's the one that all the modpacks are using...

**Comment by Buuz135** [comment]
Duplicate #648

**Comment by Spongman** [comment]
how is an issue a duplicate of itself?
