### ISSUE TITLE
fluid pump doesn't notice range addon change

### ISSUE THREAD

**Issue by Spongman** [InnovativeOnlineIndustries/Industrial-Foregoing#649]
Industrial Foregoing Version: 1.12.3
TeslaCoreLib Version: 1.12.2-1.0.15

if a fluid pump has power, then it doesn't notice when you add/change the range addon.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
