### ISSUE TITLE
[1.12.2] Add config for Mob Imprisonment Tool for currentHealth.

### ISSUE THREAD

**Issue by Slayer5934** [InnovativeOnlineIndustries/Industrial-Foregoing#652]
I would like to suggest something simple that would fix a bug in my modpack Tekxit 3, currently the mob imprisonment tool is able to capture entities such as battletower golems. What if a config could be added so it checks the entities current health and only allow capture below a certain percentage remaining or health remaining?

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
