### ISSUE TITLE
[1.12.2] Extra Utilities 2 Compound Bow cannot be disenchanted

### ISSUE THREAD

**Issue by Satvn** [InnovativeOnlineIndustries/Industrial-Foregoing#655]
Industrial Foregoing Version: 1.12.2-1.12.13-237
TeslaCoreLib Version: 1.12.2-1.0.15

The compound bow from extra utilities 2 cannot be disenchanted in the enchantment extractor, which is odd considering the Kikoku can be disenchanted

(Eu2 version: 1.12-1.9.9)

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
