### ISSUE TITLE
1.14.4 Problem with inventory sorter and if

### ISSUE THREAD

**Issue by tschaha** [InnovativeOnlineIndustries/Industrial-Foregoing#656]
Industrial Foregoing Version: 2.1.2-582ea8b
TeslaCoreLib Version: 
Using inventorysorter(16.2.0) in the plant gatherer takes out the range addon and puts it in the outputslot of it.
Using inventorysorter on the plant sower delets the range addon.

**Comment by testykleez** [comment]
I believe this to be related. When I use my Scroll Wheel Click (inventory Sorter) while my Plant Sower is open, the Range Addon also disappears, but where there is no Output slot it has no where to go and is effectively lost. I have not been able to find my missing Range Addons.
I am running All the Mods 4 with a Multi-player Server
Industrial Foregoing-1.14.4-2.12-582ea8b

**Comment by Buuz135** [comment]
I can't change how the inventory sorting mods work in my machines
