### ISSUE TITLE
EnchantmentExtractor can remove tools enchantments in Tinkers's Construct

### ISSUE THREAD

**Issue by karikusa** [InnovativeOnlineIndustries/Industrial-Foregoing#659]
Industrial Foregoing Version: IntegrationForegoing-1.12.2-1.9
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15
Crashlog (If Any): 
It seems that Tinkers' Construct's silk touch and lucky enchantment can be removed.
Unfortunately, they can't seem to be able to regain their abilities.

**Comment by drizzs** [comment]
Can you post some photos or your log after you reproduce this? I feel like that would help... but you don't have to I just want to see what you mean it sounds pretty funny

**Comment by karikusa** [comment]
![エンチャント剥がしのバグ？１](https://user-images.githubusercontent.com/23197795/71773486-16fad980-2fa1-11ea-9bcd-cd9256b7cfd6.png)
![エンチャント剥がしのバグ？２](https://user-images.githubusercontent.com/23197795/71773487-17937000-2fa1-11ea-8fbc-5a71ab7a900a.png)
![エンチャント剥がしのバグ？３](https://user-images.githubusercontent.com/23197795/71773488-17937000-2fa1-11ea-9356-adb577240f84.png)
The bug was reproduced in the minimum environment!
Forge: forge-1.12.2-14.23.5.2847
CommonCapabilities-1.12.2-2.4.4
CyclopsCore-1.12.2-1.5.1
Forgelin-1.8.4
Hwyla-1.8.26-B41_1.12.2
industrialforegoing-1.12.2-1.12.13-237
IntegratedDynamics-1.12.2-1.1.0
IntegratedTunnels-1.12.2-1.6.10
jei_1.12.2-4.15.0.291
Mantle-1.12-1.3.3.55
NoMoreRecipeConflict-0.13 (1.12.2)
OptiFine_1.12.2_HD_U_F4
TConstruct-1.12.2-2.13.0.171
tesla-core-lib-1.12.2-1.0.15
The rest is as shown in the picture,
Extractor removes the silk touch of the tool,
Enchantment book and tools remain,
The third piece is a crushed ore with the tool.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
