### ISSUE TITLE
[1.14.1]Industrial-Foregoing Plant Gather

### ISSUE THREAD

**Issue by windybut** [InnovativeOnlineIndustries/Industrial-Foregoing#661]
Industrial Foregoing Version: ndustrial-foregoing-1.14.4-2.1.1-6df3f9e.ja
TeslaCoreLib Version:  
Crashlog (If Any): 

I have a Mystical Agriculture seeds and the Gatherer works on one seed.  My seeds are underground 10 blocks down.   I then added a +4 upgrade to it, the show area was good so I ran it.  It delete my base behind the gatherer and 10-16 blocks up.  That's not good.

**Comment by Buuz135** [comment]
What?

**Comment by Buuz135** [comment]
The 1.14.4 version is not supported anymore please update to 1.15.2. And fixed ^
