### ISSUE TITLE
1.15.1 Placing block into world causes crash

### ISSUE THREAD

**Issue by MeinKraft** [InnovativeOnlineIndustries/Industrial-Foregoing#664]
Industrial Foregoing Version: 1.15.1-2.2.0
TeslaCoreLib Version: (Titanium 1.15.1-2.3.3)
Crashlog (If Any): https://pastebin.com/hbxtr46b
Forge: 30.0.41

simply place the BIO Fuel gen into the world and instant hard crash

seems to be any block placed in the world from Industrial Foregoing

**Comment by Buuz135** [comment]
Update to Titanium 2.3.4 when it's approved by CF
