### ISSUE TITLE
1.15.1 Pitiful Generator Broke!

### ISSUE THREAD

**Issue by Yamza** [InnovativeOnlineIndustries/Industrial-Foregoing#667]
Pitiful Generator eats items and doesn't produce RF.

Industrial Foregoing Version: industrial-foregoing-1.15.1-2.2.0.jar
TeslaCoreLib Version: no
titanium-1.15.1-2.3.4.jar
Crashlog (If Any): Not
https://i.imgur.com/g6IWRzc.gifv

**Comment by Sleeeper** [comment]
Just fills progress bar to 100 and does nothing more.
