### ISSUE TITLE
[1.14.4] Crash when using Block placer machine. (On a Server.)

### ISSUE THREAD

**Issue by Gbergz** [InnovativeOnlineIndustries/Industrial-Foregoing#669]
**Industrial Foregoing Version**: 2.1.2-582ea8b
**Titanium Version**: 2.2.10
**Crashlog**: https://gist.github.com/Gbergz/779158fc308136870cb0b8bdc79c759e

**Comment by Buuz135** [comment]
The chunk claiming mod is causing the issue
