### ISSUE TITLE
[1.12] Crash when using the fluid pump

### ISSUE THREAD

**Issue by Headshot-00** [InnovativeOnlineIndustries/Industrial-Foregoing#673]
So I have 8 fluid pumps in the nether with the diamond range addon, but the game keeps crashing and I think it is related to the fluid pumps. The crash happens only when the pumps are running and if they are the game crashes only a few seconds after world load.

Industrial Foregoing Version: 1.12.13-237
TeslaCoreLib Version: 1.0.15
Crashlog (If Any): https://pastebin.com/TVdt82X0

**Comment by drcrazy** [comment]
+1 for that issue

Server crashes from time to time (approximately once in two days) with same stacktrace. 
Fluid pump is working in a loaded chunk in nether.

IF version: 1.12.13-237
TeslaCoreLib version: 1.0.17

Crash log: https://pastebin.com/54JRSj5P

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
