### ISSUE TITLE
Forge change breaks your mod.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [InnovativeOnlineIndustries/Industrial-Foregoing#674]
Industrial Foregoing Version:

 industrial-foregoing-1.15.1-2.2.0

Titanium Version: 

titanium-1.15.1-2.3.4

Forge 1.15.1 - 20.0.51 
Changlog "Renamed ModConfigEvent.ConfigReloading to ModConfigEvent.Reloading"

The change breaks your mod. Please update. Thanks.

**Comment by Buuz135** [comment]
Fixed in the 1.15.2 port
