### ISSUE TITLE
Black hole units filled with air, wont accept items

### ISSUE THREAD

**Issue by dvdmcwilliams** [InnovativeOnlineIndustries/Industrial-Foregoing#678]
Industrial Foregoing Version: 1.12.13
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): no crashes with this problem.
Hi, I have the following problem: Im using black hole units as input/output for ores to be smelted, when i lock the unit to only be filled with an ore, the input box gets empty and next to it says "air" and wont accept more blocks until I unlock it again, then lock it up to only be filled with the ore i want and the problem comes back again and again, btw when this happen the black hole label shows nothing in it.
![2020-01-28_22 41 57](https://user-images.githubusercontent.com/18901992/73321266-b9188500-4220-11ea-8429-3ff19cca2992.png)

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
