### ISSUE TITLE
Crash from black hole tank with OpenBlocks liquid XP

### ISSUE THREAD

**Issue by GrantGryczan** [InnovativeOnlineIndustries/Industrial-Foregoing#679]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.13-237.jar
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15.jar
Crashlog on server: https://pastebin.com/raw/5fFpGjX2
Crashlog on client: https://paste.dimdev.org/jiwasemuwu.mccrash

Before the crash, I had placed a black hole tank filled with liquid XP from OpenBlocks. I right-clicked the tank with a bucket to get a bucket of liquid XP out. Then I right-clicked it again to put the fluid back into the tank, and both the server and my client immediately crashed. I have only had this problem with OpenBlocks liquid XP.

I've gone into the region file's NBT data and set {paused:1b} on the tank. This has stopped the repeated crashing. But if I then break the tank and place it again, and then I right-click the tank or put the bucket into the top slot of the tank, it continues crashing.

Depositing the fluid indirectly, such as through an AE2 fluid storage bus, works fine.

**Comment by Buuz135** [comment]
Duplicate #413
