### ISSUE TITLE
Cant seem to find in game manual  ? 

### ISSUE THREAD

**Issue by carlucci9660** [InnovativeOnlineIndustries/Industrial-Foregoing#680]
Industrial Foregoing Version: industrial-foregoing-1.14.4-2.1.2-582ea8b
TeslaCoreLib Version: 
Crashlog (If Any): 

Cant seem to find in game manual ? also do your machines take upgrades ? cant seem to find them either ?

**Comment by Buuz135** [comment]
The manual is not implemented and there arent upgrades yet. Use discord for support and questions.
