### ISSUE TITLE
Black Hole Controller destroyed my grains of infinity.

### ISSUE THREAD

**Issue by mamiller2322** [InnovativeOnlineIndustries/Industrial-Foregoing#681]
Industrial Foregoing Version: 1.12.2-1.9
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): none

Trying to put my Black hole units in a controller, somehow the unit with my grains of infinity got turned into arrows. Not sure when it happened, but now I have two units, one with ~4500 arrows, one with ~5300 arrows (this one should have been the grains.)

**Comment by mamiller2322** [comment]
update, it did it again, when I put the unit that had one stack of grains in the first slot, it got converted to bones this time. I will try re-placing the controller.

**Comment by Buuz135** [comment]
Did the BHU get emptied and something else got in?

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
