### ISSUE TITLE
Server Crash Report 1.15.2

### ISSUE THREAD

**Issue by xxlio109** [InnovativeOnlineIndustries/Industrial-Foregoing#683]
Issue description:
Server Crash Report

Version (make sure you are on the latest version before reporting):
Forge:  31.1.0
industrial-foregoing-1.15.2-2.2.1-f27c515

https://gist.github.com/xxlio109/4eceb3689a56c9b8dd0ffc77738b1a0e

**Comment by Buuz135** [comment]
Not an IF issue its not even mentioned in the crash report
