### ISSUE TITLE
planting machines not working properly

### ISSUE THREAD

**Issue by degenerade** [InnovativeOnlineIndustries/Industrial-Foregoing#685]
Industrial Foregoing Version: 1.12.13
TeslaCoreLib Version: 1.12.2 - 1.0.15
Crashlog (If Any): 

Im using the plant sower and the plant harvester but they constantly switch between using -4rf and 4rf and dont plant/harvest anything, they even do it of they dont have anything to do.

**Comment by q1051278389** [comment]
I have that trouble ,how can fix it?

**Comment by degenerade** [comment]
> I have that trouble ,how can fix it?

idk i havent found anything

**Comment by Buuz135** [comment]
Make sure that Minecolonies or other mods that add chunk protection arent preventing them from working
