### ISSUE TITLE
[1.12] NPE crash with mob crusher and mobs trying to apply potion effects

### ISSUE THREAD

**Issue by Cynosphere** [InnovativeOnlineIndustries/Industrial-Foregoing#686]
Industrial Foregoing Version: 1.12.13
TeslaCoreLib Version: 1.0.15
Crashlog (If Any): https://gist.github.com/Cynosphere/47ea15e290b50ad1ff68051ea4c591ed

This mainly happened with one of Advent of Ascension's mobs and I tried to report it to them but they blew me off and told me to take the issue here so I am.

**Comment by Caralamelia** [comment]
Same issue, found a small workaround until fixed of using a redstone signal to turn off the crusher when the mob is around or full moon is on effect

**Comment by Buuz135** [comment]
The issue is from the mod that adds the NightWatcher
