### ISSUE TITLE
Missing Villager Trader Exchange

### ISSUE THREAD

**Issue by Curlz242** [InnovativeOnlineIndustries/Industrial-Foregoing#687]
Industrial Foregoing Version: industrial-foregoing-1.15.2-2.2.1-f27c515
TeslaCoreLib Version: unknown
Crashlog (If Any): none

Hi there,
I am missing the Villager Trader Exchange in the newest version.

**Comment by Buuz135** [comment]
Because its not implemented....

**Comment by telemenar** [comment]
Is this something that you are expecting to add back when you have time? Or intentional removal?
