### ISSUE TITLE
[1.14.4] UnsupportedOperationException: No bounds for empty shape

### ISSUE THREAD

**Issue by Dude20121** [InnovativeOnlineIndustries/Industrial-Foregoing#688]
**Industrial Foregoing Version:** 1.14.4-2.1.2-582ea8b
**Titanium Version:** 1.14.4-2.2.10
**Crashlog**: [https://pastebin.com/chGrKcrp](https://pastebin.com/chGrKcrp)

After walking around the Nether for a few minutes with the infinity drill, my client crashed with the error "java.lang.UnsupportedOperationException: No bounds for empty shape." I can't reconnect to the server (which is private and hosted by a friend) without getting the same error when my client attempts to render the environment. The first mod mentioned in the crash log was Industrial Foregoing.

**Comment by carlucci9660** [comment]
i have same issue, but under the sea >>with drill

I think whats happening is, once the drill removes any blocks, then you move through the area the blocks used to exsist, thats when game freezes and then crash and game will not load again unless you have backups.
[crash-2020-02-18_17.48.47-client.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/4223138/crash-2020-02-18_17.48.47-client.txt)
[crash-2020-02-18_17.45.44-client.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/4223139/crash-2020-02-18_17.45.44-client.txt)

**Comment by carlucci9660** [comment]
I also sent this error to forge thinking it might be them, but after reading my log, this is what they said...

at com.buuz135.industrial.proxy.client.event.IFClientEvents.blockOverlayEvent(IFClientEvents.java:76) ~[?:2.1.2] {re:classloading}

Something in Industrial Foregoing

**Comment by Dude20121** [comment]
Based on my logs, I'm thinking it's either walking where blocks used to exist or something to do with how blocks are outlined by the drill. I was able to rejoin the world after the chunk that I was in was deleted by the server host.

**Comment by LordMZTE** [comment]
this seems to be happening when looking at a strange type of block, like a bubble column for example with the infinity drill

**Comment by Buuz135** [comment]
The 1.14.4 version is not supported anymore please update to 1.15.2.
