### ISSUE TITLE
Too Close Together?

### ISSUE THREAD

**Issue by 0haun** [InnovativeOnlineIndustries/Industrial-Foregoing#690]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.13-237
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): N/A

I have several plant harvesters and sowers near each other and I just can't get them to work. They are set with range addons and there is one block between the fields. the second one in line only harvests and plants the first row closest to the last field and the rest just don't work. I have potato fields next to each other as well that don't seem to work next to each other.
![Example 1](https://user-images.githubusercontent.com/43766028/74698137-76fcb680-51c2-11ea-9c5c-c702b952d580.png)
![Example 2](https://user-images.githubusercontent.com/43766028/74698138-77954d00-51c2-11ea-8d1c-023dc6edb7b5.png)
![Example 3](https://user-images.githubusercontent.com/43766028/74698139-782de380-51c2-11ea-9d28-0b9c46080ac0.png)
![Example 4](https://user-images.githubusercontent.com/43766028/74698140-782de380-51c2-11ea-9bac-5d31d07ed6ac.png)

**Comment by Buuz135** [comment]
Make sure that the area isn't protected by Minecolonies or something similar
