### ISSUE TITLE
Feature Request: Upgrades or Faster Block Placer

### ISSUE THREAD

**Issue by carlucci9660** [InnovativeOnlineIndustries/Industrial-Foregoing#692]
Feature Request: Upgrades for Block placer or Faster Block Placer

Industrial Foregoing Version: industrial-foregoing-1.14.4-2.1.2-582ea8b
TeslaCoreLib Version: None, running 1.14.4
Crashlog (If Any): None, Feature Request !

**Comment by Buuz135** [comment]
There are addons now
