### ISSUE TITLE
Black hole controller deleting items

### ISSUE THREAD

**Issue by OculusRex** [InnovativeOnlineIndustries/Industrial-Foregoing#693]
I built and placed 4 controllers and filled them with BHU's. I ten set about emptying the TF Cache's I'd been using into them. I went and did other stuff and came back to find out that 6 weeks of mined/processed/mob farmed items had been deleted. Over 500k items all told. I suspeect this has something to do with the issue I've now seen with the controller replacing whatever is in the first BHU with whatever is being piped in next.

Industrial Foregoing Version: 1.12.2-1.12.8-232
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any):

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
