### ISSUE TITLE
IllegalArgumentException causes crash on world start

### ISSUE THREAD

**Issue by aaronhowser1** [InnovativeOnlineIndustries/Industrial-Foregoing#694]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.13-237.jar         
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15.jar                   
Crashlog (If Any): https://paste.dimdev.org/vehahexuco.mccrash

Reposting from FTBTeam/FTB-Academy/issues/259

**Comment by James103** [comment]
I can't access the crash log (see DimensionalDevelopment/VanillaFix#262). Could you please try reuploading the crash report to Gist or Pastebin without any expiry dates?

**Comment by aaronhowser1** [comment]
Unfortunately, it isn't me who has the crash. You can ask the original issue's creator, I suppose, but the issue is from February

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
