### ISSUE TITLE
Plant Gatherer destroys my house

### ISSUE THREAD

**Issue by MoarDm** [InnovativeOnlineIndustries/Industrial-Foregoing#700]
Industrial Foregoing Version: 1.15.2-2.2.1-f27c515
TeslaCoreLib Version: 
Crashlog (If Any): 

I placed Plant Gatherer with +8 upgrade and half of my house gone. It dig up this blocks: wood, planks, wooden fence, chest, door, barrels (from 'metabarrels' mod)

It's very strange behavior. Seems like duplicate of #661

**Comment by MoarDm** [comment]
I recorded it
https://youtu.be/RLEbraMVCH8

**Comment by MoarDm** [comment]
Demolished some villager's house 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9071683/75816192-c7206f00-5da5-11ea-97af-04d2b42943ce.png">

<img width="428" alt="image" src="https://user-images.githubusercontent.com/9071683/75816089-96d8d080-5da5-11ea-881e-04a662b6c82d.png">

I don't understand why this types of blocks are harvestable

**Comment by LordMZTE** [comment]
seems like its limited to a wider selection of wood blocks instead of something like minecraft:logs wich every log should have :D

**Comment by shortybsd** [comment]
Anything wood base it will destroy; Chests, Barrels, Jukebox, e.t.c. I found out the hard way having a max tiered range upgrade installed.

**Comment by Buuz135** [comment]
Fixed in that PR ^
