### ISSUE TITLE
[1.14.4] Crash When Trying to Draw Infinity Drill Bounding box on bubble column

### ISSUE THREAD

**Issue by LordMZTE** [InnovativeOnlineIndustries/Industrial-Foregoing#701]
Industrial Foregoing Version: 1.14.4-2.1.2-582ea8b
TeslaCoreLib Version:  not installed
Titanium: 1.14.4-2.2.10
Crashlog (If Any): https://pastebin.com/H4FmayqF

i was mining with the infinity drill and hit an underwater ravine and then the game crash looped because every time i would load back in, the same error would occur again. luckily i was able to look through the source and roughly find out what caused the problem. so i managed to repair my map by changing the selected slot in the save file. 

i was able to replicate this issue by simply looking at a bubble column block with the infinity drill

im playing the All the mods 4 pack in case another mod was involved in the issue even tho it doesnt seem like thats the case

**Comment by LordMZTE** [comment]
might be Duplicate of #684

**Comment by LordMZTE** [comment]
Appears like this happens to blocks without a bounding box, so perhaps a check should be implemented

**Comment by Buuz135** [comment]
The 1.14.4 version is not supported anymore please update to 1.15.2.
