### ISSUE TITLE
[1.12.2] Wither Building spawns far too many withers

### ISSUE THREAD

**Issue by kiangribi** [InnovativeOnlineIndustries/Industrial-Foregoing#703]
Industrial Foregoing Version: 1.12.13
TeslaCoreLib Version: 1.0.15

When placing soulsand with the wither builder and puttng 3 skulls on top manually, the spawner somehow spawns like 120 withers. I am not sure what happens if I don't cut the powerline in time and I am not interested in finding out ;). It takes resources from nowhere.

**Comment by kiangribi** [comment]
![2020-03-09_15 40 36](https://user-images.githubusercontent.com/31879715/76264013-c1031600-621d-11ea-8a4d-b0f5a79c5dd7.png)

I am playing MC.Eternal with some extra mods manually added on a 1.12.2 forge server. The withers were spawned inside a RFTools Shield Projector. There is a ortal gun portal nearby but I don't think this has anything to do with this. I removed all skulls from my inventory except for the 3 I used to build the wither. So I assume it takes resources from nowhere.

**Comment by papaworld** [comment]
Use MOB DETECTOR machine. Place it "looking" at the Wither spawn area with range card that applies to your setup. The MOB DETECTOR outputs a redstone signal out the back (circle) when it detects a mob/Wither. Connect this redstone output to the WITHER BUILDER and adjust the machine to "Active on no redstone signal". This setup will pause the wither builder until the Wither is dispatched... then another Wither will be built and spawn. Also, place a lever on the Wither Builder to turn it on/off manually if you so choose.

**Comment by RaidingPanda24** [comment]
This happens to me in Dungeons Dragons and Spaceshuttles as well.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
