### ISSUE TITLE
trying to get rubber in a server

### ISSUE THREAD

**Issue by anaxgorous** [InnovativeOnlineIndustries/Industrial-Foregoing#705]
Industrial Foregoing Version: industrial-foregoing-1.14.4-2.1.2-582ea8b.jar
TeslaCoreLib Version: titanium 2.2.10
Crashlog (If Any): https://pastebin.com/cGWpcmYa

tried to get latex in a server and it crashed the server, also i can't seem to get the industrial foregoing manual book

**Comment by Buuz135** [comment]
The 1.14.4 version is not supported anymore please update to 1.15.2.
