### ISSUE TITLE
[1.14.4] Fluid Placer never places fluids

### ISSUE THREAD

**Issue by systemshaper** [InnovativeOnlineIndustries/Industrial-Foregoing#706]
Industrial Foregoing Version: 1.14.4-2.1.2
Titanium version: 1.14.4-2.2.10
Forge version: 1.14.4 28.2.0

Replicated this issue in a single player world with only IF and titanium added. I set down a fluid placer, supply it with power and lava or water, and confirm it has space to place the fluid, but nothing happens.

**Comment by Buuz135** [comment]
The 1.14.4 version is not supported anymore please update to 1.15.2.
