### ISSUE TITLE
Crash on initializing game!

### ISSUE THREAD

**Issue by MusicMaestro123** [InnovativeOnlineIndustries/Industrial-Foregoing#709]
Industrial Foregoing Version: 1.12.6-230
TeslaCoreLib Version: 1.0.15.13
Crashlog (): [https://paste.dimdev.org/toxetiteko.mccrash](url)
Note: I only used this version of Industrial Foregoing due to incompatibilities with forge.

**Comment by MusicMaestro123** [comment]
Note: This is Minecraft 1.12.2 with forge version 14.23.5.2768.

**Comment by Buuz135** [comment]
Redownload the mods, its impossible that its requesting 1.15.2 classes with a 1.12.2 version
