### ISSUE TITLE
[1.14.4] Crashing with MoreProgression's corn seeds and plant sower 

### ISSUE THREAD

**Issue by Williambriggs02** [InnovativeOnlineIndustries/Industrial-Foregoing#713]
Industrial Foregoing Version: industrial-foregoing-1.14.4-2.1.2-582ea8b

TeslaCoreLib Version:  (I don't have TeslaCoreLib as i am on 1.14.4 instead i have titanium which its version is titanium-1.14.4-2.2.10)

Crashlog (If Any):  https://pastebin.com/v4XicrLC

Hello, so when using the plant sower and MoreProgression's corn seed, when the plant sower tries to plant it, it crashes the game if in single player and if on multiplayer it shuts down the server.

**Comment by Buuz135** [comment]
More Progression Issue
