### ISSUE TITLE
[1.15.2]Client crash, this is urgent

### ISSUE THREAD

**Issue by EnterFor** [InnovativeOnlineIndustries/Industrial-Foregoing#714]
Industrial Foregoing Version: industrial-foregoing-1.15.2-2.2.2-28d4a81.jar
TeslaCoreLib Version: titanium-1.15.2-2.3.7.jar
Crashlog (If Any): 
[debug.log](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/4367309/debug.log)
[crash-2020-03-23_12.48.35-client.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/4367310/crash-2020-03-23_12.48.35-client.txt)

I'm the server. The client just crashed. The server is fine
This is urgent, my players can't access the server, access will crash.
I'm not sure if this is for industrial foregoing questions, can you answer for me?
sorry,I'm Chinese, I don't know if you can understand

**Comment by EnterFor** [comment]
I used a temporary solution: delete player inventory data

Only temporary solution to this problem, the player's inventory contains drill, I do not know whether this information can help you

**Comment by Buuz135** [comment]
Should be already be fixed
