### ISSUE TITLE
[suggestion] Black Hole Gas Tank

### ISSUE THREAD

**Issue by Charismara** [InnovativeOnlineIndustries/Industrial-Foregoing#716]
Every mekanism player would be grateful for a mass storage for gas. ExtraCells already supports gas storage for the ME systems. There are completely new possibilities for automation with a mass storage device.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
