### ISSUE TITLE
Mob Duplicator Range - Disable Bubble?

### ISSUE THREAD

**Issue by SkilledAlpaca** [InnovativeOnlineIndustries/Industrial-Foregoing#717]
Industrial Foregoing Version: 1.12.13
TeslaCoreLib Version: 1.12.2-1.0.16
Crashlog (If Any): N/A

Looking at the below attachment, the Mob Duplicators range when given an addon, it creates  a bubble effect where entities spawn underneath the device. Is there a way to disable the bottom half or have it added in? Unless this is an intentional feature I'd like a way to fix this. 

![2020-03-26_13 37 19](https://user-images.githubusercontent.com/26860324/77695371-e6578a00-6f68-11ea-8616-98b3d4f46ecb.png)
![2020-03-26_13 37 36](https://user-images.githubusercontent.com/26860324/77695372-e6f02080-6f68-11ea-8ba8-ee9cbde1dc76.png)

**Comment by Buuz135** [comment]
Intentional feature, just like Minecraft Spawners
