### ISSUE TITLE
Visual Bug w/Fluid Extractor [1.15.2]

### ISSUE THREAD

**Issue by curlywaffles** [InnovativeOnlineIndustries/Industrial-Foregoing#720]
Industrial Foregoing Version:  industrial-foregoing-1.15.2-2.2.2-28d4a81.jar
TeslaCoreLib Version: N/A
Crashlog (If Any): N/A

What happened:
https://imgur.com/a/9bQGeXE

Can replicate with any block.

**Comment by Buuz135** [comment]
It goes away after a while, its fine
