### ISSUE TITLE
[1.12.2] Plant Interactor not putting right clicks from crop sticks into Inventory

### ISSUE THREAD

**Issue by Siniq** [InnovativeOnlineIndustries/Industrial-Foregoing#721]
Industrial Foregoing Version: 1.12.13
TeslaCoreLib Version: 1.12.2-1.0.17
Crashlog (If Any): N/A

Modpack: M.C. Eternal

* The Plant Interactor is right clicking the crop from the crop stick successfully, however it is not putting the results in the inventory, items are just dropping to the ground.  Harvesting without using crop sticks works as expected, and puts the items into the inventory on the machine.

* The Crop Recolector (Plant Gatherer) harvests from the crop stick, and places the picked items into the inventory as expected.

Is this difference expected behaviour?

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
