### ISSUE TITLE
Plant Interactor Cake Duplication

### ISSUE THREAD

**Issue by doomfur** [InnovativeOnlineIndustries/Industrial-Foregoing#722]
Industrial Foregoing Version: 1.12.2 1.9
TeslaCoreLib Version: 1.12.2 1.0.15

When a vanilla cake is placed in the world and is within the working range of an Industrial Foregoing Plant Interactor, it will drop a cake item into the world without destroying the cake. Cakes can be generated quickly and indefinitely as long as the plant interactor has power.

To recreate:
Place plant interactor and connect to power source.
Place cake in working area of plant interactor.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
