### ISSUE TITLE
Plant Gatherer gathering way more trees than it should

### ISSUE THREAD

**Issue by Alethephobe** [InnovativeOnlineIndustries/Industrial-Foregoing#728]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.13-237
TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.15
Crashlog (If Any): 

![image](https://user-images.githubusercontent.com/38894389/78924578-610cc300-7a9a-11ea-82a1-07f24740c9cf.png)
![image](https://user-images.githubusercontent.com/38894389/78924614-6f5adf00-7a9a-11ea-867a-f95a749ebb7b.png)

Hi, as you can see on the pictures above, I installed 3 plant gatherers next to each other and into them i have put range addon +12. The gatherers gathered way more trees than it was supposed to and it didnt gather the trees in range, only their leafs.
I guess that its a bug.

**Comment by Alethephobe** [comment]
I replaced the gatherers and it works normally now. I have no clue what that was.

**Comment by Buuz135** [comment]
You can change the range of the machine in the config
