### ISSUE TITLE
Dissolution Chamber dupes some recipes

### ISSUE THREAD

**Issue by davqvist** [InnovativeOnlineIndustries/Industrial-Foregoing#730]
Industrial Foregoing Version: 2.2.2-28d4a81
Forge: 31.1.41

I have the folllowing datapack recipes with CraftTweaker:
https://pastebin.com/Bt9EbDy8

But this way and no matter how I change it, those recipe get processed twice.
Meaning, the recipe gets executed and I get the result item, but the input is not consumed at first, then it gets consumed and I get the output item a second time.

**Comment by davqvist** [comment]
Just as a quick addition, I just updated to 2.3.0 and I found out in testing that even some normal unchanged recipes behave like that, like the Pink Sllime ball recipe where you get 2 slime balls from one glass pane.

**Comment by Buuz135** [comment]
Ohh! So its the machine! Thanks for the info!
