### ISSUE TITLE
Have the Villager Trade Exchanger work with other shop mobs

### ISSUE THREAD

**Issue by ouroborus** [InnovativeOnlineIndustries/Industrial-Foregoing#735]
Some other mods have mobs that trade. It'd be great if those could be harnessed in the Villager Trade Exchanger. For example, Electroblob's Wizardry wizards.

I understand that you might not want to make special exceptions in code for different mods, so if there's not an API for other mods to hook into for this, I'd like to suggest adding that at least.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
