### ISSUE TITLE
Crafting Table - Serverside Crash?

### ISSUE THREAD

**Issue by StormyMode** [InnovativeOnlineIndustries/Industrial-Foregoing#736]
Industrial Foregoing Version: 2.2.2 (mc1.15)
TeslaCoreLib Version: N/A
Crashlog (If Any): https://pastebin.com/W8sLSjkg

Description: An apparent issue with Industrial Foregoing when using related items in a crafting table (this also includes crafting terminals from RS). This results in a server crash, a reboot will fix it until the same instance happens again. Any ideas?

**Comment by Quu1337** [comment]
Having same issue, blamed morph-o-tool for it, not sure whats the correct issue

https://github.com/Vazkii/Morph-o-Tool/issues/54
