### ISSUE TITLE
Fluid Pump does not work in Ocean oil wells

### ISSUE THREAD

**Issue by Rithenar** [InnovativeOnlineIndustries/Industrial-Foregoing#737]
EDIT 4/25 - I found another oil well in the ocean and found that the same thing happened on this one. Oil that is found on wells in solid ground (not Ocean) do not have problems being extracted with the pump

Industrial Foregoing Version:  1.12.13 (1.12.2-1.12.2)
TeslaCoreLib Version:  1.12.2-1.0.17
Crashlog (If Any): 

I have been using the fluid pump in oil wells with no issues until now. For some reason, the pump will not work with this oil well. I followed the same steps as always:

1- Place Pump directly above source block
2- give appropriate range add on (+3 in this case)
3- Connect ender fluid conduit and ender tank
4- Power the pump

Not only will not pump oil from source blocks bit even if I take the range upgrade out (which I usually have to do to clean up the middle section of the well which doesn't pump with a range add on), it will not pump anything at all.  I also tried a +9 and a +12 range add on with same result.  Here is the setup:

Pump setup
![image](https://user-images.githubusercontent.com/9939332/80227982-12bc0000-8614-11ea-81fb-438b36ea4715.png)

Here is the pump GUI
![image](https://user-images.githubusercontent.com/9939332/80228017-21a2b280-8614-11ea-80b9-74876875d9a1.png)

And the oil well
![image](https://user-images.githubusercontent.com/9939332/80228059-2a938400-8614-11ea-987d-1e0595fdde91.png)

thanks.

**Comment by webbster64** [comment]
Ive got the same problem with version 1.12.13, is started working fine then suddenly stopped working and my range upgrade disappeared, 

Ive tried moving it to an other oil well but no luck still doesn't work, deleted the pump and spawned in a new one also no worky 

then tested it on water it worked and then again on the oil, still not working so

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
