### ISSUE TITLE
Energy Field Provider not working

### ISSUE THREAD

**Issue by 3lfedor** [InnovativeOnlineIndustries/Industrial-Foregoing#738]
Industrial Foregoing Version: 1.11.2
TeslaCoreLib Version: 1.11.2
Crashlog (If Any): 

My understanding of the Energy Field Provider and Energy Field Addon was that when provided with power, the Energy Field Provider would charge all Energy Field Addons in range. This is not working. I can charge it in my Biofuel generator, and use a charged addon to power my equipment, but the provider does not charge the addons near it.

**Comment by Buuz135** [comment]
Update the mods and make sure both of them are linked by rightclicking the addon to the provider
