### ISSUE TITLE
Config option to make all items under one creative tab

### ISSUE THREAD

**Issue by kmecpp** [InnovativeOnlineIndustries/Industrial-Foregoing#739]
Can we have a config option to make everything appear under one creative tab?

**Comment by Buuz135** [comment]
No?

**Comment by kmecpp** [comment]
Why? IF takes up literally 7 creative tabs for no reason. That's annoying enough for me to completely not use the mod at all

**Comment by kphill11** [comment]
I agree with this. Taking up 7 tabs is pretty obnoxious for any mod since it gets really annoying on large modpacks.

**Comment by kphill11** [comment]
I agree with this. Taking up 7 tabs is pretty obnoxious for any mod since it gets really annoying on large modpacks.
