### ISSUE TITLE
1.15 Server Crash with akashic tome

### ISSUE THREAD

**Issue by Darkere** [InnovativeOnlineIndustries/Industrial-Foregoing#740]
Industrial Foregoing Version: industrial-foregoing-1.15.2-2.2.2-28d4a81

Crashlog (If Any): https://gist.github.com/Darkere/6d92988b82b4276a93bebe6dc57da23a

This line: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/80239ece88b8083f9a64118b746d0487da8f88d9/src/main/java/com/buuz135/industrial/block/MachineFrameBlock.java#L60 

is crashing as it's clientside only.

**Comment by Buuz135** [comment]
Duplicate #736

**Comment by Darkere** [comment]
The fix you made does not apply to the crash above.

**Comment by Buuz135** [comment]
Yes it do, its the same one

**Comment by Darkere** [comment]
Yeah, but for MachineFrameBlock you are extending BlockItem and not IFCustomItem. I even linked the line above...

**Comment by Buuz135** [comment]
Oh! You should have said that! I didnt even noticed.

**Comment by Darkere** [comment]
oof also in conveyor and industrial block.
