### ISSUE TITLE
Items count blinking when accessed via AE2 storage bus

### ISSUE THREAD

**Issue by quasarea** [InnovativeOnlineIndustries/Industrial-Foregoing#741]
Industrial Foregoing Version: 1.12.13
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): none

When:
* machine, i.e. Material Stonework Factory:
** is set to make i.e sand (replicated with gravel, silicon, etc)
** has ae2 storage bus attached (in my case from the bottom)
* additionally some number (1) of the items produced is also stored in attached chest 
Then the items count on ae2 terminals keeps changing constantly - making it unreadable.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
