### ISSUE TITLE
Machine upgrade slots are accessible (but blocked) from all sides and not configurable

### ISSUE THREAD

**Issue by quasarea** [InnovativeOnlineIndustries/Industrial-Foregoing#742]
Industrial Foregoing Version: 1.12.13
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): none

When machine has an upgrade in upgrade slot, this upgrade will be visible in attached via storage bus ae2 system 

When upgrade is deposited in ae2 system, it can be stored in one of machines attached via storage bus, but cannot be then taken out.

This could be fixed if we could choose side-accessibility for upgrade slots, like for any others.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
