### ISSUE TITLE
Range Upgrade gets deleted with inventory sorting

### ISSUE THREAD

**Issue by davqvist** [InnovativeOnlineIndustries/Industrial-Foregoing#746]
Industrial Foregoing Version: 2.3.0
Titanium: 2.4.0
with Inventory Sorter 17.0

To replicate:
1.) Put Fertilizer in a Fertilizer and a Range Upgrade in the Upgrade Slot
2.) Then middle mouse button inventory sort while hovering over the machine GUI
3.) The Range Upgrade gets voided

Not sure which mod is causing the issue though.

**Comment by Buuz135** [comment]
Nothing much I can do about it, I don't handle the sorting
