### ISSUE TITLE
Bio Fuel Generator, Right Click crash

### ISSUE THREAD

**Issue by MeinKraft** [InnovativeOnlineIndustries/Industrial-Foregoing#748]
**Industrial Foregoing Version:**  1.15.2-2.3.0-6f57752

**Titanium Version:**  1.15.2-2.4.0
Forge 31.1.74

**Crashlog If Applicable (Upload to pastebin/gist):** 
https://pastebin.com/iq8deF8K

If you right click the Bio Fuel Generator block from IndustrialForegoing the game crashes. Just place the block then click it

I reported on Titanium issue tracker too

**Comment by Scorch-Mechanic** [comment]
Just had this same crash. Here's my logs.
[latest.log](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/4587250/latest.log)
[crash-2020-05-06_07.05.25-client.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/4587252/crash-2020-05-06_07.05.25-client.txt)

**Comment by hbh7** [comment]
Having the same issue

**Comment by Buuz135** [comment]
Should be fixed in the latest Titanium
