### ISSUE TITLE
Sewer stopped collecting essence

### ISSUE THREAD

**Issue by davqvist** [InnovativeOnlineIndustries/Industrial-Foregoing#749]
Industrial Foregoing Version: 2.3.0
Titanium: 2.4.0

Updating from 2.2.2 to 2.3.0 and now suddenly the Sewer stopped collecting essence. I tried animal breeding, and bottles o enchanting, but it doesn't collect the XP orbs anymore, even with max Range Upgrades.

**Comment by noncom** [comment]
You *have* seen that I've reported the same issue with the Dissolution Chamber, right? :)
