### ISSUE TITLE
Pink Slime/Liquid Meat output chances reversed

### ISSUE THREAD

**Issue by blagdorfinguy** [InnovativeOnlineIndustries/Industrial-Foregoing#750]
Industrial Foregoing Version: 2.2.2
Titanium Version: 2.3.7 

I'm unsure if this is intended, but it feels like it isn't. When using the Mob Slaughter Factory (on cows in my case), it seems the output rates for Liquid Meat and Pink Slime have been reversed. Running for hours, I have nearly 10 buckets of pink slime, and less than 400 mB of Liquid Meat.

**Comment by Buuz135** [comment]
This is intended, animals produce more pink slime than other mobs
