### ISSUE TITLE
crash on server load up[1.15.2]

### ISSUE THREAD

**Issue by SDUBZ** [InnovativeOnlineIndustries/Industrial-Foregoing#751]
Industrial Foregoing Version: industrial-foregoing-1.15.2-2.3.0-6f57752
forge Version: 1.15.2- 31.1.74

Crashlog (If Any): 
[crash-2020-05-06_15.53.25-server.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/4587201/crash-2020-05-06_15.53.25-server.txt)

Logs:
[latest.log](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/4587206/latest.log)
[debug.log](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/4587208/debug.log)

**Comment by Buuz135** [comment]
Should be fixed in the latest titanium
