### ISSUE TITLE
Sewage composter not progressing on low power

### ISSUE THREAD

**Issue by xorinzor** [InnovativeOnlineIndustries/Industrial-Foregoing#756]
Industrial Foregoing Version: 1.15.2-2.3.0-6f57752
TeslaCoreLib Version: N/A

In my setup I have a limited power supply and cannot provide enough power to all machines. This would usually lead to slower production / activity, which isn't a problem for me.

But the Sewage Composter seems bugged, where the power buffer will charge to ~500FE and the progress will go to 1/100, but then instantly drop back to 0/100, and the power buffer will drop back to 0 FE too. This loops indefinitely.

Expected behaviour would be for the progress to increase much slower, based on the available power the machine has.

**Comment by Buuz135** [comment]
Fixed in dev, you can get a quick fix by changing the power consumption in the config from 400RF/t to 40RF/t
