### ISSUE TITLE
Game Freeze Whenever Defining Machine Side Input/Export

### ISSUE THREAD

**Issue by DizzyDJW** [InnovativeOnlineIndustries/Industrial-Foregoing#758]
Industrial Foregoing Version:  1.12.13-237
TeslaCoreLib Version: 1.0.17

Whenever I am using a machine from Industrial Foregoing and I attempt to configure the side inputs and outputs, the sounds of pages flipping happens just from hovering over the check/X boxes for each side and upon clicking into the interface to configure it, there is a several second pause which is worsened immensely upon actually changing a check to an X or vice versa.

Pack: MCEternal 1.3.5b (Unmodified)

Ways to Replicate: Place any machine from Industrial Foregoing and attempt to configure its sides within its GUI.

**Comment by Buuz135** [comment]
VanillaFix problem
