### ISSUE TITLE
Black hole tank crashes the game when loading world

### ISSUE THREAD

**Issue by okkokko10** [InnovativeOnlineIndustries/Industrial-Foregoing#762]
Industrial Foregoing Version: 1.12.12
TeslaCoreLib Version: 1.12.2-1.0.15
Crashlog (If Any): 
[crash-2020-05-17_14.58.13-server.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/4640242/crash-2020-05-17_14.58.13-server.txt)
I could enter the world after I turned workDisabled on for the black hole tank.
In my SkyFactory4 world, I had a black hole tank connected to a cow in a jar, a block that constantly generates milk, with Integrated Tunnels' fluid importer. In this photo I placed a block of redstone where the tank used to be:
![image](https://user-images.githubusercontent.com/28782719/82147256-365f1880-9857-11ea-98ee-21ba1fb6be9d.png)

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
