### ISSUE TITLE
Enchantment applicator destroys enchanted book stack

### ISSUE THREAD

**Issue by Machine-Maker** [InnovativeOnlineIndustries/Industrial-Foregoing#763]
Industrial Foregoing Version: 1.12.13
TeslaCoreLib Version: 1.0.17
Crashlog (If Any): 

Inside the enchantment applicator, you can put a stack of enchanted books... but when you put an item to be enchanted, it destroys all the enchanted books in the book slot to enchant 1 item.

**Comment by beanaboston** [comment]
Confirming this bug.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
