### ISSUE TITLE
Issue with Mekanism power cables & machine pauses

### ISSUE THREAD

**Issue by xJon** [InnovativeOnlineIndustries/Industrial-Foregoing#764]
`Industrial Foregoing Version: 1.12.2-1.12.13-237`
`TeslaCoreLib Version: 1.12.2-1.0.17`

Reported to my modpack over https://github.com/xJon/The-1.12.2-Pack/issues/409:
> Industrial foregoing machines have a button to pause and unpause the work of the machine. If you connect Mekanism cables to any industrial foregoing machine for energy supply and then pause the machine and reload the game, re-enabling the machine on next startup will cause the machine to not draw power from the cable. You need to manually replace the cable or re-configure the cable from normal to push for example.

> Reproduction:
Build an industrial foregoing machine
Connect power to it via Mekanism cables
Pause the machine (make sure it actually has work to do and pulls power)
Quit to main menu
Reload world
Unpause the machine --> it won't draw power from the cable until you either break the cable and place a new one or you change the cable mode via the Mekanism configurator
I only ever noticed this behavior on industrial foregoing machines.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
