### ISSUE TITLE
Potion Brewer: Can't craft Potion of Weakness

### ISSUE THREAD

**Issue by syruppp** [InnovativeOnlineIndustries/Industrial-Foregoing#766]
Industrial Foregoing Version: 1.12.2-1.12.13-237
TeslaCoreLib Version: 1.12.2-1.0.17
Crashlog (If Any): 

The Potion Brewer won't allow any potions to be crafted that don't start with Awkward Potions. This prevents crafting of potions such as Potion of Weakness and its splash variant as it starts with fermented spider eye.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
