### ISSUE TITLE
BioReactor causing Stack Overload, causing Server to crash

### ISSUE THREAD

**Issue by SayulilyonPipeDream** [InnovativeOnlineIndustries/Industrial-Foregoing#771]
Industrial Foregoing Version: 2.1.2 (on MC 1.14.4)
TeslaCoreLib Version: N/A
Crashlog (If Any): Attached, see below.

To fix the issue on the server, we had to change the bioreactor to stone. Any attempts to load that block before would crash the server.

[crash-2020-05-29_20.47.55-server.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/4703824/crash-2020-05-29_20.47.55-server.txt)

**Comment by Buuz135** [comment]
Update to 2.3.2
