### ISSUE TITLE
Gears were removed from 1.15.2

### ISSUE THREAD

**Issue by Aevaris** [InnovativeOnlineIndustries/Industrial-Foregoing#772]
Industrial Foregoing Version: 2.3.2
TeslaCoreLib Version: 
Crashlog (If Any): 

It seems all gears have been removed from the 1.15.2 version, so the recipes don't work for most machines now.

![image](https://user-images.githubusercontent.com/9640671/83336270-a28a4500-a277-11ea-99da-777be4f3dd4c.png)

**Comment by Buuz135** [comment]
Update titanium
