### ISSUE TITLE
[1.12] Issue Title

### ISSUE THREAD

**Issue by alexHunter854** [InnovativeOnlineIndustries/Industrial-Foregoing#774]
**Industrial Foregoing Version:1.12.13**

**TeslaCoreLib Version:1.0.17**

I put in a mob with 0.04 health and it rounded it down and had a divide by 0 error

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
