### ISSUE TITLE
[1.12] Inverted Laser Lenses can cause server crash 

### ISSUE THREAD

**Issue by robertmaxton42** [InnovativeOnlineIndustries/Industrial-Foregoing#775]
**Industrial Foregoing Version:** 1.12.13

**TeslaCoreLib Version:** 1.12.2-1.0.17

**Crashlog If Applicable (Upload to pastebin/gist):** https://pastebin.com/czT1kmJx

I've attached the crashlog on general principles, but I'm pretty sure I've found the relevant line. After [line 196 of LaserBaseTile.java](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/ff3afe62fcab65e4dcd8cca52ca31e6595a48cd8/src/main/java/com/buuz135/industrial/tile/world/LaserBaseTile.java#L196), the weighting of each ore is not subject to bounds checking after being adjusted by the list of lenses. If it should so happen that there are enough inverted lenses that the total weight is negative, `WeightedRandom.getRandomItem` will throw an exception and crash. As you can see above.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
