### ISSUE TITLE
[1.12] Duplication bug with conveyors under certain circumstances

### ISSUE THREAD

**Issue by Saereth** [InnovativeOnlineIndustries/Industrial-Foregoing#776]
**Industrial Foregoing Version:**

industrialforegoing-1.12.2-1.12.13-237.jar
--

**TeslaCoreLib Version:**

tesla-core-lib-1.12.2-1.0.17.jar
--

**Crashlog If Applicable (Upload to pastebin/gist):**
This was originally posted on the interactions github, relevant bug report
https://github.com/FTBTeam/FTB-Interactions/issues/881

Basically you can use conveyors to dupe some items under specific circumstances

**Comment by SSKirillSS** [comment]
Any info about fix? Month has passed :c

**Comment by Buuz135** [comment]
![Discord_2020-07-11_12-06-48](https://user-images.githubusercontent.com/3874674/87221792-16d40000-c36f-11ea-88bc-2700f187f90a.png)

**Comment by SSKirillSS** [comment]
Sorry, didn't notice

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
