### ISSUE TITLE
[1.15] Sewage Composter can produce Fertilizer with water

### ISSUE THREAD

**Issue by fishpicklepasta** [InnovativeOnlineIndustries/Industrial-Foregoing#777]
**Industrial Foregoing Version:** 1.15-2.3.2

**Titanium Version:** 1.15.2-2.4.1

**Crashlog If Applicable (Upload to pastebin/gist):**

**Comment by Buuz135** [comment]
Can you explain the issue better?

**Comment by fishpicklepasta** [comment]
I accidentally sucked some water into a Sewage Composter with xNet cables and it started to produce fertilizer on its own. There wasn't any sewage in the composter when it made the fertilizer.
