### ISSUE TITLE
[1.15] Biofuel Generator GUI causes divide by 0 crash

### ISSUE THREAD

**Issue by SmolFloofyRedhead** [InnovativeOnlineIndustries/Industrial-Foregoing#778]
**Industrial Foregoing Version:2.3.0**

**Titanium Version:2.4.0**

**Crashlog If Applicable (Upload to pastebin/gist): https://pastebin.com/AkTsYyTj**

I was playing FTB Omnia, trying to get a biofuel setup working, and when I right clicked the empty biofuel generator (no biofuel, no power), I got a divide by 0 crash from it trying to render the power meter.

**Comment by Buuz135** [comment]
Update titanium
