### ISSUE TITLE
[1.15] Biofuel Generator makes free infinite power

### ISSUE THREAD

**Issue by dmliscinsky** [InnovativeOnlineIndustries/Industrial-Foregoing#781]
**Industrial Foregoing Version:** 2.3.2

**Titanium Version:** 2.4.0

Biofuel Generator stops consuming biofuel and consequently generates infinite power for free. 

(Note: I am using the Flux Networks mod (version 1.15.2-5.0.1-2) for FE transportation and storage).

-- Setup (4 x 3 x 3 area) --
Front View: 
```
            [ Flux Plug ] [Flux Point]
[Flux Plug] [Biofuel Gen] [Bioreactor]
            [ Flux Plug ] [Water Condenser] [Water]
```
Top View: 
```
            [ Flux Plug ] [   Water  ]
[Flux Plug] [ Flux Plug ] [Flux Point] [Water]
            [ Flux Plug ] 
```
Reference Image:
![image](https://user-images.githubusercontent.com/22301555/84347307-2bf71c80-ab80-11ea-96a3-6542c8e212d3.png)

(Note: in the image, there are two hoppers feeding items from chests into the Biofuel Reactor, but this does not affect the issue; the bug occurred before with this same setup without hoppers present).

The amount of FE being consumed is rather low (essentially only the Bioreactor and Water Condenser are drawing FE, maybe also a Latex Processor), while the output of the Biofuel Generator is an order of magnitude larger.

I am unsure at exactly what triggers the bug, but it has happened twice in two different worlds with this same setup. No more items in the Bioreactor are consumed after the bug triggers. My best guess is that it triggered when my Flux Storage and Biofuel Generator internal FE buffer became full.

**Comment by Buuz135** [comment]
Have you checked if its a Flux Plug issue?

**Comment by woutwoot** [comment]
I'm seeing the same issue. 
I'm using Refined Pipes for energy transport. (https://www.curseforge.com/minecraft/mc-mods/refined-pipes)

**Comment by boneskull** [comment]
I seem to be having a similar issue... it  seems to generate a lot more FE than it should.  Also using 1.15.2 and refined pipes.

**Comment by woutwoot** [comment]
Slightly unrelated: I added Mekanism to my pack and started using the generators it provides. Never looked back 🙂

**Comment by DKnightADRI** [comment]
I've recently got another person with the same issue so I replicated it using only 3 mods:

Industrial Foregoing 1.15.2-2.3.3
Titanium 1.15.2-2.4.2

For checking power generation
Mekanism 1.15.2-9.10.9.422

Setup: https://imgur.com/a/9nZlou9

I'm pretty sure there's something wrong with the progress process that causes this to happen, it freezes at the value seen in the screenshot below.

**Comment by ab9rf** [comment]
Having the same issue with 1.16.4, using Cyclic energy pipes and Immersive Engineering wires for transport.

Forge 35.1.13
Industrial Foregoing 1.16.4-3.2.5-74675d6
Cyclic 1.16.4-1.0.0
Immersive Engineering 1.16.4-4.1.2-129

**Comment by Buuz135** [comment]
Should be fixed in the latest titanium
