### ISSUE TITLE
[1.12] Duplication bug

### ISSUE THREAD

**Issue by SSKirillSS** [InnovativeOnlineIndustries/Industrial-Foregoing#782]
**Industrial Foregoing Version:** industrialforegoing-1.12.2-1.12.13-237

**TeslaCoreLib Version:** tesla-core-lib-1.12.2-1.0.17

Check the video: https://www.youtube.com/watch?v=Uv-_ZwIMH9I

**Comment by Buuz135** [comment]
Duplicate of #776
