### ISSUE TITLE
[1.12] Black Hole Controller unlocks the BH units' inventory

### ISSUE THREAD

**Issue by Porcy** [InnovativeOnlineIndustries/Industrial-Foregoing#783]
**Industrial Foregoing Version:*1.12.13-237*

**TeslaCoreLib Version:*1.0.17*

**Crashlog If Applicable (Upload to pastebin/gist):**
Just noticed that when I put a black hole unit that I locked ('Lock inventory' button) inside a black hole controller, it gets unlocked. That allows for my AE system to insert anything in it if it ever gets emptied :/

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
