### ISSUE TITLE
[1.15] 2.3.3 Crashes with PneumaticCraft installed

### ISSUE THREAD

**Issue by ZigTheHedge** [InnovativeOnlineIndustries/Industrial-Foregoing#785]
**Industrial Foregoing Version:**
2.3.3
2.3.2 - works ok

**Titanium Version:**
2.4.0

**Crashlog If Applicable (Upload to pastebin/gist):**
https://pastebin.com/i1yEaGGM

**Comment by Buuz135** [comment]
There is no mention of IF there, also update titanium first.
