### ISSUE TITLE
[1.15] Crash on startup

### ISSUE THREAD

**Issue by remplerus** [InnovativeOnlineIndustries/Industrial-Foregoing#787]
After upgrading to Industrial Foregoing 2.3.3 Minecraft crashes every time i start it. If I go back to 2.3.2 everything starts fine.

Industrial Foregoing Version: 2.3.3
Titanium Version: 2.4.0

Latest.log: [https://pastebin.com/PJxTCBQZ](https://pastebin.com/PJxTCBQZ)
(Crashlog if you need it: [https://pastebin.com/YcTgv19L](https://pastebin.com/YcTgv19L) )

**Comment by Buuz135** [comment]
Update titanium
