### ISSUE TITLE
[1.15] Mechanical Dirt Spawning Issue

### ISSUE THREAD

**Issue by Shadow-WolfDemon** [InnovativeOnlineIndustries/Industrial-Foregoing#788]
Industrial Foregoing Version:2.3.2

Titanium Version:2.4.1

Modpack: Valhelsia 2 Version: 2.2.2a

I've noticed that mechanical dirt will only spawn mobs if there is a block underneath the dirt after a bunch of testing with a single player and server, of trying to figure out why I was unable to spawn anything but my creative tests would I found out the only differences between the setups were that my survival play through did not have a block underneath the dirt as I was piping into the bottom not the side where as my creative tests I had blocks underneath.

**Comment by Buuz135** [comment]
Fixed in the 1.16 version, the 1.15 support is unsupported
