### ISSUE TITLE
[1.12] Plant Interactor in Compact Machine crashes save during launch

### ISSUE THREAD

**Issue by MBfromOK** [InnovativeOnlineIndustries/Industrial-Foregoing#793]
**Industrial Foregoing Version:**
    1.12.2-1.12.13-237
**TeslaCoreLib Version:**
    1.0.15
**Crashlog If Applicable (Upload to pastebin/gist):**
    https://pastebin.com/3a8VQ4t9

I have 3-4 Plant Interactors growing crops in several 13x13x13 Compact Machines.  For some reason when I launch the game it crashes (See block entity being ticked data in pastebin). Game ran fine last night and I did a backup right before shutting down.. I will see if recovering a backup resolves the issue or allows the save to launch.

**Comment by Buuz135** [comment]
Discord Integration Issue

**Comment by MBfromOK** [comment]
Confirmed: Save launches after disabling Discord mod.
