### ISSUE TITLE
[1.12] Mystical Fertilizer

### ISSUE THREAD

**Issue by G1R-Productions** [InnovativeOnlineIndustries/Industrial-Foregoing#794]
**Industrial Foregoing Version:**
industrialforegoing-1.12.2-1.12.13-237
**TeslaCoreLib Version:**
tesla-core-lib-1.12.2-1.0.17

The fertilizer machine does not accept Mystical Fertilizer as an acceptable fertilizer.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
