### ISSUE TITLE
[1.12] Unknown Crash, please help!

### ISSUE THREAD

**Issue by LonelySauce** [InnovativeOnlineIndustries/Industrial-Foregoing#795]
**Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.13-237

**TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.17

**Crashlog If Applicable (Upload to pastebin/gist): https://pastebin.com/mxFk2f3T

I'm not sure what could've caused this crash but I'm hoping you can release a fix for it quickly!
Sidenote: VanillaFix detected a hard crash instead of a soft crash while loading the game.
-Sauce

**Comment by Buuz135** [comment]
Make a smaller pack, you have too many blocks and items
