### ISSUE TITLE
[1.12] Pink Slime liquid adheres to no mob cap

### ISSUE THREAD

**Issue by Shovinus** [InnovativeOnlineIndustries/Industrial-Foregoing#796]
This is likely not normally an issue ... until you generate an RFTools dimension with said liquid, and it crashes the server as millions of the things spawn - even in peaceful

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
