### ISSUE TITLE
[1.16.1] Internal Exception: java.lang.NullPointerException when joining a Server.

### ISSUE THREAD

**Issue by Gbergz** [InnovativeOnlineIndustries/Industrial-Foregoing#798]
**Industrial Foregoing Version:**
3.0.0-f8b04de

**Titanium Version:**
3.0.0

**Issue**
![image](https://user-images.githubusercontent.com/26634554/88091820-e1f65300-cb8f-11ea-8d06-2335b299216a.png)

**Comment by Buuz135** [comment]
I need logs

**Comment by Gbergz** [comment]
Client latest.log
https://hastebin.com/hedovogino.coffeescript

**Comment by Gbergz** [comment]
debug.log
https://hastebin.com/efatixonas.md

**Comment by Gbergz** [comment]
Server latest logs:
https://hastebin.com/yirenumujo.sql

Server latest debug:
https://hastebin.com/gayokiqupa.md

**Comment by Gbergz** [comment]
Still happens with updated file [3.0.1-f3c15d2](https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing/files/3010897)

**Comment by Buuz135** [comment]
Can you try to use forge 32.0.71?

**Comment by Gbergz** [comment]
Tried it, same thing.

**Comment by Buuz135** [comment]
Fixed in https://github.com/InnovativeOnlineIndustries/Titanium/commit/85ec91d191686eb92eb0ffeb05f90b98fc821ce5 grab the update in a bit
