### ISSUE TITLE
Block placer / Block breaker facing

### ISSUE THREAD

**Issue by DStrand1** [InnovativeOnlineIndustries/Industrial-Foregoing#800]
**Is your feature request related to a problem? Please describe.**
Block placer and breaker can only be facing N/S/E/W.

**Describe the solution you'd like**
Allow block placer to be facing U/D as well.

**Additional context**
Would like to be able to automate latex production without having to use another mod for block placing, since ideally I'd have 4 Tree Fluid Extractors around the log, and the Block Placer placing the block from top or bottom.

**Comment by Buuz135** [comment]
You can already do that
