### ISSUE TITLE
[1.16] Mechanical Dirt - Tick Block Entity error

### ISSUE THREAD

**Issue by papaworld** [InnovativeOnlineIndustries/Industrial-Foregoing#801]
MC - 1.16.1
FML - 32.0.71
Titanium - 3.0.1
IF - 3.0.2  78e809f

Created a test world for Mechanical Dirt and Slaughter machines. Would not spawn mobs. With Mechanical Dirt GUI open game crashed with the following report:

[crash-2020-07-21_18.33.09-server.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/4957007/crash-2020-07-21_18.33.09-server.txt)

Sorry, I did not understand how to use the pastebin/gist thingie.

**Comment by DStrand1** [comment]
https://pastebin.com/ZkMZbNH0

**Comment by papaworld** [comment]
Tried the Mechanical Dirt again in a new test world and just let it sit there with no interaction from me. The same crash occurred within 3 minutes. No mobs spawned on the Dirt.
