### ISSUE TITLE
[1.12.2] Plant Sower not placing seeds on fertilized ground

### ISSUE THREAD

**Issue by dasmou** [InnovativeOnlineIndustries/Industrial-Foregoing#803]
I noticed that the plant sower does not plant any seeds on fertilized_ground provided by the "hatchery" mod which is included in the stoneblocks 2 modpack.

I already found the reason for it. 
In line 139 from the CropSowerTile.java file it checks if the block is dirt, but not if the block maybe is fertilized farmland. 

So can i somehow add it in order to get it to work?

here a screenshot showing the item's name:
![2020-07-23_11 24 10](https://user-images.githubusercontent.com/68687343/88271219-22acb400-ccd7-11ea-8321-d6762cf4b7ca.png)

thanks for helping out!

br,
m0u

**Comment by dasmou** [comment]
any updates on this?

**Comment by dasmou** [comment]
bump

**Comment by dasmou** [comment]
bump

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
