### ISSUE TITLE
[1.16] Server crash from simple machine frame recipe

### ISSUE THREAD

**Issue by EPostill** [InnovativeOnlineIndustries/Industrial-Foregoing#805]
Playing on Enigmatica 6 v0.2.0

**Industrial Foregoing Version:** 3.0.1

**Titanium Version:** 3.0.1

**Crashlog If Applicable (Upload to pastebin/gist):**
https://pastebin.com/d9eZ6KQZ

**Comment by Buuz135** [comment]
Update IF
