### ISSUE TITLE
[1.16.1] Dissolution Chamber crash.

### ISSUE THREAD

**Issue by Gbergz** [InnovativeOnlineIndustries/Industrial-Foregoing#806]
Title^
Crash happened on a server.

**Minecraft:** 1.16.1
**Forge:** 32.0.75
**Industrial Foregoing Version:** 3.0.3-5935836
**Titanium Version:** 3.0.2

**Crashlog:** https://hastebin.com/uyizijazeh.pl

**-** Gbergz

**Comment by jakedecker** [comment]
Similar crash

https://pastebin.com/c1se0Upr

**Comment by Dyllan2000alfa** [comment]
Had the same thing happen to me. A few things to add I noticed when testing things. Server starts up fine and only crashes when player tries to join. Also based on what players where on in the crash log the error didn't occur until all players left and I rejoined so the issue may be cause by weirdness with unloading and loading.

Crash log: https://hastebin.com/abobonulay.pl

**Comment by Buuz135** [comment]
@Dyllan2000alfa thats an IF issue
@jakedecker you issue can be fixed by updating the mod

**Comment by Buuz135** [comment]
Fixed in https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/commit/dd536af55a046ec5989568fac1941480ec849bfd#diff-b1cefe7734ce48dcc9d424643e83da6f
