### ISSUE TITLE
[1.16] Tiny dry rubber to dry rubber

### ISSUE THREAD

**Issue by ZEROX7** [InnovativeOnlineIndustries/Industrial-Foregoing#807]
**Industrial Foregoing Version:** 

industrial-foregoing-1.16.1-3.0.3-5935836.jar

**Titanium Version:** titanium-1.16.1-3.0.2.jar

hey there i am playing on a server, i can see the dry rubber recipe but i cant craft it
https://i.imgur.com/pcE5X7t.png

**Comment by Buuz135** [comment]
Can you restart the server and check if it works?

**Comment by NoahJGersh** [comment]
I can replicate this on a multiplayer server, and same instance works fine in singleplayer. Contacted server owner for a restart, so I'll update here if that fixes anything.

Industrial foregoing version is the same, as is Titanium. Running Forge 32.0.75.

**Comment by Buuz135** [comment]
Does it happen with just IF and Titanium?

**Comment by NoahJGersh** [comment]
Just got a quick server set up, hosted locally, and it doesn't. I'm going to do some digging into the problematic instance's logs and see if it's some weird recipe conflict issue with another mod.

**Comment by NoahJGersh** [comment]
Finally found a minimal reproducible setup. There appears to be something wrong with Placebo's recipe registration for FastWorkbench that doesn't play nicely with BiomesOPlenty.

Can be reproduced with the following setup:
Industrial Foregoing
Titanium
BiomesOPlenty
FastWorkbench
Placebo (required by FastWorkbench)

Using either BiomesOPlenty, or FastWorkbench, but not both, actually works. It's the interaction between the two that was causing issues.

**Comment by ZEROX7** [comment]
well i dont have biomnesoplenty installed and still have the issue XD

**Comment by NoahJGersh** [comment]
What's your modlist?

**Comment by ZEROX7** [comment]
Bookshelf (by DarkhaxDev)
Simple Planes (by przemykomo)
Explosion't (by FishSound)
Just Enough Items (JEI) (by mezz)
Nether Portal Spread (by Serilum)
Toast Control (by Shadows_of_Fire)
Mekanism Additions (by bradyaidanc)
Infinity Works With All Arrows (by tfarecnim)
Culinary Construct (by TheIllusiveC4)
Extra Boats (by Markus1002)
Refined Storage Addons (by raoulvdberge)
Enchantment Descriptions (by DarkhaxDev)
CC: Tweaked (by SquidDev)
Light Overlay (Rift/Forge/Fabric) (by shedaniel)
Gauges and Switches (by wilechaote)
CleanCut (by Rongmario)
Prefab (by wuestman)
Player Plates (Forge) (by Gaz_)
ConnectedTexturesMod (by tterrag1098)
Waystones2Waypoints (by Noobanidus)
Village Spawn Point (by Serilum)
Engineer's Decor (by wilechaote)
ReAuth (by TechnicianLP)
Powah! (by owmii)
Storage Drawers (by Texelsaur)
No Hostiles Around Campfire (by Serilum)
Enchantments Reloaded (by Seanboyy11)
Connected Glass (by SuperMartijn642)
Unity: Extras (by theCyanideX)
AppleSkin (by squeek502)
Industrial Foregoing (by Buuz135)
Lollipop (by owmii)
Double Slabs (by CJMinecraft01)
GraveStone Mod (by henkelmax)
Cloth Config API (Forge) (by shedaniel)
Waystones (by BlayTheNinth)
Engineer's Tools (by wilechaote)
Xaero's World Map (by xaero96)
Gotta Climb Fast! (by Rongmario)
🥝 Kiwi (by Snownee_)
The One Probe (by McJty)
U Team Core (by HyCraftHD)
Silent Lib (by SilentChaos512)
Vampirism - Become a vampire! (by maxanier)
Vanilla Hammers [Forge] (by MelanX)
Bedspreads (by TheIllusiveC4)
World Pre Generator (by GeheimagentNr1)
☃ Snow! Real Magic! (by Snownee_)
Trash Cans (by SuperMartijn642)
Dwarf Coal (by traverse_joe)
Double Doors (by Serilum)
Portality (by Buuz135)
BannerAdditions (by EliteAsian123)
EverPotion (by Snownee_)
Titanium (by hrznstudio)
Silent Gear (by SilentChaos512)
Coloured Tooltips (by DarkhaxDev)
Map Tooltip (by VendoAU)
Immersive Engineering (by BluSunrize)
FastFurnace (by Shadows_of_Fire)
Guard Villagers (by almightytallestred)
Enderthing (by gigaherz)
Useful Backpacks (by HyCraftHD)
Shulker Tooltip (by ZephaniahNoah)
Tool Stats (by DarkhaxDev)
🌳 Passable Foliage (by Snownee_)
MixinBootstrap (by LX_Gaming)
WorldEdit (by sk89q)
Caelus API (by TheIllusiveC4)
Ranged Pumps (by raoulvdberge)
Wormhole (Portals) (by SuperMartijn642)
Improved Stations (Forge) (by shedaniel)
Macaw's Windows (by sketch_macaw)
Morpheus (by Quetzi)
Refined Storage (by raoulvdberge)
OpenBlocks Elevator (by vsngarcia)
Better minecart rotation (Forge) (by KosmX)
Mekanism (by bradyaidanc)
YUNG's Better Caves (by YUNGNICKYOUNG)
Vampires Need Umbrellas (by Focamacho)
Neat (by Vazkii)
Get exp for everything (by gosvoh)
Mekanism Generators (by bradyaidanc)
Colytra (by TheIllusiveC4)
Ultimate Car Mod (by henkelmax)
Ma Enchants (by Maciej916)
Mekanism Tools (by bradyaidanc)
Pocket Storage (by Flanks255)
Enchantable Horse Armor Forge (by tfarecnim)
Miner's Helmet (by ModdingLegacy)
Campfire Torches (by enemeez1)
Flour Power (by Anteater46)
Farming for Blockheads (by BlayTheNinth)
Tool Belt (by gigaherz)
Overloaded Armor Bar (by tfarecnim)
Enchanted Book Redesign (by tfarecnim)
Regrowth (by MacTso)
Polymorph (Forge) (by TheIllusiveC4)
NetherPortalFix (by BlayTheNinth)
Mahou Tsukai (by stepcros)
Artifacts (by ochotonida)
Drawers Tooltip (by Snownee_)
Unity: Modded (by theCyanideX)
StepUp (by NotTooManyItems)
Cooking for Blockheads (by BlayTheNinth)
Quark (by Vazkii)
🌟 Lighting Wand (by Snownee_)
Netherite Horse Armor Mod (by louie_cai)
Bag of Yurting (by Commoble)
Just Enough Resources (JER) (by way2muchnoise)
Cosmetic Armor Reworked (by LainMI)
Botany Pots (by DarkhaxDev)
XP Tome (by bl4ckscor3)
Actually Useful Smithing Table (by Rohzek)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Better Than Mending (by legobmw99)
Carpet Stairs Mod (by EndlesNights)
Inventory HUD+ (Forge) (by dmitrylovin)
Decorative Blocks (by stohun)
Macaw's Bridges (by sketch_macaw)
Collective (by Serilum)
Snow Under Trees (by bl4ckscor3)
Move Boats (by Serilum)
Dragon Drops Elytra (by Serilum)
Reap Mod (by henkelmax)
Security Craft (by Geforce132)
Unity (by theCyanideX)
Better Advancements (by way2muchnoise)
Dank Storage (by tfarecnim)
Comforts (by TheIllusiveC4)
Quark Oddities (by Vazkii)
MoreVanillaLib (by MelanX)
Iron Chests (by ProgWML6)
AutoRegLib (by Vazkii)
Move Minecarts (by Serilum)
Fast Leaf Decay (by olafskiii)
Builders Crafts & Additions (Forge) (by MRHminer)
Lamp Block (by br4nder5)
Iron Shulker Boxes (by ProgWML6)
JEI Enchantment Info (by Phylogeny)
Vanilla Excavators [Forge] (by MelanX)
Curios API (Forge) (by TheIllusiveC4)
IamMusicPlayer (by morimori0317)
Simple Magnets (by SuperMartijn642)
Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
Better Bedrock Generator (by JayJay1989BE)
BountifulBaubles (by Cursed1nferno)
Mod Name Tooltip (by mezz)
FastWorkbench (by Shadows_of_Fire)
Healing Campfire (by Serilum)
Armor Toughness Bar (by tfarecnim)
Actually Useful Stonecutter (by Rohzek)
Unity: Dark Edition (by theCyanideX)
Extra Disks (by MelanX)
Inventory Tweaks Renewed (by yuitakaa)
Mouse Tweaks (by YaLTeR)
Curio of Undying (Forge) (by TheIllusiveC4)
Falling Tree (by RakSrinaNa)
Easy Elytra Takeoff (by Serilum)
Macaw's Doors (by sketch_macaw)
Harvest Sprites (by MongoTheElder)
Controlling (by Jaredlll08)
Xaero's Minimap (by xaero96)
Curious Shulker Boxes (Forge) (by TheIllusiveC4)
Ma Essentials (by Maciej916)
FTB Ultimine (by LatvianModder)
Placebo (by Shadows_of_Fire)
Curious Elytra (by TheIllusiveC4)

**Comment by NoahJGersh** [comment]
Issue located, and fixed in Placebo 4.0.2:
https://github.com/Shadows-of-Fire/Placebo/commit/b0af7f38a1c73d85b61461d57c76d5a5cbb4f6ae

**Comment by Buuz135** [comment]
Fixed ^
