### ISSUE TITLE
[1.16] Enchantment Extractor

### ISSUE THREAD

**Issue by dj-holy** [InnovativeOnlineIndustries/Industrial-Foregoing#808]
industrial-foregoing-1.16.1-3.0.3-5935836.jar

When opening the Echnantment Extractor it immediatley opens the Essence Sideconfig 
(I would assume because the rightclick onto the Machine also triggers the Essence config. Since mouse/croshair is at same spot as the Essence configbutton when opening the GUI.)

Dislocating the Button may already fix this issue.

**Comment by Buuz135** [comment]
Fixed in https://github.com/InnovativeOnlineIndustries/Titanium/commit/b5b0ea1f8b25256db9b92f835599def3f731e096
