### ISSUE TITLE
[1.16] Forge Generic Listener Error

### ISSUE THREAD

**Issue by Stirpe4me** [InnovativeOnlineIndustries/Industrial-Foregoing#811]
**Industrial Foregoing Version:1.16.1-3.0.3-5935836**

**Titanium: Version:1.16.1-3.0.2**
Forge Version is1.16.1-forge-32.0.98 

Forge Error Screen Screenshot (https://user-images.githubusercontent.com/66574976/88930709-75d7b700-d241-11ea-892b-119c8ed725e8.png)

**Comment by Buuz135** [comment]
Duplicate #810
