### ISSUE TITLE
[1.16] Enchantment Factory never starts processing

### ISSUE THREAD

**Issue by LeadAssimilator** [InnovativeOnlineIndustries/Industrial-Foregoing#812]
**Industrial Foregoing Version:** 1.16.1-3.0.4-eeeb31e

**Titanium Version:** 1.16.1-3.0.3

**Mekanism Version:** 1.16.1-10.0.8.431

**Forge Version:** 32.0.98

The Enchantment Factory appears to be non-functional.  Gave it at least 3b essence, power from a Mekanism Creative Energy Cube and any enchantable tool like a diamond pick, but it does nothing.  It just sits there, doesn't even attempt to start.  The Enchantment Applicator and Enchantment Extractor appear to work ok however.  I tested it with only the mods listed above as well as the latest ATM6 pack.

**Comment by Buuz135** [comment]
It needs much more essence for it to work

**Comment by LeadAssimilator** [comment]
It used to be 3b, but it doesn't work even with a full 32b.

**Comment by LeadAssimilator** [comment]
I think you confused b and mb.

**Comment by LeadAssimilator** [comment]
Never mind, appears to be working with 28.2b, sorry.  I guess the minimum amount changed at some point.
