### ISSUE TITLE
[1.15] Upgrades for most of the machines

### ISSUE THREAD

**Issue by kill05** [InnovativeOnlineIndustries/Industrial-Foregoing#813]
**Industrial Foregoing Version:*1.15.2-2.3.3-e356e61*

**Titanium Version:*1.15.2-2.4.2*

**Crashlog If Applicable (Upload to pastebin/gist):**

Hi, most of the machines can't be upgraded. In older version you could use tesla core lib upgrades, but there is no tesla core lib for 1.15.2. My request is to add the option to upgrade all the machines. Thanks!

**Comment by Buuz135** [comment]
Look for addons in JEI

**Comment by davqvist** [comment]
I can confirm and I am pretty sure the OP meant addons. They don't go in most machines like the Stonework Factory or the Dissolution Chamber.
