### ISSUE TITLE
[1.16] Unable to craft Dry Rubber item

### ISSUE THREAD

**Issue by D4VID-B** [InnovativeOnlineIndustries/Industrial-Foregoing#815]
**Industrial Foregoing Version:** 1.16.1-3.0.4-eeeb31e

**Titanium Version:** 1.16.1-3.0.4

**Crashlog If Applicable (Upload to pastebin/gist):** The game doesn't crash, so I guess it's not needed? I can attach the latest.log or debug.log if they can help

Basically what the title says. It doesn't work with the FastWorkbench bench, the Craftingstation Station or the RS Crafting grid. If I try to make it into a pattern, it's not recognized as a recipe and the pattern creation arrow doesn't light up.

**Comment by Buuz135** [comment]
Update placebo, not an IF issue

**Comment by D4VID-B** [comment]
Actually, what seemed to fix it was running the /reload command (I believe that's from CraftTweaker), so you beat me by a few minutes.
