### ISSUE TITLE
[1.16] Mechanical Dirt not working

### ISSUE THREAD

**Issue by D4VID-B** [InnovativeOnlineIndustries/Industrial-Foregoing#816]
**Industrial Foregoing Version:** 1.16.1-3.0.4-eeeb31e

**Titanium Version:** 1.16.1-3.0.4

**Crashlog If Applicable (Upload to pastebin/gist):** No game crashes, but can upload debug.log, latest.log, or any other if needed

This might just be me not understanding how the thing works, because this is my first time using it, but it has both sufficient power, meat and the progress/run timer is ticking like with the other machines, but nothing happens. Tried using it with both redstone set to Pulse and Ignored, but still nothing. It's currently in the ground, but there are no blocks directly above it and the room it's in is pretty dark.

**Comment by Buuz135** [comment]
Make sure the room is atleast 3 blocks high for better efficiency

**Comment by D4VID-B** [comment]
![IF_MD_Test-01](https://user-images.githubusercontent.com/48723686/89931040-a8869580-dbd9-11ea-947d-42346a31f002.png)
This is a test I did in creative. The space is 5x5x4, so there should be plenty of room. It has infinite power and meat, but it still doesn't do anything.

**Comment by tpoismans** [comment]
I somewhere read that mechanical dirt needs a solid block under it to operate for some reason. So if you're cabling for power and liquid meat goes underneath, it doesn't count it as a solid block.

**Comment by D4VID-B** [comment]
Just tried adjusting my setup and it does spawn mobs now. Only it doesn't do so every time the progress bar reaches 0, though that might be intended...

**Comment by Buuz135** [comment]
I found that out recently too, reopening. The not spawning always when the bar reaches 0 its intented.
