### ISSUE TITLE
[1.16] Crafting the Intinity Saw crashes the Sever

### ISSUE THREAD

**Issue by Philipp766** [InnovativeOnlineIndustries/Industrial-Foregoing#818]
**Industrial Foregoing Version:**
1.16.1-3.0.3

**Titanium Version:**
1.16.1-3.0.2
**Crashlog If Applicable (Upload to pastebin/gist):**
https://pastebin.com/9xLPB2wA

If you try to Craft the Infinity saw and the crafing finishes the server crashes and the Item is lost.

**Comment by Buuz135** [comment]
Update IF
