### ISSUE TITLE
[1.12] kotlin.KotlinNullPointerException when filling a Black Hole Tank with a Water Bottle

### ISSUE THREAD

**Issue by James103** [InnovativeOnlineIndustries/Industrial-Foregoing#819]
**Industrial Foregoing Version:** industrialforegoing-1.12.2-1.12.8-232.jar

**TeslaCoreLib Version:** tesla-core-lib-1.12.2-1.0.15.jar

**Modpack:** FTBPresentsDirewolf20112-2.5.0-1.12.2.zip (the only addition was VanillaFix 1.0.10 to report this issue)

**Crashlog If Applicable (Upload to pastebin/gist):** https://pastebin.com/31MCYPLz

When you manually fill a Black Hole Tank using a Water Bottle, Tesla Core Lib reports a scheduled task exception `kotlin.KotlinNullPointerException` This does not apply when using for example an alcohol bottle from Binnie's Mods, or any other container to fill the liquid. Emptying a Black Hole Tank with a Water Bottle does work, without reporting any errors.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
