### ISSUE TITLE
[1.12] NullPointerException in FluidPumpTile.work

### ISSUE THREAD

**Issue by remyroy** [InnovativeOnlineIndustries/Industrial-Foregoing#824]
**Industrial Foregoing Version:**

1.12.2-1.12.13-237

**TeslaCoreLib Version:**

1.12.2-1.0.17

**Crashlog If Applicable (Upload to pastebin/gist):**

https://gist.github.com/remyroy/d0eab4164dc7b019343540c6de081dd0

**More details**

I've been playing FTB Interactions for a few days now. I've recently added a Fluid Pump above an oil well. It was working for a while but it seems like it made my world crash just now.

I can provide more details like a world dump or anything else needed. Just let me know.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
