### ISSUE TITLE
[ 1.12 ] Fermentation Station / ModTweaker compatibility

### ISSUE THREAD

**Issue by LnX-OrioN** [InnovativeOnlineIndustries/Industrial-Foregoing#829]
Hi, Can you add compatibility with modtweaker for the fermentation station, i want add custom recipes for my modpack ( Ascensio on curseforge ).
Your fermentation station fits perfectly to use with rustic and others alcool mods for brewing, fermentation but with greater automations.

Thanks for consider my request 😉

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
