### ISSUE TITLE
[1.16] Biofuel generators always using biofuel

### ISSUE THREAD

**Issue by SirWellingt0n** [InnovativeOnlineIndustries/Industrial-Foregoing#830]
**Industrial Foregoing Version:** 1.16.1-3.0.5

**Titanium Version:** 1.16.1-3.0.4

**Crashlog If Applicable (Upload to pastebin/gist):** N/A

Biofuel generators always burnign fuel even when full of energy.

https://youtu.be/c6kKxCg1ofw

**Comment by tonyysz** [comment]
up
