### ISSUE TITLE
[1.15] Marine Fisher Excessive CPU usage

### ISSUE THREAD

**Issue by AtomicGrog** [InnovativeOnlineIndustries/Industrial-Foregoing#831]
**Industrial Foregoing Version: industrial-foregoing-1.15.2-2.3.3-e356e61**

**Titanium Version: titanium-1.15.2-2.4.2**

**Warmroast image snippet: https://pasteboard.co/JoOhELA.png**

This is from latest version of ATM5 (2.18) but was being experienced prior.

The block was using around 70% of of total load, with TPS reduced to around 12-14 on average. (i9900k dedicated server)

Likely the blocks were chunk loaded but the server has only had light usage since inception.

The screenshot shows the effort being within the work() function.

I subsequently changed the mods config so that the Marine Fisher only cycled ever 500 ticks rather than the default 100 i.e. significantly slowing it. The load dropped proportionally but making it woefully slow.

**Comment by Buuz135** [comment]
Look deeper in the trace, there was a mod causing it I think.

**Comment by AtomicGrog** [comment]
Thanks,

Trace led to another mod as you suggested. There's a sister issue raised in the other mod's github here.
https://github.com/TeamMetallurgy/Aquaculture/issues/113
Interestingly also with the Fisher as the calling mod.
