### ISSUE TITLE
[1.12] Bioreactor accepted items list depends on mod loading order

### ISSUE THREAD

**Issue by target-san** [InnovativeOnlineIndustries/Industrial-Foregoing#832]
**Industrial Foregoing Version:1.12.13-237**

**TeslaCoreLib Version:1.0.15**

**Crashlog If Applicable (Upload to pastebin/gist): not a crash**

Context: reproduced on FTB Academy 1.1.1 modpack

Description: adding or removing mods which add/remove trees may alter set of saplings accepted by BioReactor
In my particular case, BR initially accepted saplings from vanilla, tinkers' construct and Quark. Twilight Forest and Traverse saplings weren't accepted. After adding Integrated Dynamics, Quark saplings disappeared from accepted list and were replaced by ID's menril sapling.

Walking through codebase a bit lead me to `RecipeHandlers.loadBioReactorEntries` which fills `BioreactorEntry.BIO_REACTOR_ENTRIES` collection through IndustrialForegoingHelper methods.
And `RecipeHandlers.loadBioReactorEntries` is called from `CommonProxy.init` method. I may be wrong here although I remember `init` is (was?) used to register blocks, while recipes registration or their tweaking was performed in `postInit`.
Could it be the case that checking ore dictionary is better be postponed to postInit?

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
