### ISSUE TITLE
[1.16] Block Placer can not place blocks in claimed chunk.

### ISSUE THREAD

**Issue by lucasbanting** [InnovativeOnlineIndustries/Industrial-Foregoing#834]
Industrial Foregoing Version: 1.16
TeslaCoreLib Version: N/A
Crashlog (If Any): N/A

The block placer can not place blocks in a chunk that is claimed with FTB chunks method.

**Comment by Buuz135** [comment]
You need the add the Fake Player `[IF]` as a friend
