### ISSUE TITLE
[1.16] Infinity drill deletes fluid/water in south east corner 

### ISSUE THREAD

**Issue by PORTB** [InnovativeOnlineIndustries/Industrial-Foregoing#835]
**Industrial Foregoing Version:** industrial-foregoing-1.16.1-3.0.5-7e692e4

**Titanium Version:** titanium-1.16.1-3.0.4

The infinity drill deletes the fluid (tested with water only) in the south east corner when mining in the x/z axis. When mining on the y axis it deletes the top left corner
before mining:
![image](https://user-images.githubusercontent.com/34615701/92887943-37e0cc00-f458-11ea-96e8-7118191bc147.png)

after mining:
![image](https://user-images.githubusercontent.com/34615701/92888017-4f1fb980-f458-11ea-89ab-113a15c107de.png)

Drill set to 7x7x1 mode

**Comment by tonyysz** [comment]
How do i charge my infinity drill in 1.16.1? @PORTB
