### ISSUE TITLE
[1.15] Dissolution Chamber Not Creating Addons

### ISSUE THREAD

**Issue by imakunee** [InnovativeOnlineIndustries/Industrial-Foregoing#836]
**Industrial Foregoing Version:** industrial-foregoing-1.15.2-2.3.3-e356e61.jar

**Titanium Version:** titanium-1.15.2-2.4.2.jar

Upon inserting a recipe to the Dissolution Chamber and supplying power and latex the Chamber does nothing.

https://ibb.co/zx3CYYs

Thank you for your work on this mod! It's pretty much a must have for me.

Afterword: I would use the 1.16 version of forge and the mod but for some reason all the forge versions I've tried crash on startup even with no mods installed and it seems many people are having this issue.

**Comment by Buuz135** [comment]
Look at the recipe there are glass panes there.

For support like this use discord first.
