### ISSUE TITLE
[1.12] Fluid pump not pumping oil and crashing

### ISSUE THREAD

**Issue by Heldenkrieger01** [InnovativeOnlineIndustries/Industrial-Foregoing#837]
**Industrial Foregoing Version:**
1.12.13

**TeslaCoreLib Version:**
1.0.17

**Crashlog If Applicable (Upload to pastebin/gist):**
https://pastebin.com/JuYhA0dD

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
