### ISSUE TITLE
[1.16.1] Crash

### ISSUE THREAD

**Issue by 04Slash** [InnovativeOnlineIndustries/Industrial-Foregoing#839]
**Industrial Foregoing Version:** industrial-foregoing-1.16.3-3.1.0-7b7cd48.jar 

**Titanium Version:** titanium-1.16.3-3.1.0.jar

**Crashlog If Applicable (Upload to pastebin/gist):** No crash report.
[Latest.log](https://pastebin.com/LJDvzyBB)
[Crash screen](https://imgur.com/d1MIVOb)

**Minecraft version:** 1.16.1
**Forge version:** 32.0.108

**Description:** The latest release of Industrial foregoing is marked compatible with 1.16.1 and 1.16.3 on Curseforge. Upon loading the mod on 1.16.1 the game crashes with the above message. After reading the patch notes, and looking at 1.16.3 in the mod.jar, I suspect this was suppose to be compatible with 1.16.2 and 1.16.3.

**Comment by Buuz135** [comment]
You are using a 1.16.3 mod with 1.16.1 forge, I will mark it in cf as not compatible
