### ISSUE TITLE
[1.12] Custom Fluid Dict Converter help

### ISSUE THREAD

**Issue by YOYOK9** [InnovativeOnlineIndustries/Industrial-Foregoing#840]
Forge: 14.23.5.2854
Industrial Foregoing Version: 1.12.2-1.12.13-237
TeslaCoreLib Version: 1.12.2-1.0.17

Not sure if this is a script issue or an actual block mechanic issue. Basically I am trying to convert between Immersive Petroleum oil and Thermal Foundations crude oil. If I look in JEI for the recipe it shows the 2 being able to convert back and forth, however when I put the liquids and cycle through the fluid types the 2 oil buckets don't exist. So the fluids won't convert. 

oil -> crude with respective bucks below in the converter: https://puu.sh/GttGh/585a738663.png
Ct with buckets containing fluids names: https://puu.sh/GttHZ/0c610aabfc.png
Gif showing JEI: https://puu.sh/GttLu/7048e5b913.gif

Script: https://pastebin.com/qSamAwBh

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
