### ISSUE TITLE
[1.12] Fluid pump suggestion

### ISSUE THREAD

**Issue by Mufty7** [InnovativeOnlineIndustries/Industrial-Foregoing#842]
**Industrial Foregoing Version:**  industrialforegoing-1.12.2-1.12.13-237.jar

**TeslaCoreLib Version:** Tesla Core Lib : 1.0.17.25

**Crashlog If Applicable (Upload to pastebin/gist):**

I have a problem with the Fluid pump, it sometimes stops pumping oil, my suggestion is when you place the pump, it's automatically in pause mode, so you can add upgrade for range. I would like to have the option to set a filter by bucket of that liquid in the gui and have the option to turn off/on the cobblestone replacing the liquid. And I don't know if it's intentional, but the pump doesn't output the oil to the ender tank at the top.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
