### ISSUE TITLE
[1.15] Block Placer Stops Placing blocks

### ISSUE THREAD

**Issue by madbrad21** [InnovativeOnlineIndustries/Industrial-Foregoing#845]
**Industrial Foregoing Version:**  industrial-foregoing-1.15.2-2.3.3-e356e61.jar

**Titanium Version:** titanium-1.15.2-2.4.2.jar

**Crashlog If Applicable (Upload to pastebin/gist):** None

It appears the block placer just stops placing blocks (possibly after a certain number of places)

Set up automated latex processing and then one day the block placer stopped placing he acacia logs despite being full of logs and having an empty spot to place them. The placer still makes the sound as though it is placing the block when it has one in its inventory but still does not place it. Even newly made placers do not place any blocks.

Issue is occurring on a server running Valhelsia2

I own and operate the server so if any logs are needed please reach out and I will provide as much information as possible

**Comment by Buuz135** [comment]
Make sure the are isn't protected or whitelist the fake player for it.

**Comment by madbrad21** [comment]
It was not a protected area, just realized that we built a minecolonies village that may be protecting the area even though all users have full rights to the colony though so it is still strange but I didn't think of how that might be the issue. Thank you
