### ISSUE TITLE
[1.15] Efficiency & Speed add-ons not supported by some machines with 4 upgrade slots

### ISSUE THREAD

**Issue by PlayerDot** [InnovativeOnlineIndustries/Industrial-Foregoing#846]
**Industrial Foregoing Version:**
1.15.2-2.3.3-e356e61.jar
**Titanium Version:**
???
**Crashlog If Applicable (Upload to pastebin/gist):**
No.

StoneWork factory is slow but does not accept any efficiency or speed add-ons, despite having 4 slots for upgrades. I also tried pumping them in and looking for other gimmicks that would insert it for me, but it didn't work. Those addons were just inserted into their inventories or production outputs.
I discovered the same problem with the Dissolution chamber, but the mob grinder and rancher do accept these upgrades. 

I haven't tested the other ones since there was no need to upgrade.

**Comment by Buuz135** [comment]
Fixed in the 1.16 version, the 1.15 support is unsupported
