### ISSUE TITLE
[1.12] Mob Crusher causing ticking block entity crashes?

### ISSUE THREAD

**Issue by TwoPluzTwo** [InnovativeOnlineIndustries/Industrial-Foregoing#849]
Playing on Sky Factory 4 modpack. Using the Mob Crusher to kill cows with a +5 Range Addon.
Guess I will have to find another way to get essence. =(

Industrial Foregoing Version: industrialforegoing-1.12.2-1.12.13-237.jar

TeslaCoreLib Version: tesla-core-lib-1.12.2-1.0.17.jar

Crashlog If Applicable (Upload to pastebin/gist): [Crashlog](https://pastebin.pl/view/fe1f5faa)

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
