### ISSUE TITLE
[1.12] Mob Crusher generating stacks of mob-heads

### ISSUE THREAD

**Issue by lightlike** [InnovativeOnlineIndustries/Industrial-Foregoing#851]
**Industrial Foregoing Version:** 1.12.13-237

**TeslaCoreLib Version:** 1.0.17

## Setup (Server)

- EnderIO Mob Spawner spawning Zombies
- Killing zombies with mob crusher
- nothing else there

![grafik](https://user-images.githubusercontent.com/12970722/95019832-e6e38280-0667-11eb-8b68-0693e8cbf3b4.png)

**Comment by Buuz135** [comment]
Are you sure they arent just piling up?

**Comment by lightlike** [comment]
Yep. This machine ran for about 5 seconds. And was empty before.

**Comment by spencerrcr** [comment]
Came here to see if anyone else had this issue, apparently so, getting stacks of enderman heads after it ran for less than 1min

**Comment by phrostt** [comment]
Can confirm, I have exactly same issue.

**Comment by ProjectGSX** [comment]
I had the same issue.  Tons and tons of mob heads in a matter of seconds.

**Comment by SanderWxD** [comment]
Same. Drops 50 heads per mob.

**Comment by SanderWxD** [comment]
For me this was caused by Ender IO/Core. Updating those two to latest version fixed the issue.

**Comment by lightlike** [comment]
It seems that this was fixed with EnderIO 5.2.61 but I get a Forge-Error when trying to load that version.
But that is not a problem for this Repo so I will close this here. (and this is not really a problem as no one on my server uses spawners)
