### ISSUE TITLE
[1.15] Marine Fisher missing texture

### ISSUE THREAD

**Issue by SonicSpeedster16** [InnovativeOnlineIndustries/Industrial-Foregoing#853]
**Industrial Foregoing Version:** 2.3.3

**Titanium Version:** 2.4.2

**Crashlog If Applicable (Upload to pastebin/gist):** N/A

When viewing the Marine Fisher in JEI or holding it in your hand, it has a missing texture (it uses the black and purple squares). Once placed in the world it looks correctly.

Forge 31.2.43

**Comment by Buuz135** [comment]
Fixed in the 1.16 version, the 1.15 version is unsupported
