### ISSUE TITLE
[1.15] Resourceful Furnace not producing Essence

### ISSUE THREAD

**Issue by SonicSpeedster16** [InnovativeOnlineIndustries/Industrial-Foregoing#854]
**Industrial Foregoing Version:** 2.3.3

**Titanium Version:** 2.4.2

**Crashlog If Applicable (Upload to pastebin/gist):** N/A

Smelting things in the Resourceful Furnace does not produce any Essence at all. Nothing I have smelted has produced Essence.

Forge 31.2.43

**Comment by Buuz135** [comment]
Fixed in the 1.16 version, the 1.15 version is unsupported

**Comment by SonicSpeedster16** [comment]
I didn't realize that 1.15 was already completely unsupported.

**Comment by Buuz135** [comment]
Don't worry, I always aim for the latest
