### ISSUE TITLE
[1.16] Issue Title

### ISSUE THREAD

**Issue by PowerToTheNerd** [InnovativeOnlineIndustries/Industrial-Foregoing#855]
**Industrial Foregoing Version:**

**Titanium Version:**

**Crashlog If Applicable (Upload to pastebin/gist):**
Pink slime isn't obtainable from mob grinder. Sludge glitches in the process of purifying as well. Last animal feeder doesn't work at all.

**Comment by Buuz135** [comment]
Please make an proper issue report or ask in discord for support, The mob crusher doesnt make pink slime.
