### ISSUE TITLE
Integration of Farmer's Delight

### ISSUE THREAD

**Issue by Nekdo-Jiny** [InnovativeOnlineIndustries/Industrial-Foregoing#861]
**Is your feature request related to a problem? Please describe.**
Its not related to problem, but Plant Gatherer wont gather tomatoe plants from Farmer's Delight mod. 

**Describe the solution you'd like**
Plant Gatherer should gather tomatoes like Sweet Berries from Vanilla Minecraft.

**Additional context**
-

**Comment by AlexandreMouyen** [comment]
Hello there,

![image](https://user-images.githubusercontent.com/27637370/196040756-56797efb-d017-44fe-ab6c-e079741f82f0.png)

I am on Direwolf20 for MC 1.18, Industrial Foregoing 3.3.1.4 and the Plant Gatherer is not harvesting tomatoes.
