### ISSUE TITLE
[1.12] Server crash

### ISSUE THREAD

**Issue by CukeManCZ** [InnovativeOnlineIndustries/Industrial-Foregoing#862]
Can someone tell me whats the problem ?
I using modpack Foolcraft 3

**Industrial Foregoing Version:**
1.12.2-1.11.5-2150
**TeslaCoreLib Version:**
1.0.15
**Crashlog If Applicable (Upload to pastebin/gist):**
https://paste.minecrafthelp.co.uk/?30874eac3c680a0d#Ba6DyUgbNxd61Y1w9Fjte7WwbPx8sut3bdNQq1YygfUs

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
