### ISSUE TITLE
[1.16] Industrial's foregoing Book texture issue

### ISSUE THREAD

**Issue by vazan** [InnovativeOnlineIndustries/Industrial-Foregoing#863]
Industrial Foregoing Version: 1.16
TeslaCoreLib Version: n/a
Crashlog (If Any): n/a

The book of industrial Foregoing have no model or texture:
![2020-10-24_22 37 07](https://user-images.githubusercontent.com/14837391/97097765-0f4d1400-164b-11eb-86c2-167358e034b9.png)

**Comment by Buuz135** [comment]
Patchouli issue
