### ISSUE TITLE
Give the player a possibility to "reset" a fluid pump search without breaking it

### ISSUE THREAD

**Issue by funfox1** [InnovativeOnlineIndustries/Industrial-Foregoing#864]
**Is your feature request related to a problem? Please describe.**
In Glacial Awakening i wanted to use Amplifying tubes (turns cobblestone into lava) to create a regular supply of lava 1 block next to the fluid pump.
It works only the "first time", as the pump stops after a work cycle without lava available (this was shown in other issues already).

**Describe the solution you'd like**
I feel it would be interesting to let the player "choose" the way the pump handles what happens after a work cycle without liquid is available. Either by giving the possibility to "reset" it with a redstone signal, or by giving the player a way to choose in the pump GUI if the pump should scan its work range regularly as plant sowers do.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
