### ISSUE TITLE
[1.16] Manual missing

### ISSUE THREAD

**Issue by benjanamin** [InnovativeOnlineIndustries/Industrial-Foregoing#872]
**Industrial Foregoing Version:* 3.1.1-a834e76*

**Titanium Version:* 1.16.3-3.1.0.jar*

**Crashlog If Applicable (Upload to pastebin/gist):**
Manual is missing in survival and creative

**Comment by Buuz135** [comment]
Use Patchouli

**Comment by benjanamin** [comment]
Patchouli?

**Comment by Buuz135** [comment]
https://www.curseforge.com/minecraft/mc-mods/patchouli

**Comment by benjanamin** [comment]
do i only have to put it on my mods folder, right?
