### ISSUE TITLE
[1.16] Mob Crusher doesn't kill baby mobs

### ISSUE THREAD

**Issue by STOKESTER** [InnovativeOnlineIndustries/Industrial-Foregoing#877]
**Industrial Foregoing Version:**
industrial-foregoing-1.16.4-3.2.2-daea863.jar
**Titanium Version:**
titanium-1.16.4-3.2.1.jar

watched it running, kills adult vanilla mobs fine, kills thermal mobs fine. But it's showing baby mobs from Mekanism mercy as well as vanilla baby zombies.

**Comment by WBgroup** [comment]
This might be related to a bugfix for #869, which made it so baby mobs aren't killed
