### ISSUE TITLE
Mob Imprisonment Tool Crash

### ISSUE THREAD

**Issue by jake4832** [InnovativeOnlineIndustries/Industrial-Foregoing#881]
Industrial Foregoing Version: 1.12.2-1.12.11-235
TeslaCoreLib Version: 1.12.2-1.0.15

Crash happens when right-clicking a cow with the tool, upon reopening world tool is still empty and cow is still there

Crashlog (If Any): 
[crash-2020-11-25_17.20.11-client.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/5599932/crash-2020-11-25_17.20.11-client.txt)

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
