### ISSUE TITLE
[Cosmetic]: Changelog numbering mistake

### ISSUE THREAD

**Issue by SomewhatDamaged** [InnovativeOnlineIndustries/Industrial-Foregoing#890]
[This version number](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/changelog/CHANGELOG.md#312) should be 3.2.2 I believe, not 3.1.2

**Comment by Buuz135** [comment]
Don't make issues for stuff that its not an issue, please use discord for those things
