### ISSUE TITLE
[1.16] Slime Generator isn't picking up the slime tag properly

### ISSUE THREAD

**Issue by MuteTiefling** [InnovativeOnlineIndustries/Industrial-Foregoing#892]
**Forge**
35.1.7
**Industrial Foregoing Version:**
industrial-foregoing-1.16.4-3.2.4-c94618f
**Titanium Version:**
titanium-1.16.4-3.2.2
**Crashlog If Applicable (Upload to pastebin/gist):**
[crash-2020-12-06_12.02.55-client.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/5649182/crash-2020-12-06_12.02.55-client.txt)

![image](https://user-images.githubusercontent.com/9543430/101281967-419c7600-37a0-11eb-9196-31ac7f26578d.png)

![image](https://user-images.githubusercontent.com/9543430/101281974-4c570b00-37a0-11eb-8201-738d3d3abb2c.png)

**Comment by MuteTiefling** [comment]
Same thing with the magma generator and redstone

![image](https://user-images.githubusercontent.com/9543430/101282034-99d37800-37a0-11eb-9810-238257fadf27.png)

**Comment by MuteTiefling** [comment]
aaaand the Meatallurgic with ingots. Guess it's the tag support in general that's not working right.

🐱

**Comment by Buuz135** [comment]
It should be visual only on JEI, it should work fine tho.

**Comment by MuteTiefling** [comment]
Alright, I'll double check in a bit

**Comment by MuteTiefling** [comment]
well, something funny is going on here. Got an NPE when I placed the meatallurgic generator on a server. I'm a bit baffled by the errors related to Mek/PNC heat adapters though. 

This was in the in-dev instance of E6


[crash-2020-12-06_12.02.55-client.txt](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/files/5649176/crash-2020-12-06_12.02.55-client.txt)

**Comment by Buuz135** [comment]
Update to 3.2.5
