### ISSUE TITLE
generator visual bug

### ISSUE THREAD

**Issue by Warbringer12** [InnovativeOnlineIndustries/Industrial-Foregoing#893]
**Industrial Foregoing Version:** 1.1.6.4-3.2.5-74675d6

**Titanium Version:** 1.16.4-3.2.2

![2020-12-06_12 30 44](https://user-images.githubusercontent.com/44590540/101291716-bb902780-37bf-11eb-8895-e2de52ed126d.png)

**Comment by Buuz135** [comment]
Can you explain a little?

**Comment by WBgroup** [comment]
I think the power level is not rendering in the UI

**Comment by Warbringer12** [comment]
yeah the power isnt rendering in the ui after a certain amount
