### ISSUE TITLE
[1.16] Infinity tools recipe issue

### ISSUE THREAD

**Issue by Basedgod199** [InnovativeOnlineIndustries/Industrial-Foregoing#894]
**Industrial Foregoing Version:** 1.16.4.3.2.4-c94618f

**Titanium Version:** titanium-1.16.4-3.2.2

**Crashlog If Applicable (Upload to pastebin/gist):** N/A

All the infinity tools use an addon range tier 12 in the recipe, however clicking on the addon doesn't show the recipe. I'm guessing its because it has no nbt (compared to all the others in jei)

now that being said its not too big of a deal because searching for it in jei will still show the recipe for the addon, but i thought i'd still mention it.

![image](https://user-images.githubusercontent.com/32063145/101293008-db2b4e00-37c7-11eb-9dfd-7b55f7ec83f3.png)

**Comment by oof2win2** [comment]
I have encountered this issue too, Enigmatica 6 0.5.6.
