### ISSUE TITLE
Sword Enchants for Infinity Hammer

### ISSUE THREAD

**Issue by KrAzYGEEK32** [InnovativeOnlineIndustries/Industrial-Foregoing#895]
**Is your feature request related to a problem? Please describe.**
main problem is Hammer doesnt take looting

**Describe the solution you'd like**
solution would be fdor it to have support for all sword enchants, even from other mods.

**Comment by Buuz135** [comment]
It should already work, it does accept looting with just IF installed

**Comment by KrAzYGEEK32** [comment]
buuz, btw did you get it to work on servers? or ever found out the issue regarding the E6 server?

**Comment by Buuz135** [comment]
Yes, its Ensorcellation fault, in latest I force it.
