### ISSUE TITLE
[1.16] Issue Title Crusher doesn't kill rats from Rats mod

### ISSUE THREAD

**Issue by Basedgod199** [InnovativeOnlineIndustries/Industrial-Foregoing#898]
**Industrial Foregoing Version:** 1.16.4.3.2.4-c94618f

**Titanium Version:** 1.16.4-3.2.2

**Crashlog If Applicable (Upload to pastebin/gist):**

It will kill pied pipers but not the rats that are spawned with him. it also won't kill the rats that are normally spawned.

**Comment by Buuz135** [comment]
I need to fix this asap, this cannot be an issue. All funny rats must be erradicated.

**Comment by Basedgod199** [comment]
LOL
