### ISSUE TITLE
[1.12] Plant sower and Gatherer

### ISSUE THREAD

**Issue by Albinstu** [InnovativeOnlineIndustries/Industrial-Foregoing#902]
**Industrial Foregoing Version:**
industrialforegoing-1.12.2-1.12.13-237

**TeslaCoreLib Version:**
tesla-core-lib-1.12.2-1.0.15
Just downloaded and changed to the following in a last messures of trying to solve this. Using the following:
tesla-core-lib-1.12.2-1.0.17

**Crashlog If Applicable (Upload to pastebin/gist):**
none.

The problem I'm having right now is that the plant sower and gatherer are not working properly. The sower doesnt hoe any dirt blocks, have tried to use regular minecraft dirt, not working, other dirt blocks, not working. Another thing the sower does is using RF, it switches between using 40 RF/tick and not, so its using power and will drain the system if no RF generating device is on, and it does so fast. The same goes for the gatherer it uses power constantly if its provided even if there is nothing to gather. The sower also when it does succeed in planting, this is after I myself have hoed a dirt block, takes a very long time for it to do so, if i were to example hoe a dirt block it would take like 20-30 sec to plant something there. 

When it comes to the gatherer its that i mentioned before, it uses power though it should'nt but it also does'nt gather much, and when it does it takes a long time. 

I have tried to fix it and searched around. Could'nt solve it. Tried to change the fake player status, unclaiming chunks, tried to download the latest versions of FTB utilities and industrialcraft. Even removed FTB Utilities but didnt solve it. Nothing have worked so far. 

Must say, a fantastic mod.
Thanks in advance.

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
