### ISSUE TITLE
Hydrator?

### ISSUE THREAD

**Issue by TheOwnerOfThis** [InnovativeOnlineIndustries/Industrial-Foregoing#903]
**Is your feature request related to a problem? Please describe.**
I miss the hydrator, why did you get rid of it? Or is it being worked on? In general, what's happening to it.

**Describe the solution you'd like**
Adding the hydrator back or a good description as to what happened to it in the 1.16.4 update.

**Additional context**
The hydrator was my favorite block in this mod and was just wondering where it went, or if it's coming back, or what's happening. I'm not mad or anything, just curious!

**MC Version:** 1.16.4
**Mod Version:** 3.2.5

**Comment by Buuz135** [comment]
Please ask your questions in discord, not all the features have been added yet
