### ISSUE TITLE
auto grindstone and auto anvil is necessary

### ISSUE THREAD

**Issue by jlusuoya** [InnovativeOnlineIndustries/Industrial-Foregoing#906]
**Is your feature request related to a problem? Please describe.**
I can do most things with this mod  except for the following two：
1、repair my item， as an anvil.
2、clear remove enchantments from enchantment book， as a grindstone。Enchantment Extractor use too much books and storage too much useless enchantment book.

**Describe the solution you'd like**
1、add a new machine named AutoAnvil,  use RF。 input item and repair it
2、add a new machine named AutoGrindstone， user RF， input item and remove all enchantment，support enchantment book
or 
2、add a machine named UncraftingTable， user RF， input double item and only out one synthetic raw materials。 for example，  input two enchantment book， output 3 Paper an only 1 leather。

**Comment by Buuz135** [comment]
1) I don't want something that repairs items
2) The Enchantment Extractor can transform enchantments into essence
2b) Terrible idea
