### ISSUE TITLE
[1.16] Fluid placer does nothing

### ISSUE THREAD

**Issue by Xplodin** [InnovativeOnlineIndustries/Industrial-Foregoing#909]
**Industrial Foregoing Version:**
3.2.2
**Titanium Version:**
3.2.1
**Crashlog If Applicable (Upload to pastebin/gist):**
N/A

Just doesnt place liquids in the world. I have no idea why its not. tried a button and with/without power. No results

**Comment by Buuz135** [comment]
If the area is claimed and you have given the fake player permission its an FTBChunk issue
