### ISSUE TITLE
[1.16] Milk liquid bucket duplication glitch.

### ISSUE THREAD

**Issue by bluefutureMC** [InnovativeOnlineIndustries/Industrial-Foregoing#912]
**Industrial Foregoing Version:**
3.2.6-c3ea663
**Titanium Version:**
3.2.3

When placing milk using a milk bucket and then picking it up again, the liquid sometimes stays after the bucket was filled.

**Comment by Buuz135** [comment]
Waiting on this https://github.com/MinecraftForge/MinecraftForge/pull/7294
