### ISSUE TITLE
Unable to load model: 'industrialforegoing:mob_essence_tool' error

### ISSUE THREAD

**Issue by GadgetNH** [InnovativeOnlineIndustries/Industrial-Foregoing#913]
**Industrial Foregoing Version:** industrial-foregoing-1.16.4-3.2.5-74675d6

I am getting an error "Unable to load model:'industrialforegoing:mob_essence_tool'. I am new to this mod and learning a LOT (Great mod btw) but this shows as an error in Minecraft. I also do not see a Mob Duplicator so I was not sure if this is related.

Any advice?

**Comment by Buuz135** [comment]
Seeing that message is not an issue, not everything is implemented yet.

Please use discord for questions
