### ISSUE TITLE
[1.12] Server is always crashing with this mod 

### ISSUE THREAD

**Issue by a1exfeb** [InnovativeOnlineIndustries/Industrial-Foregoing#914]
**Industrial Foregoing Version:**  industrialforegoing-1.12.2-1.12.13-237

**TeslaCoreLib Version:**  tesla-core-lib-1.12.2-1.0.15.jar

**Crashlog If Applicable (Upload to pastebin/gist):**  https://pastebin.com/meXvt6Tw

**Comment by Buuz135** [comment]
:wave: Sorry but Industrial Foregoing has ended support for version 1.12. I'm closing this issue as it will no longer be updated for that version. Thanks for playing with the mod.
