### ISSUE TITLE
[1.16] Generator Energy Bug

### ISSUE THREAD

**Issue by Jan3004** [InnovativeOnlineIndustries/Industrial-Foregoing#933]
**Industrial Foregoing Version:3.2.7

[https://youtu.be/uzloLtuXW08](url)

The video shows the bug, the energy resets every time.

**Comment by Buuz135** [comment]
It's just a visual bug, power doesnt get display properly client side but it doesn't loose power. Duplicate of #893

**Comment by Jan3004** [comment]
Ok. But can you fix that?

**Comment by Buuz135** [comment]
Yes, but is the same issue as the other one, thats why I closed this issue

**Comment by Jan3004** [comment]
Ok. thanks for the answer. Have a nice day!
