### ISSUE TITLE
mob crusher server crash

### ISSUE THREAD

**Issue by luchokoldo** [InnovativeOnlineIndustries/Industrial-Foregoing#934]
Industrial Foregoing Version: industrial-foregoing-1.16.4-3.2.7-7d95990
TeslaCoreLib Version: titanium-1.16.4-3.2.4
Crashlog (If Any): https://pastebin.com/3g2Cpqri

Im using Dw20 1.16 modpack and I got today 2 server crash, with the old version of the modpack ( with a old version of IF and titanium ) didnt have this issue

edit: another crash log if that help: https://pastebin.com/JectYUbn

**Comment by luchokoldo** [comment]
another crash log if that help: https://pastebin.com/JectYUbn

**Comment by Buuz135** [comment]
This is not an IF issue, some mod is adding a bad attribute to mobs. I can't fix it on my side.
