### ISSUE TITLE
1.16.4 BioFuel Generator acts like Creative infinite power block

### ISSUE THREAD

**Issue by soundtechscott** [InnovativeOnlineIndustries/Industrial-Foregoing#937]
**Industrial Foregoing Version:**
3.2.5 according to my mods screen

When using the Biofuel Generator, it never loses power... goes to full power and stops...
appears to function like an infinite power source

I used a bioreactor to fill it with the bio fuel until power reached Max Value
then I removed the boo reactor to make sure nothing else was still powering it

I attached an RF Tools builder to it to see if I could drain it....
RF tool Builder would only fill at 10k per tick...and it can power much faster than that
and biofuel generator never went down in power or biofuel

**Comment by Buuz135** [comment]
What is your titanium version?
