### ISSUE TITLE
[1.16] Cactus Gathering

### ISSUE THREAD

**Issue by GarrettEstey** [InnovativeOnlineIndustries/Industrial-Foregoing#940]
Industrial Foregoing Version: industrial-foregoing-1.16.4-3.2.7-7d95990
Titanium Version: titanium-1.16.4-3.2.4
Crashlog (If Any): None

The Plant Gatherer appears to function on cacti like it does on trees. A harvester I was setting up to harvest cacti also harvested a lot of wood logs outside of its operating range, and the entire cactus plant. I'd imagine the intended function of the gatherer on cacti would be identical to how it currently functions with sugar cane, leaving the bottom block and collecting the grown parts, however it appears to use tree gathering functionality.

**Comment by Buuz135** [comment]
Some mod might be adding the log tag to the cactus. It works fine in dev.
