### ISSUE TITLE
[1.16] Mechanical Dirt book page is kinda messed up

### ISSUE THREAD

**Issue by aaronhowser1** [InnovativeOnlineIndustries/Industrial-Foregoing#942]
**Industrial Foregoing Version:**
industrial-foregoing-1.16.4-3.2.7-7d95990
**Titanium Version:**
titanium-1.16.4-3.2.4

![image](https://user-images.githubusercontent.com/15698722/103948313-2efac100-50ff-11eb-8e05-e9656280235c.png)

You also can't hold control on it in your inventory to see its page

**Comment by Pdiddy973** [comment]
fixed in 1.4.0 https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/942
