### ISSUE TITLE
[1.16] Fakeplayer issue with minecolonies

### ISSUE THREAD

**Issue by KySoto** [InnovativeOnlineIndustries/Industrial-Foregoing#945]
**Industrial Foregoing Version:** 
industrial-foregoing-1.16.4-3.2.7-7d95990.jar

**Titanium Version:**
titanium-1.16.4-3.2.4.jar
**Crashlog If Applicable (Upload to pastebin/gist):**

I created a report on the minecolonies github, and they essentially told me to come here. https://github.com/ldtteam/minecolonies/issues/6375

**Comment by IamStig** [comment]
Minecolonies has a policy of not accepting any responsibility for compatibility issues. As far as they are concerned ALL mods need to comply to their way of doing things.

**Comment by TheCurle** [comment]
No, no. Raycoms has a point.
Not knowing who put down a fake player block is a massive security flaw.
Allowing it blindly could possibly lead someone to accidentally destroy their entire colony with a malicious block.
This should be a quick fix on IF's part, and i'll see about fixing this tomorrow.

**Comment by thaurane** [comment]
Is there any word on this getting a fix? The last commenter said they would try to fix it the next day. However it is still open and still an issue 5 months later.

**Comment by ravenbuilder934** [comment]
To be fair, Curle *did* have server failures, but I think that was in February
