### ISSUE TITLE
Crash after latest update

### ISSUE THREAD

**Issue by AdnanuReeves** [InnovativeOnlineIndustries/Industrial-Foregoing#946]
https://paste.ubuntu.com/p/4xQDrMPHgY/

I just mined a stone and crashed, happened again when i tried again.

**Comment by AdnanuReeves** [comment]
I'm confused why this got closed, is the crash not due to the mod?

**Comment by WBgroup** [comment]
Buuz Fixed it in the newer titanium version, wait for the release

**Comment by Buuz135** [comment]
It got transfered to the IF repo (as it was an IF issue) and then fixed there

**Comment by AdnanuReeves** [comment]
Oh okey, thanks :) Just got a little confused since it just got locked without saying anything. Sorry
