### ISSUE TITLE
NPE in 1.16.4

### ISSUE THREAD

**Issue by Letoric** [InnovativeOnlineIndustries/Industrial-Foregoing#947]
**Industrial Foregoing Version:**
industrial-foregoing-1.16.4-3.2.8-bb86c58

**Titanium Version:**
titanium-1.16.4-3.2.5

**Crashlog If Applicable (Upload to pastebin/gist):**
https://gist.github.com/Letoric/abea1154c55c0e66a2846c24308c3a06
It didn't create a true crash log even though it said it was preparing one, so the latest is what we have to work with. If you end up needing debug, lemme know.

**Comment by Buuz135** [comment]
Update to 3.2.8.1 and try again to get a crashlog

**Comment by Letoric** [comment]
Thanks, I didn't see that you had released a minor update and removed the
old, so close together.
