### ISSUE TITLE
[1.16] Crash infinite backpacks

### ISSUE THREAD

**Issue by signormorte** [InnovativeOnlineIndustries/Industrial-Foregoing#948]
**Industrial Foregoing Version:*industrial-foregoing-1.16.4-3.2.8.1-f2c848c*

**Titanium Version:*titanium-1.16.4-3.2.5*

**Crashlog If Applicable (Upload to pastebin/gist):*https://gnomebot.dev/api/guild/file/166630061217153024/254806806516203520/797588674866970645/crash-2021-01-09_23.11.45-server.txt*

**Comment by Buuz135** [comment]
You are not using 3.2.8.1 as you mentioned. Update to that.
