### ISSUE TITLE
[1.16] Dye Mixer wasting dye

### ISSUE THREAD

**Issue by djacicd** [InnovativeOnlineIndustries/Industrial-Foregoing#949]
**Industrial Foregoing Version:** industrial-foregoing-1.16.4-3.2.7-7d95990

**Titanium Version:** titanium-1.16.4-3.2.4

**Crashlog If Applicable (Upload to pastebin/gist):** //

**Description:** It uses dye even when color tanks are full, it constantly tries to fill them up and by that process it's wasting dye. While it's trying to fill color tanks it's unable to export.

**Comment by Buuz135** [comment]
Can I get an example or some images? I can't replicate it.

**Comment by djacicd** [comment]
I found out that it's happening because of bad i/o configuration.
https://www.youtube.com/watch?v=DGojkstnfUU

**Comment by Buuz135** [comment]
So its being extracted instead of the output?

**Comment by djacicd** [comment]
Yes, that's the case, it' actually not wasting it as i thought, but it's cycling it back to the system.
