### ISSUE TITLE
[1.16] Industrial Foregoing cannot display Chinese

### ISSUE THREAD

**Issue by Liust1918** [InnovativeOnlineIndustries/Industrial-Foregoing#953]
**Industrial Foregoing Version:**1.16.4-3.2.7-7d95990

**Titanium Version:**   1.16.4-3.2.5

**Crashlog If Applicable (Upload to pastebin/gist):**  NO
 Industrial Foregoing's Manual only display English.it is not display Chinese.
I read Codes in zh-cn.json and zh-CN.lang that has readly Chinese.

**Comment by Buuz135** [comment]
The manual needs to be translated even tho zh-cn.json and zh-CN.lang exist, I don't speak Chinese so I can't do it.
