### ISSUE TITLE
[1.16] Unable To Get Ether Gas / No Tutorial How To Get it

### ISSUE THREAD

**Issue by GaminExotic** [InnovativeOnlineIndustries/Industrial-Foregoing#954]
**Industrial Foregoing Version:**

**Titanium Version:**

**Crashlog If Applicable (Upload to pastebin/gist):**

**Comment by Buuz135** [comment]
Check JEI it tell you to place a Fluid Laser on top of a wither , aslo #529

**Comment by GaminExotic** [comment]
> Check JEI it tell you to place a Fluid Laser on top of a wither , aslo #529

Hmm i tried it I went to the end and placed the wither and my fluid base and lasers with power but it didnt worl
