### ISSUE TITLE
About grades of blackhole storage

### ISSUE THREAD

**Issue by rainsillwood** [InnovativeOnlineIndustries/Industrial-Foregoing#956]
Hello Buuz

Thank you for your wonderful mods which bring us so mach happiness,and also for your hard working on updating new features.

I'v found that in newest IF,blackhole storage system has different grades:Supreme>Advanced>Simple>Pity>Common.
But in common scenes,common usually means normal/medium,simple means easy/little,pity means very easy/poor.Such as game difficulties.So some (or most?) of us maybe confused with current grades.(especially for translators)

Is it really appropriate for current grades?What does the current grades' actually meaning?

**Comment by Buuz135** [comment]
Common is just a tier added as a veeery early game option outside of most of the progression
