### ISSUE TITLE
[1.16] Mob Crusher not accepting any Range addons

### ISSUE THREAD

**Issue by munsonman1** [InnovativeOnlineIndustries/Industrial-Foregoing#958]
**Industrial Foregoing Version:**
1.16 build 3.2.8.2

Running FTB Direwolf20 1.16 Modpack version 1.4.0. Had Mob Crusher with a Tier 12 Range addon in it and some random mob loot drops. Accidently middle-clicked (sorts inventory) while in the Mob Crusher's gui. The loot and addon both disappeared. Now I can no longer put any range addons into the Mob Crusher. Replaced the crusher with a new one, same issue. Tried different range addons, same issue. Closed and restarted the world, same issue.

**Comment by Buuz135** [comment]
If you are getting the items from creative they have nbt that its not getting attached with the /give command, make sure to get them from jei (by shift + clicking the wrench to enable cheat mode) or the creative menu

**Comment by joejoe1456** [comment]
I built a range addon myself and tried to add it to the block breaker but it didn't work either

**Comment by WBgroup** [comment]
Block breaker doesn't accept range addons (at least functionally), that's intended, also a thing with fluid extractors.

**Comment by joejoe1456** [comment]
Huh. Well is there anything else I could use to make a tree farm?
