### ISSUE TITLE
[1.16] IF is marked as supporting 1.16.3, 1.16.4 on CurseForge but requires Forge 36.0.1+, which is 1.16.5 only.

### ISSUE THREAD

**Issue by Vaelzan** [InnovativeOnlineIndustries/Industrial-Foregoing#959]
On CurseForge, the latest release of Industrial Foregoing is marked as supporting Minecraft 1.16.3, 1.16.4, and 1.16.5 but the required Forge version (36.0.1+) is only available for 1.16.5, making the game fail to load when used in 1.16.4. Either the Forge requirement needs to be dropped lower or the CurseForge metadata needs to be adjusted, since many launchers rely on CurseForge metadata being correct to determine compatibility (such as GDLauncher).

This is made even more confusing given that the filename still contains 1.16.4.

**Industrial Foregoing Version:**
industrial-foregoing-1.16.4-3.2.8.3-7ac4a96

**Titanium Version:**
titanium-1.16.4-3.2.5

**Crashlog If Applicable (Upload to pastebin/gist):**
N/A.

**Comment by Buuz135** [comment]
Fixed thanks!
