### ISSUE TITLE
[1.16] industrial-foregoing-1.16.4-3.2.8.3-7ac4a96.jar not compatible with 1.16.4

### ISSUE THREAD

**Issue by TechniumUnlimited** [InnovativeOnlineIndustries/Industrial-Foregoing#967]
**Industrial Foregoing Version:**
industrial-foregoing-1.16.4-3.2.8.3-7ac4a96.jar

This mod when run on server says it requires 36.0.1 of Forge, which is 1.16.5 version of forge, making this mod incompatible with state 1.16.4 forge/mc versions - despite the beta showing 1.16.4 as the MC version.

**Comment by Buuz135** [comment]
Curseforge doesnt show its 1.16.4 compatible, the name will be fixed in the future

**Comment by TechniumUnlimited** [comment]
Sorry yea I didn't check the cf version, just looked at the jar name, thank you have a nice day
