### ISSUE TITLE
[1.16] Server crash when trying to put a bottle in a black hole tank with potion

### ISSUE THREAD

**Issue by mthp1999** [InnovativeOnlineIndustries/Industrial-Foregoing#971]
**Industrial Foregoing Version:**
1.16.4-4.1.2-129
**Titanium Version:**
1.16.4-3.2.5
**Crashlog If Applicable (Upload to pastebin/gist):**
https://pastebin.com/TFd8GzpN

Happened when I tried to put a glass bottle into the black hole tank when it was full with a potion fluid.

**Comment by Buuz135** [comment]
In the blue filter slot?

**Comment by Buuz135** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/4583

**Comment by malte0811** [comment]
I just had a look at the crash, I don't think this is on our side. Yes, we do sometimes call simulate with empty (but not null) fluid stacks (and we should probably change that), but that's not what's crashing here. [Here](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/578705c511993b3951bde49aafecc3c72df34a1c/src/main/java/com/buuz135/industrial/block/transportstorage/tile/BlackHoleTankTile.java#L63) you are calling `orElseGet` with `null` as the `other`-argument, and part of the specification for `orElseGet` is
 > Throws: NullPointerException – If `other` is `null` and this `LazyOptional` is non-empty (sic: should be "is empty")

So my guess is that potion bottles do not have any fluid handler (we don't attach one in IE, I think we may have done at some point), so it tries to use your "supplier" and fails. You probably want `orElse`, without the `Get`.
