### ISSUE TITLE
[1.16] You can pour infinite milk

### ISSUE THREAD

**Issue by aaronhowser1** [InnovativeOnlineIndustries/Industrial-Foregoing#975]
**Industrial Foregoing Version:**
industrial-foregoing-1.16.4-3.2.8.2-6b5c95b
**Titanium Version:**
titanium-1.16.4-3.2.5
**Forge version:**
36.0.1 (latest for 1.16.5)

Slightly different from #912, I think. 

https://user-images.githubusercontent.com/15698722/105575272-0e05b300-5d30-11eb-9b64-235db598bfa2.mp4

After pouring milk, I can click the empty bucket two more times to make two more sources.

**Comment by Buuz135** [comment]
Please update to the latest version where I dont handle the milk bucket, as that one is the forge one

**Comment by aaronhowser1** [comment]
Unless I'm missing something, I *am* using the latest version. 

industrial-foregoing-1.16.4-3.2.8.2-6b5c95b
https://www.curseforge.com/minecraft/mc-mods/industrial-foregoing/files/3167607

**Comment by Buuz135** [comment]
![firefox_BNQlSDPGLE](https://user-images.githubusercontent.com/3874674/105576670-b6d60180-5d74-11eb-9bbb-535fe5892221.png)

**Comment by aaronhowser1** [comment]
Huh, fair enough then lol

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/105576728-6d68c080-5d3a-11eb-9477-711407e71626.png)
Curseforge why are you the way that you are
