### ISSUE TITLE
[1.16] Infinity backpack causing crash (BackpackCapabilityProvider.getCapability)

### ISSUE THREAD

**Issue by EternalClickbait** [InnovativeOnlineIndustries/Industrial-Foregoing#977]
**Industrial Foregoing Version:** industrial-foregoing-1.16.4-3.2.8.2-6b5c95b (3.2.8.2)

**Titanium Version:** titanium-1.16.4-3.2.5 (3.2.5)

**Crashlog If Applicable (Upload to pastebin/gist):** https://pastebin.com/pnG3gcLL
Crashes as soon as I join the server :(

**Comment by Buuz135** [comment]
Update the mod

**Comment by EternalClickbait** [comment]
I can't, it's in a Modpack (direwolf 1.16) @Buuz135

**Comment by Hadoukanen** [comment]
I got this issue as well. Dire said he would update IF in the last episode. Like yesterday for me. I guess one have to wait. Watch some flowers... Maybe have a drink... Think about how buggy all the mods are. :-)

**Comment by Buuz135** [comment]
> 
> 
> Think about how buggy all the mods are. :-)

Kinda rude, ngl

**Comment by Hadoukanen** [comment]
These things happen. No worries Buzz, just joking. :-) Seems Dire would not update the pack yet, so i went in and nuked the backpack from my inventory with NBTExplorer on my server. So my problem is sorted at least. Will check it out again when a update will be done on the Dire pack. If you do this remember to BACKUP the data BEFORE messing around with NBTExplorer... OK kids! :-)
