### ISSUE TITLE
[1.16] Fluid Extractors never recover from stripped-log extraction rate.

### ISSUE THREAD

**Issue by VorpalLemur** [InnovativeOnlineIndustries/Industrial-Foregoing#978]
**Industrial Foregoing Version:** 3.2.8.2

**Titanium Version:**. 3.2.5

**Crashlog If Applicable (Upload to pastebin/gist):**

I'm playing in the direwolf20 1.16.4 modpack (1.5.1) but have experienced this issue in another 1.16 modpack recently.   Thus I've experienced this in two worlds total.  I was recently reminded that I had failed to file a bug on this while watching Direwolf20's Let's Play S10E39 where he too encounters this.

A newly placed fluid extractor will extract latex from a log at the documented rate.   For Acacia wood in the pack I'm using, that's 4mb/cycle.   It will continue extracting at this rate until the log is used up and is replaced with a stripped version of the log.  At this point, extraction continues at a much lower 1mb/cycle rate until the stripped log eventually breaks.   This all seems like expected behavior. 

The problem arises once the extractor shifts from the normal extraction rate (4mb/cycle in my case) to the stripped rate (1mb/cycle)... it never recovers.   You can break the stripped log and replace it with a fresh one and it will continue to extract from the new log at 1mb/cycle.    You can let the stripped log break entirely and then replace it with a fresh log and it will still only extract at 1mb/cycle.    Interestingly, if you allow the extractor to extract from a fresh log until the log shows damage, say 80% damage, then break and replace the log, the new log will show the same damage.   If you try this with a stripped log which is showing damage, break and replace it with a fresh log, the fresh log will now show damage (and extraction will still only be 1mb/cycle). 

I have found no way to get a fluid extractor to extract at the documented rate once it has exhausted its first log apart from breaking the fluid extractor itself and replacing it.

Expectation is that when a stripped log is broken and replaced with a fresh log, extraction will resume at the documented rate for that log. 

Expectation is that when a 'damaged' log is broken and replaced with a fresh log, the new log will start at 0% damage.   This raises the potential issue of an easy way to cheese the fluid extractor using a single log that simply gets broken and replaced over and over again by automation.  One idea to mitigate this would be: a log that is broken with more than some threshold of damage simply doesn't drop an item, or it drops its stripped version.

**Comment by Camohunter7t** [comment]
This issue does not seem to be fixed in Industrial Foregoing Version: 3.2.9.1
