### ISSUE TITLE
[1.16] Leaf Shearing Addon Missing

### ISSUE THREAD

**Issue by quasarea** [InnovativeOnlineIndustries/Industrial-Foregoing#979]
**Industrial Foregoing Version:**
industrial-foregoing-1.16.4-3.2.7-7d95990

**Titanium Version:**
titanium-1.16.4-3.2.4

As @Insomnik pointed out in Discussion https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/discussions/876 there is no leaf-shearing addon. Is this intender, or is this a bug?

**Comment by Buuz135** [comment]
Duplicate of #876

**Comment by quasarea** [comment]
@Buuz135 can't answer ?:(

**Comment by Buuz135** [comment]
Its not implemented yet that why its a feature request ...
