### ISSUE TITLE
[1.16] Crashes on startup depending on network availability. Direwolf20 pack

### ISSUE THREAD

**Issue by ST92** [InnovativeOnlineIndustries/Industrial-Foregoing#980]
**Industrial Foregoing Version:** 3.2.8.2

**Titanium Version:** 3.2.5

**Crashlog If Applicable (Upload to pastebin/gist):** https://pastebin.com/CrywvZDw

Breaks when connected to the internet. Works when network interface disabled.

**Comment by attrib** [comment]
Issue is that it tries to load: https://raw.githubusercontent.com/Buuz135/Industrial-Foregoing/master/contributors.json

Which is not a valid json.

**Comment by Buuz135** [comment]
Fixed https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/commit/bc051fa987e23f698e1c40af4a88c340b8504447 plese restart
