### ISSUE TITLE
chrash at start 1.16.5_36.0.10

### ISSUE THREAD

**Issue by JasonKillsUs** [InnovativeOnlineIndustries/Industrial-Foregoing#981]
Industrial Foregoing Version: industrial-foregoing-1.16.5-3.2.9-2215ef4.jar
TeslaCoreLib Version: titanium-1.16.5-3.2.6.jar
Crashlog (If Any): 
"https://pastebin.com/ndrVi8Zn"

**Comment by Buuz135** [comment]
Fixed https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/commit/bc051fa987e23f698e1c40af4a88c340b8504447 please restart
