### ISSUE TITLE
[1.16] Missing in Refined Storage "@industrial" search

### ISSUE THREAD

**Issue by IamStig** [InnovativeOnlineIndustries/Industrial-Foregoing#986]
**Industrial Foregoing Version:**industrial-foregoing-1.16.5-3.2.9.1-fbef27c

**Titanium Version:**titanium-1.16.5-3.2.6.1

MC 1.16.5
Forge 36.0.1

Not sure if this has not yet been implemented, I thought it was working previously. In Refined storage I can search for "Machine" and I get the 3 IF machine frames (and 1 each from RFTools, RS and Thermal) either showing as available or auto craftable but if I search @industrial I see nothing from IF not even the advanced machine frame that I know is there.
Sorry if this is not yet added, I hope it is an easy fix/add

Thanx

**Comment by Buuz135** [comment]
RS Issue that they have fixed in dev

**Comment by Industrial** [comment]
This is going to tag me a lot :(
