### ISSUE TITLE
[1.16] Plant Gatherer missing texture when placed

### ISSUE THREAD

**Issue by Apocryphai** [InnovativeOnlineIndustries/Industrial-Foregoing#987]
**Industrial Foregoing Version:**
1.16.5-3.2.9-2215ef4

**Titanium Version:**
1.16.4-3.2.5

Plant Gatherer looks fine in JEI and in hand but when placed in the world has missing texture. Custom modpack, modlist here: https://pastebin.com/ZxQ3PczK

**Comment by tyler489** [comment]
Does this occur without optifine?

**Comment by WBgroup** [comment]
Update to 3.2.9.1

**Comment by Apocryphai** [comment]
Still happened without Optifine, but updating to 3.2.9.1 fixed it. I should have checked that, thanks! :)
