### ISSUE TITLE
Animal Rancher not collecting milk 1.16.5 All the Mods 6

### ISSUE THREAD

**Issue by zombiebush** [InnovativeOnlineIndustries/Industrial-Foregoing#990]
Industrial Foregoing Version: 1.16.5 3.2.8.4
TeslaCoreLib Version: dont know couldnt find it in the mods folder (maybe thats the problem)
Crashlog (If Any): n/a

Cows are within range, progress bar is working, but no milk.  I dl'd the pack from curse and installed it using MultiMc. maybe the ATM team for the TeslaCoreLib I dont know.  The only other thing iv used for this mod so far is extracting latex and that works.

**Comment by Buuz135** [comment]
Update the mod

**Comment by zombiebush** [comment]
that did it sir, thank your for the dam near instant response.
