### ISSUE TITLE
[1.16] Dupe Bug /w Infinity Backpack

### ISSUE THREAD

**Issue by Delloga** [InnovativeOnlineIndustries/Industrial-Foregoing#992]
**Industrial Foregoing Version:**
industrial-foregoing-1.16.4-3.2.8.2-6b5c95b

**Titanium Version:**
titanium-1.16.4-3.2.5

**Modpack:**
Direwolf20 1.16.4 Version 1.5.1

There is a duping bug with the Infinity Backpack. While an item in the backpack has a placeholder (a spot with a 0) you can use the middle-mouse button to get a copy of that item while there is non in the Infinity Backpack. I have tested this with a few different items. It seems to work with anything you put in there.

**Comment by Buuz135** [comment]
Update the mod
