### ISSUE TITLE
[1.16] Animal Rancher now not shearing sheep

### ISSUE THREAD

**Issue by geeee785** [InnovativeOnlineIndustries/Industrial-Foregoing#997]
Playing ATM 6 mod pack which is using this version, industrial-foregoing-1.16.5-3.2.9.1-fbef27c.jar. The last update has fixed the cow milking with the Rancher,  but currently it is not shearing sheep.

**Comment by natebc** [comment]
Interestingly this is the same version we have in e6 and mine is shearing away:


![sheepies](https://user-images.githubusercontent.com/53818/106925605-3d2c0500-66de-11eb-8bf7-248e6ca0473e.gif)

**Comment by Buuz135** [comment]
If you have cows it will keep milking the cow until the tank is filled, then shear the sheep.
