### ISSUE TITLE
[1.16] extreme reactors ores not added to ore laser recipes

### ISSUE THREAD

**Issue by lightningjude** [InnovativeOnlineIndustries/Industrial-Foregoing#999]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Version:**
1.16.5-3.2.9.1-fbef27c
**Titanium Version:**
1.16.5-3.2.6.1
**Crashlog If Applicable (Upload to pastebin/gist):**\
https://pastebin.com/jAWbTtwV

**Comment by Tiln1** [comment]
Same case with Uraninite from Powah. (3.2.9.2)

**Comment by PhamKun** [comment]
did you successfully add Extreme Reactor Recipes to the drill yet?

**Comment by lightningjude** [comment]
in case a dev fins this and wants to know the issue
the serializer returns null

**Comment by Buuz135** [comment]
The integration is there since the start, the ore needs to have the item tag too for it to work
